### ISSUE TITLE
[Feature Request]: Breakpoints window

### ISSUE THREAD

**Issue by puremourning** [puremourning/vimspector#10]
Breakpoints can be displayed int he location list, but this is weak and not fully implemented.

We need a breakpoints window to list all breakpoints, allowing:

- move/edit/enable/disable
- view for line and function breakpoints
- etc.

UI wise, it's not obvious where to put this.

**Comment by puremourning** [comment]
There’s an undocumented ListBreakpoints function which populated the location list with line breakpoints. It’s a good start but probably not the right overall approach

**Comment by eyalk5** [comment]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/eyalkarni/.vim/plugged/vimspector/python3/vimspector/debug_session.py", line 983, in ListBreakpoints
    return self._breakpoints.ListBreakpoints()
  File "/Users/eyalkarni/.vim/plugged/vimspector/python3/vimspector/breakpoints.py", line 90, in ListBreakpoints
    if self._connection and self._codeView:
AttributeError: 'ProjectBreakpoints' object has no attribute '_codeView'
```

**Comment by puremourning** [comment]
ah, yeh... it's bugged if you call it _while_ debugging. it only works when _not_ debugging (e.g. after VimspectorReset). this is one of the reasons it's not documented  :(

**Comment by puremourning** [comment]
Actually that's easy to fix.

**Comment by eyalz800** [comment]
@puremourning I'd make a tab inside near the console window for breakpoints and add like a button for it.

**Comment by puremourning** [comment]
we currently have `call vimspector#ListBreakpoints()` which uses the QuickFix list. This has the advantage of jumping to the line where the breakpoint is, but it makes it tricky to do more with it. I don't want to re-implement what the QuickFix list does and I don't want to hack it. It's a dilemma.

**Comment by eyalz800** [comment]
@puremourning to me it sounds like the stack window functionality except it shows the breakpoints.

**Comment by eyalz800** [comment]
@puremourning 
```vim
augroup ZVimspectorCustomMappings
    autocmd!
    autocmd User VimspectorUICreated call ZVimspectorSetupUi()
augroup end
function! ZVimspectorSetupUi()
    let g:zvimspector_breakpoints_open = 0
    call win_gotoid(g:vimspector_session_windows.output)
    set ft=asm
    let b:zvimspector_output_window_height = winheight(g:vimspector_session_windows.output)
    vert rightb copen
    vert resize 40
    nnoremenu <silent> WinBar.ListBreakpoints :call vimspector#ListBreakpoints()<CR>
    call vimspector#ListBreakpoints()
    call win_gotoid(g:vimspector_session_windows.code)
endfunction
```
![image](https://user-images.githubusercontent.com/29372486/95002026-590c8680-05d8-11eb-99a7-c83bee30b761.png)

**Comment by TamaMcGlinn** [comment]
Thank you @eyalz800 I can confirm that mapping works; it also shows conditions if present, so #299 can be closed. However, it needs to get updated when breakpoints change. The current approach makes it necessary to stop and start debugging in order to see the breakpoints.

**Comment by puremourning** [comment]
@dsych has a wip PR for this. Woo. https://github.com/puremourning/vimspector/pull/437

**Comment by puremourning** [comment]
Added in #437

**Comment by eyalz800** [comment]
@puremourning this is great, however is there an option to open the breakpoint window at the right side of the command window just like in the screenshot above?

**Comment by puremourning** [comment]
no, it always opens at the bottom
