### ISSUE TITLE
Request: some clarity for all the types of "names"

### ISSUE THREAD

**Issue by lanza** [puremourning/vimspector#111]
I set up lldb-vscode via copy and pasting the config you have on the front readme. It lists an adapter named...? "lldb-vscode". It has a property called "name" with a value of "lldb". It's in a file named `lldb-vscode.json`.

I copy and paste the `.vimspector.json` you have for it. It has a `<name>`, an "adapter" key whose value seems to be some sort of "name", a configuration with a "name" : "<name>" and a "type" which refers to an adapter name. 

I haven't been able to get vimspector to launch or attach to anything yet and I can't tell what the problem is so far. But my first approach has been musical chairs with all the permutations of the word "name" and I'm not sure I've gotten it right yet.

**Comment by puremourning** [comment]
Have you read the documentation rather than just copying and pasting?

**Comment by puremourning** [comment]
https://puremourning.github.io/vimspector/

**Comment by puremourning** [comment]
The reference guide explains then configuration. The adapter name is the name of the adapter you set up. If you are having trouble making it work, happy to help, but I feel there is clarity in the reference guide including a complete json schema for the configuration format. 

If there are specific errors or omissions, please raise a specific issue.
