### ISSUE TITLE
[Feature Request]: Open current file in code view when starting a debug session

### ISSUE THREAD

**Issue by badbyte7** [puremourning/vimspector#117]
**Is your feature request related to a problem? Please describe.**
When I start a new debug session, the code window is empty, and I have to open my current source file manually. Most of the time, when I attach or launch the debugger session, I want to set a breakpoint in the file I have open right now.

**Describe the solution you'd like**
If I start a debugging session, the code window should automatically open my current file in the original tab.

**Describe alternatives you've considered**
Maybe it is configurable if it starts empty or with the current file?

**Additional context**

**Comment by puremourning** [comment]
I guess that’s possible yeah. 

Normally I just do `gt` to get back to my code tab, or more usually it breaks on connection and code window jumps to wheeever the process is. But maybe current buffer is better than empty file as a default. 

Strictly speaking though, the current file could be totally unrelated to what you are debugging (or there may not be a current file even).

**Comment by badbyte7** [comment]
You are right, it might be unrelated.

Maybe a settings parameter for the `vimspector#LaunchWithSettings ` is a better way to choose the behaviour.

**Comment by puremourning** [comment]
The would like to avoid any settings at all. There are already enough imposed by the protocol so I don’t really want vimspector to add a bunch more.

**Comment by badbyte7** [comment]
I can understand that.

Btw: You did a very good job with this plugin! It's awesome!

**Comment by puremourning** [comment]
You're too kind ;)
