### ISSUE TITLE
No information displayed with naive rust lldb adapter try.

### ISSUE THREAD

**Issue by iago-lito** [puremourning/vimspector#118]
**Describe the bug**
I keep wandering through the docs at `vimspector` and `vscode`, and I find no way properly set up Rust debugging with lldb properly. Should I use `rust-lldb`? How?

**To Reproduce**
Create dummy rust project, here:
`Cargo.toml`
```toml
[package]
name = "rust_test"
version = "0.1.0"
authors = ["Iago-lito"]
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs" 
```
`src/main.rs`
```rust
fn main() {
    let a = 5;
    let mut b = 3;

    meth(&mut b, &a);
    println!("{}", a);
    println!("{}", b);
}

fn meth(b: &mut i32, a: &i32) -> bool {
    let inner = 7;
    println!("Inside.");
    *b += a + inner;
    return true;
} 
```

Try configuring a naive `.vimspector.json`
```json
{
    "adapters": {
        "lldb": {
            "name": "lldb",
            "command": [
                "lldb",
                "-b",
                "-O",
                "command script import '$HOME/.vscode-oss/extensions/vadimcn.vscode-lldb-1.4.5/adapter'",
                "-O",
                "script adapter.main.run_stdio_session()"
            ]
        }
    },
    "configurations": {
        "simple_rust - launch": {
            "adapter": "lldb",
            "configuration": {
                "name": "LLDB: Launch",
                "type": "llbd",
                "request": "launch",
                "cwd": "${workspaceRoot}",
                "args": [],
                "program": "${workspaceRoot}/target/debug/main"
            }
        }
    }
} 
```
Set up a breakpoint inside `meth()`, then `:call vimspector#Launch()`.

**Expected behavior**
5 windows open in a new tab, with debugging information.

**Actual behaviour**
The windows are mostly empty. The interpreter trivially evaluates any `<random-input>` to `<random-input>` like a schoolcase echo server. The stacktrace seems to work, but the "Scopes" are empty, and there are no "Variables" listed in corresponding window :(

[.vimspector.log](https://github.com/puremourning/vimspector/files/4205069/vimspector.log)
![UI](https://user-images.githubusercontent.com/10091387/74544184-039b4080-4f47-11ea-9e6b-83c7e8003049.png)

**Environment**

```
$ uname -a
Linux etak 5.5.2-arch1-1 #1 SMP PREEMPT Tue, 04 Feb 2020 18:56:18 +0000 x86_64 GNU/Linux

$ nvim --version
NVIM v0.5.0-374-gd9657b3ae
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/iago-lito/.cache/yay/neovim-git/src/neovim-git/build/config -I/home/iago-lito/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/iago-lito/.cache/yay/neovim-git/src/neovim-git/build/src/nvim/auto -I/home/iago-lito/.cache/yay/neovim-git/src/neovim-git/build/include
Compilé par iago-lito@etak

Features: +acl +iconv +tui
See ":help feature-compile"

         fichier vimrc système : "$VIM/sysinit.vim"
               $VIM par défaut : "/usr/share/nvim"

Run :checkhealth for more info

$ git rev-parse HEAD
79df51e83c8775f34fcf5c225f0c5c152d52094e
```
```
$ which vim 
vim: aliased to nvim -p

$ which nvim
/usr/bin/nvim
```

`:py3 pass` and `:py3 import vim` yield nothing.

```
:checkhealth
health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle found
  - OK: Service started

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5803'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python version: 2.7.17
  - INFO: pynvim version: 0.3.2 (outdated; from /usr/lib/python2.7/site-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.1

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.8.1
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v10.18.1
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - WARNING: `perl` and `cpanm` must be in $PATH.
    - ADVICE:
      - Install Perl and cpanminus and verify that `perl` and `cpanm` commands work.
```

I am very excited to see DAP interacting with Vim, thank you for this huge work. And thank you for support :)

**Comment by puremourning** [comment]
From the screenshot, everything appears to be working...

> there are no "Variables" listed in corresponding window

They are collapsed scopes (scopes are collapsed by default when they are marked as "expensive" to calculate), put the cursor on one of them (e.g. Locals) and hit `<CR>` as explained in the docs.

> The interpreter trivially evaluates any <random-input> to <random-input> like a schoolcase echo server

I have no clue what you mean by 'interpreter' here and I sort of resent the tone, but I'm assuming this was meant in jest.... could you perhaps elaborate on what you meant ?

> Expected behavior
5 windows open in a new tab, with debugging information.

That appears to be what's happening.

If you were using Vim, then the Watch window would be a prompt buffer, but it looks like you're using neovim, so you have to use the ex commands and get a largely weaker experience.

If you want to add a watched variable, use `:VimspectorWatch` if you want to see different output in the bottom window, use `:VimspectorShowOutput`. These are all documented in the README.

I assume you've worked out from the docs how to step over, step into etc. ?

---

P.S. thanks for sharing your config for using vscode-lldb. I hadn't got round to working out how to make it run a stdio server rather than a tcp one!

---

**Comment by iago-lito** [comment]
Hm, it's hard to tell what feels wrong because I'm not used to it. But waybe you're right and everything is fine? I'll try to elaborate.

> They are collapsed scopes (scopes are collapsed by default when they are marked as "expensive" to calculate), put the cursor on one of them (e.g. Locals) and hit \<CR> as explained in the docs.

I understand this, but nothing happens when I hit `<cr>` in this window or even when I `:call vimspector#ExpandVariable()` (whereas that the same actions do expand correctly when I'm debugging `python` script instead). With rust, it's just like the scopes were empty, but I feel they should not be.. unless they should in this case?

> I have no clue what you mean by 'interpreter' here and I sort of resent the tone, but I'm assuming this was meant in jest.... could you perhaps elaborate on what you meant ?

I'm referring to the window right below the code window in [my screenshot](https://user-images.githubusercontent.com/10091387/74544184-039b4080-4f47-11ea-9e6b-83c7e8003049.png). Sorry for the tone, the jest was about the following behaviour :)

![echo server](https://user-images.githubusercontent.com/10091387/74560450-dfe7f280-4f66-11ea-880f-20df164a60a4.png)

I feel like I should have got errors during evaluation of some of these inputs, and that one of the two middle lines should have yielded to `3` or `&3` or something. But the "echo server" has proved to be quite consistent in sticking to its behaviour ;) Considering what you wrote next (see below), I think I have mistaken this window for the "watch" window, whereas it could actually be the "output" window?

> If you want to add a watched variable, use :VimspectorWatch if you want to see different output in the bottom window, use :VimspectorShowOutput. These are all documented in the README.

Sorry for having missed that one. `:VimspectorWatch b` does correctly displays `3` in the.. actual watch window. This is why I think now that the "echo" window actually was the output window.

> I assume you've worked out from the docs how to step over, step into etc. ?

Yes, although I have not tried it much yet, I'm still puzzled whether `lldb` is working or not.

> P.S. thanks for sharing your config for using vscode-lldb. I hadn't got round to working out how to make it run a stdio server rather than a tcp one!

Not sure what you mean or how I have helped you (have I?), but you're welcome :)

Sorry for being this confused, I'll have a thorougher relecture of the docs on monday to check for other things I probably have missed, so I can help us converging to a more meaningful "issue" :) BTW are there other channels we could get in touch with other users in a more informal way, so as to clarify confusion without cluttering the issue tracker?

**Comment by puremourning** [comment]
Can you gist or post your `.vimspector.log` ? You can open it in the output window with `:VimspectorShowOutput Vimspector-out` or it's just `~/.vimspector.log`. this will tell me what's going on.

It's likely just that lldb (or vscode-lldb) isn't doing a good job with evaluate requests or supplying locals, but it could also be that we're failing to parse the results correctly,

**Comment by puremourning** [comment]
I was able to get your example project to work with `vscode-cpptools` using the following config:

<img width="954" alt="Screenshot 2020-02-14 at 22 50 34" src="https://user-images.githubusercontent.com/10584846/74574730-7b379280-4f7c-11ea-9d45-502df601fdb2.png">

```json
{
  "configurations": {
    "simple_rust - launch": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "name": "LLDB: Launch",
        "type": "cppdbg",
        "request": "launch",
        "cwd": "${workspaceRoot}",
        "args": [],
        "program": "${workspaceRoot}/target/debug/main",
        "stopAtEntry": true,
        "MIMode": "lldb",
        "miDebuggerPath": "/Users/ben/Development/llvm-project/lldb-mi/build.brew/src/lldb-mi",
        "externalConsole": true
      }
    }
  }
}

```

Note that I'm using my build of `lldb-mi`; as directed [here](https://github.com/puremourning/vimspector#c-c-rust-etc)

**Comment by iago-lito** [comment]
> Can you gist or post your .vimspector.log ?

There is one in my first post, but I can't remember what I've done exactly when I was recording it (maybe just a few tries to `ExpandVariables()` or something). Do you need a more complete one where I would try more specific actions?

> [.vimspector.log](https://github.com/puremourning/vimspector/files/4205069/vimspector.log)

---

> I was able to get your example project to work with vscode-cpptools

I does work with this adapter :D Thank you for this hint. Here is the `.vimspector.json` I'm finally using :)

```json
{
    "adapters": {
        "lldb": {
            "name": "lldb",
            "command": [
                "lldb",
                "-b",
                "-O",
                "command script import '${HOME}/.vscode-oss/extensions/debugAdapters/OpenDebugAD7",
                "-O",
                "script adapter.main.run_stdio_session()"
            ]
        }
    },
    "configurations": {
        "simple_rust - launch": {
            "adapter": "vscode-cpptools",
            "configuration": {
                "name": "LLDB: Launch",
                "type": "cppdbg",
                "request": "launch",
                "cwd": "${workspaceRoot}",
                "args": [],
                "program": "${workspaceRoot}/target/debug/main",
                "stopAtEntry": true,
                "externalConsole": true
            }
        }
    }
} 
```

Should I close the issue (I can now debug rust <3) or should it remain open since it is unsure why my initial config failed?

Thank you for support :)

**Comment by puremourning** [comment]
Let's close it. Your initial one didn't work due to some problem with the debug adapter, not vimspector.

```
2020-02-14 16:23:40,742 - DEBUG - Message received: {'type': 'event', 'seq': 0, 'event': 'output', 'body': {'category': 'stderr', 'output': 'Internal debugger error:\nTraceback (most recent call last):\n  File "/home/iago-lito/.vscode-oss/extensions/vadimcn.vscode-lldb-1.4.5/adapter/debugsession.py", line 1366, in handle_message\n    result = handler(args)\n  File "/home/iago-lito/.vscode-oss/extensions/vadimcn.vscode-lldb-1.4.5/adapter/debugsession.py", line 935, in DEBUG_variables\n    time_limit = time.clock() + self.evaluation_timeout\nAttributeError: module \'time\' has no attribute \'clock\'\n\n'}}
2020-02-14 16:23:40,767 - DEBUG - Message received: {'type': 'response', 'command': 'variables', 'request_seq': 11, 'success': False, 'body': {'error': {'id': 0, 'format': "Internal debugger error: module 'time' has no attribute 'clock'", 'showUser': True}}}
```

That is:

`Internal debugger error: module 'time' has no attribute 'clock'`

Vimsepctor could do a better job of displaying that.

**Comment by GopherJ** [comment]
hi @iago-lito Are you using vscode-lldb? I tried vscode-cpptools but found its display of HashMap is really bad

**Comment by iago-lito** [comment]
Hi @GopherJ, I am not. Are you having troubles with `vscode-lldb`? Or do you mean that it is working even better than `vscode-cpptools`?  
I am not debugging Rust at the moment, so the details of this issue are a little blur in my memory now X)

**Comment by GopherJ** [comment]
@iago-lito Hi thanks for your reply, I didn't try `vscode-lldb` does it worked for you? `vscode-cpptools` doesn't really working great. Some rust type isn't well displayed.

That's why I would like to ask you if you succeed to make `vscode-lldb` works

**Comment by iago-lito** [comment]
Okay :) Well, as far as I remember, I could not manage to get `vscode-lldb` working in the end, but I was satisfied enough with `vscode-cpptools` for the short debugging session I was needing back then. Now, I haven't used either of those in a while, so I don't know which one is best, or whether `vscode-lldb` is working now.
