### ISSUE TITLE
[Feature Request]: Don't prompt users to enter a variable that is already defined in the configuration

### ISSUE THREAD

**Issue by Nnoerregaard** [puremourning/vimspector#128]
First of all, I'd like to say I really love your work with Vimspector! It's incredibly useful. I've noticed a minor inconvenience with it though.

**Is your feature request related to a problem? Please describe.**
When defining a variable in the `variables: {}` portion of `.vimspector.json` and subsequently using that exact same variable later in the configuration, I'm still prompted to enter that variable upon starting the debugger even though it has already been set in the configuration

**Describe the solution you'd like**
I'd like vimspector to skip user prompt for variables that are already defined in the configuration file.

**Describe alternatives you've considered**
Right now the workaround is simply to ignore the prompt and press enter without entering any values. The debugger receives the value as configured and everything works as expected. 

Also, I figured out the vscode-node adapter can apparently figure out on its own to connect to the node process when it's running in debug mode so another workaround is to simply omit the processId line altogether and debugging works without any prompt. However, I still think it would be nice to not be prompted in the cases where a variable is indeed necessary.

**Additional context**
Here is my .vimspector.json file. I realize setting a variable through a shell command is rather advanced so I tested it by simply setting `"processId: --someValue--"` as well, and that exhibits the exact same behavior
```
{
  "configurations": {
    "launch": {
      "adapter": "vscode-node",
      "configuration": {
        "variables": {
          "processId": {
            "shell": [
              "ps | grep ${workspaceRoot}/node_modules/.bin/node | grep -v grep | sed -n 's/\\([[:digit:]]*\\).*/\\1/p'"
            ]
          }
        },
        "type": "node",
        "request": "attach",
        "name": "Attach by Process ID",
        "processId": "${processId}"
      }
    }
  }
}
```

**Comment by puremourning** [comment]
Hmmmm. Are you on the latest commit? I feel like I fixed this recently....

**Comment by puremourning** [comment]
Yeah I just tested it and it works for me.

And I just realised what the problem is . Your `variables` block is in the wrong place. It should be like this:

```json
{
  "configurations": {
    "launch": {
      "adapter": "vscode-node",
        "variables": {
          "processId": {
            "shell":  "ps | grep ${workspaceRoot}/node_modules/.bin/node | grep -v grep | sed -n 's/\\([[:digit:]]*\\).*/\\1/p'"
          }
        },

      "configuration": {
        "type": "node",
        "request": "attach",
        "name": "Attach by Process ID",
        "processId": "${processId}"
      }
    }
  }
}

```

I changed 2 things:

- move the `variables` block out of the launch config block.
- change the command to a string. It should be a string or a list where each arg is a string. As you're using a pipe, it's easier to just use a string.
