### ISSUE TITLE
[Feature Request]: Guide on setting up python debugging

### ISSUE THREAD

**Issue by RonanMacF** [puremourning/vimspector#130]
Hi,

I have installed and attempted to setup vimspector on neovim, however, everytime I try to get it to work I get the error`Request for initialize aborted: Closing down`. I have installed the python gadbet and deubgpy tool, copied the imspector.json python config and hardcoded in the workspace/file paths to get it to work but no luck every time. 

I have attemoted to look online to find a solution but did not come across any, all I came across was other people having the same issue such as the reddit post[here](https://www.reddit.com/r/neovim/comments/f0yznl/help_configuring_vimspector_for_python/).

I, and others i'm sure, would appreciate a python guide similar to the vim guide on the website to make setting up python much easier.

Kind regards,

**Comment by puremourning** [comment]
Please can you see CONTRIBUTING.md and provide all of the requested diagnostics in a new issue, completing the issue template. I'm confident we can make this work for you, but I require the diagnostics.
