### ISSUE TITLE
[Feature Request]: Allow comments in .vimspector.json

### ISSUE THREAD

**Issue by noscript** [puremourning/vimspector#135]
`.vimspector.json` is similar to VSCode's `tasks.json` or `launch.json` but unfortunately I cannot put any comments there.

It would be great to switch to [JSON with Comments (jsonc)](https://code.visualstudio.com/docs/languages/json) for vimspector config files.

**Comment by puremourning** [comment]
vimspector uses pure python `json` module. I don't intend to either add any non-pure-python dependencies or write a custom json parser.

I agree that lack of comments is a pain (tbh i strongly regret using json for this at all).

FWIW, vimspector won't choke on a key it doesn't know, so you can at least do:

```json
{
  "configurations": {
     "test": {
      "comment": "This is a comment"
     }
}
```

I know that's pretty crappy, but ... json.

**Comment by puremourning** [comment]
Having said that i'm going to leave this open. It's actually not difficult to write a trivial filter for line comments at least. I'd probably consider a PR if it were simple enough.

**Comment by puremourning** [comment]
My preference, however would be to use `#` comments, as these would be compatible if we switched to a yaml parser (the only reason json is used over yaml is that yaml is not in pure python standard library)

**Comment by noscript** [comment]
Using keys is last resort but neither that or `#` comments would be highlighted properly.

**Comment by puremourning** [comment]
`//` comments wouldn't be highlighted properly either in a json file.
at least with `#` you could `setf yaml` (yaml is a superset of json)

**Comment by puremourning** [comment]
it seems to be contentious. 

https://github.com/nlohmann/json/tree/f272ad533d32a40a3b2154a76f1ae9a45eacd6d3#comments-in-json

interesting

**Comment by puremourning** [comment]
there's a tiny json minify here: https://github.com/getify/JSON.minify/blob/python/json_minify/__init__.py
