### ISSUE TITLE
[Feature Request]: Use current working directory as gadget directory

### ISSUE THREAD

**Issue by LinArcX** [puremourning/vimspector#137]
**Is your feature request related to a problem? Please describe.**
Hi. i'm using nix + direnv + lorri on void linux to develop c/c++ applications.

The problem that i have with integrating nix with vimspector is that [the path of gadgets directory can't change right now.](https://github.com/puremourning/vimspector#the-gadget-directory)

This is the content of lldb-vscode.json:(~/.config/nvim/plugged/vimspector/gadgets/linux/.gadgets.d/lldb-vscode.json)
```
{
  "adapters": {
    "lldb-vscode": {
      "attach": {
        "pidProperty": "pid",
        "pidSelect": "ask"
      },
      "command": [
        "/usr/bin/lldb-vscode"
      ],
      "env": {
        "LLDB_LAUNCH_FLAG_LAUNCH_IN_TTY": "YES"
      },
      "name": "lldb"
    }
  }
}
```

As you can see i hardcoded the path: `/usr/bin/lldb-vscode`

But in nix the path are hashes.(maybe something like this: `5vrk0asc16lbkbwn87yaxq38pliwn91s-foo`)

**Describe the solution you'd like**
I think it's a good way to let users define their gadgets settings inside their projects.(in .nvimrc files for instance)

**Describe alternatives you've considered**

**Additional context**

**Comment by puremourning** [comment]
> I think it's a good way to let users define their gadgets settings inside their projects.(in .nvimrc files for instance)



You can define `adapters` in `.vimspector.json` which is project specific.
