### ISSUE TITLE
Compatibility with vim in ubuntu16.04

### ISSUE THREAD

**Issue by qlibp** [puremourning/vimspector#143]
**Is your feature request related to a problem? Please describe.**
Need some change, in order to support Ubuntu 16.04. When using apt-get to get vim in Ubuntu 16.04, the vim version can satisfy the minimum request, but python3.5 is pre-built inside vim. However, the code you wrote in python, uses f string, which is not compatible with python3.5 and throwing out error.

**Describe the solution you'd like**
Maybe changes on this could make vimspector compatible in ubuntu16.04. Otherwise, user could only use vimspector after rebuilding vim from source.

Best

**Comment by puremourning** [comment]
Sorry compatibility with legacy vim or python versions is not a goal for this project at present.

**Comment by puremourning** [comment]
Also, vimspector requires vim 8.2, so I'd be surprised in ubuntu 16.04 has that, as the version in ubuntu 18.04 is 8.0
