### ISSUE TITLE
Unavilable

### ISSUE THREAD

**Issue by huanhexiao** [puremourning/vimspector#144]
**Describe the bug**

Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/huanhexiao/.vim/pack/vimspector/opt/vimspector/python3/vimspector/debug_session.py", line 95
    self._logger.debug( f'Reading gadget config: {gadget_config_file}' )
                                                                     ^
SyntaxError: invalid syntax

**To Reproduce**
List of steps to reproduce

Vimspector config file:

```
paste .vimspector.json here
```

**Expected behavior**

**Actual behaviour**
What actually happened, including output, log files etc.

Please include:
* Vimspector log (~/.vimspector.log)
* Output from any or all UI diagnostic tabs (Server, etc.)

**Environemnt**

NOTE: NeoVim is supported only on a best-effort basis. Please check the README
for limitations of neovim. Don't be offended if I ask you to reproduce issues in
Vim.

NOTE: Windows is not supported. There is a branch with windows support, which
you can contribute to, rather than opening an issue.

* Version of Vimspector: (e.g. output of `git rev-parse HEAD` if cloned or the
  name of the tarball used to install otherwise)

* Output of `vim --version` or `nvim --version`

```
paste here
```

* Output of `which vim` or `which nvim`:

```
paste here
```

* Output of `:py3 pass`:

```
paste here
```

* Output of `:py3 import vim`:

```
paste here
```

* For neovim: output of `:checkhealth`

```
paste here
```

* Operating system: <linux or macOS> and version

**Additional context**

**Comment by puremourning** [comment]
See Dependencies. 

But first, see CONTRIBUTING..md

You need vim compiled with python 3.6
