### ISSUE TITLE
[Feature Request]: CodeLLDB adapter support

### ISSUE THREAD

**Issue by neiljohari** [puremourning/vimspector#145]
**Is your feature request related to a problem? Please describe.**

I've been having issues with vscode-cpptools for a while (https://github.com/microsoft/vscode-cpptools/issues/3829#issuecomment-606314684). The recent comments suggest it may have been patched but I've been sticking with CodeLLDB since it works.

**Describe the solution you'd like**

It would be nice if install_gadgets could add support for CodeLLDB. I am familiar enough with how vimspector works to add a new gadget and send in a PR, though I don't mind playing around with it for a bit given some pointers.

**Describe alternatives you've considered**

I've tried using vscode-cpptools and lldb-vscode but have issues with input redirection.

**Comment by neiljohari** [comment]
Also it seems like there was a fix issued for the issue described in the README (verision 0.27) https://github.com/microsoft/vscode-cpptools/issues/3829#issuecomment-606314684

Does that affect vimspector at all?

**Comment by puremourning** [comment]
If memory serves me correctly codelldb uses a very strange way of starting the debug adapter that isn't really compatible with the standard DAP way of doing things, but if you can find a way to start it and it implements the DAP correctly, then it should work with vimspector.

I have certainly tried in the past to use codelldb but failed. You're welcome to try, but I won't be "officially" supporting it, because it's too wonky.

**Comment by GopherJ** [comment]
@puremourning Hi, just come across this issue, I'm also interested in CodeLLDB because it has better support on rust. With vscode-cpptools the display of variable values is horrible.

**Comment by puremourning** [comment]
@GopherJ My last post explains the situation. Vimspector is compatible with any DAP-compliant server. So feel free to try.

**Comment by puremourning** [comment]
Update: We spoke on Gitter, and it appears that CodeLLDB can work outside of VSCode now.

What's needed is to start the adapter, which will listen on a port, then vimspector can connect to it using `multi-session` adapter.

https://files.gitter.im/5bfc5f15d73408ce4fb023af/Imjx/image.png

```
leave that running
then use this :
                     "adapter": "multi-session",
when it asks for a port, give it 46359
```

**Comment by puremourning** [comment]
What we need is some way to launch the adapter and work out the port (annoyingly it probably requires reading its stdout :(
