### ISSUE TITLE
[Feature Request]: Conditional breakpoints

### ISSUE THREAD

**Issue by adam-r-kowalski** [puremourning/vimspector#152]
Currently three types of breakpoints are supported (function, line and exception breakpoints). This has already been extremely helpful when working on larger projects. However, often times I find myself wanting conditional breakpoints in order to only pause the program when a very specific situation is occurring.

I believe the protocol supports conditional breakpoints and projects such as [emacs dap](https://github.com/emacs-lsp/dap-mode#debugger-commands) supports adding them. 

Currently I find myself running lldb directly or switching to another editor such as emacs when dealing with conditional breakpoints and then switching back to vim when I want to keep working, but it would be great to have everything in one place.

Thanks again for all your hard work on this project.

**Comment by puremourning** [comment]
One of the tricky parts of this is that I currently [don't have a good UI for breakpoint management](#10), so I have been trying to resist adding too many breakpoints-related features until I've sorta worked out how to do that well.

Sounds crazy, right? Don't add breakpoint features to a debugger UI. I know. But I wanted to avoid adding something that subsequently became a blocker to doing something good.

But great, enemy of good, enemy of useful and all that.

Would something like this work for you: add a new argument (condition) to the vimscript function `ToggleBreakpoint`: `vimspector#ToggleBreakpoint( '<condition here>' )` (I might actually add an options dict). That way you can add a mapping like `nnoremap <leader><F9> :call vimspector#ToggleBreakpoint( input( "Enter condition: " ) )<CR>` ?

I know, it's a bit weak, but it would be fairly easy to do and wouldn't commit me to building a _good_ UI/UX for this, at the expense of users having to build it themselves.

I dunno that sounds dumb; I could just add a `<plug>` mapping that does the above I suppose.

Thoughts?

**Comment by puremourning** [comment]
@adam-r-kowalski I pushed a branch with basic support. If using 'HUMAN' mappings, then `<leader><F9>` adds a conditional breakpoint. Quick demo:

![vimspector-conditional-bp-demo](https://user-images.githubusercontent.com/10584846/80287915-32464c00-872c-11ea-983c-b971227dc892.gif)

**Comment by adam-r-kowalski** [comment]
Wow you work fast!! Amazing work, thanks for resolving this so quickly.

**Comment by TamaMcGlinn** [comment]
This works, but it doesn't appear to be possible to see the conditions already assigned to a breakpoint. Also, when you add a conditional breakpoint where there is already a (conditional or not) breakpoint, it *deletes* the breakpoint and discards your input. That is rather unexpected behaviour.

Suggest that if you try to add a conditional breakpoint where there already is a breakpoint, the input is pre-populated with the current condition (if any), and of course it first deletes the breakpoint but then also adds the new one; that way you can edit/view the conditional breakpoint by adding another conditional breakpoint, and just press enter again if you just wanted to view it, solving both the deletion and visibility problems without adding new interface elements.

**Comment by puremourning** [comment]
Feel free to raise a new issue with your feature request and/or bug report. If you have good ideas, I'm open to discussion and PRs too.

**Comment by puremourning** [comment]
did I not add the condition to the `:call vimspector#ShowBreakpoints()` output ? I thought I did, but may be misremembering.
