### ISSUE TITLE
Reset after closing windows

### ISSUE THREAD

**Issue by eyalk5** [puremourning/vimspector#159]
**Describe the bug**

When you close some windows of vimspector, and after that try to do Launch or Reset or Restart, it presents different erros. Most notably:
```
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/eyalkarni/.vim/plugged/vimspector/python3/vimspector/debug_session.py", line 930, in OnServerExit
    self.Clear()
  File "/Users/eyalkarni/.vim/plugged/vimspector/python3/vimspector/debug_session.py", line 924, in Clear
    self._stackTraceView.Clear()
  File "/Users/eyalkarni/.vim/plugged/vimspector/python3/vimspector/stack_trace.py", line 74, in Clear
    with utils.ModifiableScratchBuffer( self._buf ):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/eyalkarni/.vim/plugged/vimspector/python3/vimspector/utils.py", line 142, in ModifiableScratchBuffer
    if buf.options[ 'modifiable' ]:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pynvim/api/common.py", line 88, in __getitem__
    return self._get(key)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pynvim/api/common.py", line 51, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: Invalid buffer id: 41
Can't send message: Job was not initialised correctly
```

**To Reproduce**
List of steps to reproduce

Launch python. close some vimspector windows (:q), try the mentioned commands. 

Vimspector config file:

```
{
  "configurations": {
    "genhash: Launch": {
      "adapter": "debugpy",
      "configuration": {
        "name": "genhash: Launch",
        "type": "python",
        "request": "launch",
        "python": "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python" ,
        "cwd": "/Users/eyalkarni/utils/ad_scripts",
        "stopOnEntry": true,
        "console": "externalTerminal",
        "debugOptions": [{"justMyCode": false}],
        "program": "/Users/eyalkarni/utils/ad_scripts/genhash.py",
        "args":["password1"]
      }
    }
  }
}
```

**Environemnt**

NOTE: NeoVim is supported only on a best-effort basis. Please check the README
for limitations of neovim. Don't be offended if I ask you to reproduce issues in
Vim.

NOTE: Windows is not supported. There is a branch with windows support, which
you can contribute to, rather than opening an issue.

* Version of Vimspector: (e.g. output of `git rev-parse HEAD` if cloned or the
  name of the tarball used to install otherwise) 2451d56de4a16eecb62befade3289345aa6491c5

* Output of `vim --version` or `nvim --version`
NVIM v0.5.0-418-g87d892afa
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/usr/local/opt/gettext/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

* Operating system:  macOS

**Comment by puremourning** [comment]
> close some vimspector windows

which ones?

**Comment by puremourning** [comment]
I have generally been putting these sorts of things under this umbrella: https://github.com/puremourning/vimspector/issues/86

But the truth is that's a bit of a cop out because the likelihood of #86 being worked on is quite slim - it's a lot of work and not completely obvious what to do exactly.

I guess we can at least catch the errors.

**Comment by whitebyte** [comment]
Happens to me as well after closing basically any vimspector window
`NVIM v0.5.0-559-ga0a84fc9e`
