### ISSUE TITLE
[Feature Request]: jump to cursor (support GoTo/GoToTaregets) request

### ISSUE THREAD

**Issue by eyalk5** [puremourning/vimspector#161]
Hi, I think that it could be nice to have an option to set the next line that will be executed.
At least in python. This is similar to the `j` command in pdb. 

debugpy seems to support it.

Thanks.

**Comment by puremourning** [comment]
I agree, run to cursor would be nice.

 I find it kind of annoying that there is no support for temporary breakpoints in DAP directly. Means I have to have the stateful logic in the client (vimspector) which seems the wrong place for it. This is the main reason I haven’t implemented this yet.

**Comment by puremourning** [comment]
> set the next line that will be executed

I just realised I might have misunderstood. Are you referring to the [GoTo request](set the next line that will be executed) which basically forcefully sets the PC to some line ? Or "run-to-cursor" ?

If the GoTo request, we could implement that... though it would be a little tricky because the protocol requires that we use the GoToTargets request to get the possible targets, which is a little awkward.

**Comment by eyalk5** [comment]
Goto request. run-to-cursor is nice too but this obstacle can be overcome using breakpoints.

**Comment by vds2212** [comment]
Thank you very much!

It seems to work fine :-)

There is a minor glitch it seems that when I use the following mapping:
``nmap <C-F11> <Plug>VimspectorGoToCurrentLine``

I have to hit <kbd>Enter</kbd> for the operation to occur.

I don't have the problem If I call the function explicitely:
``:call vimspector#GoToCurrentLine``<kbd>Enter</kbd>

**Comment by puremourning** [comment]
Not sure what's up with your mapping, but this works for me:

```
  nmap <silent> <LocalLeader>g <Plug>VimspectorGoToCurentLine
```

**Comment by vds2212** [comment]
I'm running Vim 8.2 including patch 1-3493 on Windows.
I have made a test disabling all plugins but Vimspector

I have the problem with the proposed mapping.
Let me know if you want me to test another version or in other conditions.

**Comment by puremourning** [comment]
If you think it is a reproducible bug in vimspector then raise an issue.

**Comment by vds2212** [comment]
I think there is spelling error. The documentation mention:
``<Plug>VimspectorGoToCurrentLine``

But the mapping that works is:
``<Plug>VimspectorGoToCurentLine``

**Comment by puremourning** [comment]
Ah ok, I'll fix that.

**Comment by puremourning** [comment]
fixed thanks.

**Comment by vds2212** [comment]
It works! Great!
