### ISSUE TITLE
Vimspector + netcoredbg is not functional.

### ISSUE THREAD

**Issue by altmnt** [puremourning/vimspector#163]
Hi. Recently I decided to give a c# + netcore + vim  another try and discovered vimspector. Unfortunately when I tried a simple console app debugging it failed. Vimspector screen would show up and I could see the code window but Stacktrace, Watches and other were empty. Upon looking in the logs I discovered that DAP `threads ` command fails with 0x80131302 error code (Process not synchronized).  

The main reason of this behavior seems to be netcoredbg which fails to perform `threads ` command when not in stopped/breakpoint state. After commenting `threads` command in vimspector everywhere except in `stopped` event handler vimspector started to work (or seemed so) which is a temporary solution apparently. 

Netcoredbg would fail on any `threads` command after `threads` event because of that as well. I am aware that according to DAP specification adapter should return dummy threads in if it is impossible to get the current threads state (after startup phase). 

While the root cause of this issue is `netcoredbg` DAP implementation and bug must be addressed on their side I still think that failed `threads` command should be treated correctly in vimspector and not make it look frozen (must be due `_requesting_threads `variable not resetting? didnt have time to go deep.) 

System specs:
.netcore 3.0/3.1
neovim 0.4.3/vim 8.1
Windows WSL2 or Mac OS 10.15  (repro in both)

Log file: 
[vimspector.log](https://github.com/puremourning/vimspector/files/4614212/vimspector.log)

**Comment by puremourning** [comment]
> Netcoredbg would fail on any threads command after threads event because of that as well. I am aware that according to DAP specification adapter should return dummy threads in if it is impossible to get the current threads state (after startup phase).

Yes, this is an adapter bug.

> While the root cause of this issue is netcoredbg DAP implementation and bug must be addressed on their side I still think that failed threads command should be treated correctly in vimspector and not make it look frozen (must be due _requesting_threads variable not resetting? didnt have time to go deep.)

Maybe but this seems niche. I don't have the time or impetus to faff around working around broken servers. Vimspector polish level at this stage doesn't call for this sort of defensiveness.

I haven't updated the netcoredebug adapter for quite some time, so maybe try updating `install_gadget.py` to pull the latest server ? Perhaps it's been patched.

**Comment by altmnt** [comment]
install_gadget seems to be always pulling the latest version. I don't think it has been patched. It might not be even netcoredbg problem but underlying dbg shim libs from microsoft.

Main concern here that vimspector skips failed `threads` command and considers it infinitely in progress.

**Comment by puremourning** [comment]
Ah you know what, you're right. There's a bug here. When the threads request _fails_, we don't reset [self._requesting_threads](https://github.com/puremourning/vimspector/blob/master/python3/vimspector/stack_trace.py#L59)

I can repro. Will fix this.
