### ISSUE TITLE
Remote debugging asks for PID

### ISSUE THREAD

**Issue by noscript** [puremourning/vimspector#165]
**Describe the bug**
Attaching to gdbserver should not require entering PID, [`miDebuggerServerAddress`](https://code.visualstudio.com/docs/cpp/launch-json-reference#_midebuggerserveraddress) config option is ignored.

**To Reproduce**
1. Start gdbserver:
```
$ gdbserver localhost:2345 ./cast
Process ./cast created; pid = 26845
Listening on port 2345
```
2. Attach using Vimspector config:
```json
{
  "configurations": {
    "test-attach": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "type": "cppdbg",
        "request": "attach",
        "program": "~/cpp_tests/cast",
        "args": [ ],
        "cwd": "~/cpp_tests",
        "environment": [  ],
        "externalConsole": true,
        "MIMode": "gdb",
        "miDebuggerPath": "/usr/bin/gdb",
        "miDebuggerServerAddress": "localhost:2345"
      }
    }
  }
}
```

**Expected behavior**
Debugging starts normally.

**Actual behaviour**
Vimspector asks to enter PID.

When using plain gdb, it is enough to provide hostname and port number:
```
$ gdb ./cast
(gdb) target remote localhost:2345
Remote debugging using localhost:2345
...
```

**Comment by puremourning** [comment]
Use: "request": "launch"

**Comment by noscript** [comment]
That works, thanks.

**Comment by puremourning** [comment]
👍
