### ISSUE TITLE
[Feature Request]: Node 12+ support

### ISSUE THREAD

**Issue by JbIPS** [puremourning/vimspector#176]
Since today Node12 is the [current LTS](https://nodejs.org/en/about/releases/) (until the end of the year), I figure it would be nice to support those new versions.

Could you tell me the changes that limits the support to < 12? I'm ready to explore solutions but I don't understand the problem yet.

Thank you for your help

**Comment by puremourning** [comment]
You mean for the node debugger ?

The debug adapter is crappy and only tested in VSCode. The result is that it only runs in the embedded node environment that VScode uses, which i believe is node 10..

I think i asked them to support other nodes and they said no.

If you can get https://github.com/microsoft/vscode-node-debug2 to work in node 12, by all means we can update. Maybe just try the latest ?

**Comment by puremourning** [comment]
relevant vimspector installer code:

https://github.com/puremourning/vimspector/blob/master/install_gadget.py#L348-L366
https://github.com/puremourning/vimspector/blob/master/install_gadget.py#L473-L491

**Comment by JbIPS** [comment]
I feared this kind of external requirements.

I'll look at this and try a few times to see what goes wrong (or not).

**Comment by puremourning** [comment]
Thanks!

I don't node so i don't use this adapter very often. if anyone can find a way to run the debug adapter without the vscode extension itself, or find a pre-built version of the extension that we can install instead, that's also an option

**Comment by puremourning** [comment]
Any luck @JbIPS ?

I think I'm going to close this as not really something I can fix :/

**Comment by JbIPS** [comment]
I didn't look at it yet but sure, close it, I'll give you updates when I have time to look at it!
