### ISSUE TITLE
install gadget error: "This script should *not* be run as super user. Aborting." when not using sudo

### ISSUE THREAD

**Issue by RonanMacF** [puremourning/vimspector#177]
**Describe the bug**
An attempt to install any gadget e.g. `./install_gadget.py --enable-go` is resulting in the command saying `This script should *not* be run as super user. Aborting`. As is clear from the command I am not using sudo.

Vimspector config file:

```
  {
     "configurations": {
        "<name>: Launch": {
           "adapter": "debugpy",
           "configuration": {
              "name": "<name>: Launch",
              "type": "python",
              "request": "launch",
              "cwd": "${workspaceRoot}",
              "python": "/usr/local/bin/python3",
              "stopOnEntry": true,
             "console": "externalTerminal",
             "debugOptions": [],
             "program": "${file}"
         }
      }
    },
     "run": {
       "adapter": "vscode-go",
        "configuration": {
         "request": "launch",
           "program": "${fileDirname}",
          "mode": "debug",
          "dlvToolPath": "$HOME/go/bin/dlv"
        }
    }
  }
```

**Comment by puremourning** [comment]
what's the output of `echo SUDO_COMMAND` in your shell?

If you're sure that you're the right user, then you can specify `--sudo` to override the validation.

**Comment by puremourning** [comment]
FWIW you also have errors in your config (the 'run' configuration is not in the 'configurations' block)

**Comment by RonanMacF** [comment]
output `$SUDO_COMMAND` = /tmp/tmp.uMeC9KwnTV.

My apologies --sudo worked fine, unsurprisingly. Out of curiosity was the SUDO_CMD above what should be expected?

**Comment by puremourning** [comment]
No. Why do you have SUDO_COMMAND set ? That’s only set by sudo.
