### ISSUE TITLE
[Feature Request]: Remove all breakpoints

### ISSUE THREAD

**Issue by nikki93** [puremourning/vimspector#188]
**Is your feature request related to a problem? Please describe.**
Once I'm done with a debugging session, I want to get back to normal coding and not have breakpoints set and forget about my debug session. When I 'Reset' at the end, the breakpoints are still remembered (which seems right to me), but it would be nice to also have a 'Remove all breakpoints' action that lets me truly clear the breakpoints and get back to square one.

**Describe the solution you'd like**
The 'Remove all breakpoints' action described above.

**Describe alternatives you've considered**
I browsed around the docs a bit but I don't think I could figure out how to do something like this with the current featureset. 🤔

**Comment by puremourning** [comment]
You can call vimspector#ClearBreakpoints()

**Comment by puremourning** [comment]
I’ll leave this open as 5at func is undocumented
