### ISSUE TITLE
[Feature Request]: Display string value in local/global variable list vscode-cpp

### ISSUE THREAD

**Issue by pianocomposer321** [puremourning/vimspector#194]
First of all, I'd like to thank you for this awesome plugin.  The main thing I missed after switching from VSCode to vim was debugging, and this plugin is (almost) perfect.

Now for the issue.

Compare the two below images:

![image](https://user-images.githubusercontent.com/54072354/86941429-89dc3d00-c109-11ea-8563-29f6ed1799ae.png)
![image](https://user-images.githubusercontent.com/54072354/86941465-96f92c00-c109-11ea-8908-c3b301f4eb61.png)

The first is vimspector debugging a simple "Hello, World!" program in C++. The second is VSCode debugging the same file. They are both stopped at the same breakpoint on line 8. The difference is in the variable list. In the VSCode screenshot, it's much neater, with the value of msg being displayed as a neat string: "Hello, World". With vimspector, it's a different story. The output looks, for lack of a better word, ugly. Not only do you have to expand several folds to see the actual string value of msg, but the value you see is more like an array of chars than a string. It makes sense that that is what a std::string is under the hood, but the debug adapter for vimspector with C++ is the VSCode extension for C++, so it makes sense for the output to be the same, right?

**Comment by pianocomposer321** [comment]
BTW, sorry about not following the issue template, it just didn't seem to fit for this issue. I will try to follow it better in any future issues.

**Comment by puremourning** [comment]
Vimspector just displays what the debug adapter tells it to 

Can you paste your launch.json from vscode?

**Comment by pianocomposer321** [comment]
launch.json:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "g++ - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/bin/${fileBasenameNoExtension}",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: g++ build active file",
            "miDebuggerPath": "/usr/bin/gdb"
        }
    ]
}
```

tasks.json, just in case:

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "shell",
			"label": "C/C++: g++ build active file",
			"command": "/usr/bin/g++",
			"args": [
				"-g",
				"${file}",
				"-o",
				"${workspaceFolder}/bin/${fileBasenameNoExtension}"
			],
			"options": {
				"cwd": "${workspaceFolder}"
			},
			"problemMatcher": [
				"$gcc"
			],
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```

**Comment by pianocomposer321** [comment]
I assume it's this part of the launch.json that makes it look good in VSCode:

```
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
```

**Comment by pianocomposer321** [comment]
The one think I don't get is that if I just debug with gdb and do `p msg` it outputs correctly. So shouldn't vimspector display the same thing?

**Comment by puremourning** [comment]
what happens if you add this in your vimspector.json ?

```
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
```

**Comment by puremourning** [comment]
To explain why I can't do anything about this in vimspector. This is all vimspector gets:

https://microsoft.github.io/debug-adapter-protocol/specification#Types_Variable

So if it's not in the `value` I can't just make it up.

**Comment by pianocomposer321** [comment]
It works! Thanks, @puremourning.

I though of trying that, but I didn't find anything in the docs for "setupCommands".

Will any options in a vscode launch.json work in .vimspector.json?

**Comment by puremourning** [comment]
> Will any options in a vscode launch.json work in .vimspector.json?

Pretty much, though frustratingly some vscode "plugins" completely rewrite what you put in your launch.json to determine the actual launch arguments.

The launch arguments are just the [DAP launch](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Launch) request. The values for `arguments` are adapter-specific. Vimspector configuration is just literally setting up an object to send on the request.

you're using vscode-cpptools, which means the documentation for the launch arguments is here: https://code.visualstudio.com/docs/cpp/launch-json-reference

I guess we could add a default that always enables pretty-printing, though I can see users who would balk at that. It might be worth a line or two in the README though, cos TBH I might use this myself!

**Comment by pianocomposer321** [comment]
>>Will any options in a vscode launch.json work in .vimspector.json?
>
>Pretty much, though frustratingly some vscode "plugins" completely rewrite what you put in your launch.json to determine the actual launch arguments.

Is this true of adapters that are not from vscode, such as debugpy, too?

**Comment by puremourning** [comment]
It's true of all of them, though some are much better at documenting their actual parameters and being good non-vscode citizens. debugpy is a shining example of something that works well and is well documented to be used outside of vscode. Less true of some of the others, but tbh debug adapters are generally pretty good and much more protocol-conformant than language servers.

btw the default behaviour of lldb seems to be a lot saner:

<img width="348" alt="Screenshot 2020-07-08 at 19 59 20" src="https://user-images.githubusercontent.com/10584846/86959454-c2096d00-c155-11ea-8fd7-6faed35723f1.png">

**Comment by pianocomposer321** [comment]
Great @puremourning. Would you like me to add something to the README.md for you? I would be happy to.
