### ISSUE TITLE
NameError: name `_vimspector_session' is not defined

### ISSUE THREAD

**Issue by dr-costas** [puremourning/vimspector#199]
**Describe the bug**
When pressing F3 or F9, I get the error `NameError: name '_vimspector_session' is not defined`. 

```python
Traceback (most recent call last):
    File "<string>", line 1, in <module>
NameError: name '_vimspector_session' is not defined
```

**To Reproduce**
Install Vimspector, install gadgets. 

Vimspector config file:
I use the .vimspector config from the example. 

**Expected behavior**
To work normally. 

**Actual behaviour**
Did not worked normally. 

Please include:
* Vimspector log (~/.vimspector.log): I do not have this file. 
* Output from any or all UI diagnostic tabs (Server, etc.)

**Environemnt**

* Version of Vimspector: (e.g. output of `git rev-parse HEAD` if cloned or the
  name of the tarball used to install otherwise)

Just did an upgrade with Plug

* Output of `vim --version` or `nvim --version`

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 24 2020 22:00:13)
```

* Output of `which vim` or `which nvim`:

```
paste here
```

* Output of `:py3 pass`:

```
No output
```

* Output of `:py3 import vim`:

```
No output
```

* For neovim: output of `:checkhealth`

```
paste here
```

* Operating system: <linux or macOS> and version

Linux

**Additional context**
I'm using Vim and Vimspector on a computational cluster, with no admin rights. I have followed the same process as I have followed in my local machine, and in my local machine I have a fully working Vimspector.

**Comment by puremourning** [comment]
Please complete the issue template. In particular:

* please paste the full output of `:messages:
* Please gist the full contents of `~/.vimspector.log`

**Comment by dr-costas** [comment]
Sure! 

Here is it: 

```bash
Error detected while processing function vimspector#internal#state#Reset:
line    9:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/users/<username>/.vim/plugged/vimspector/python3/vimspector/debug_session.py", line 21, in <module>
    import subprocess
  File "/<path-to>/miniconda3/envs/pytorch-1.3.0-1/lib/python3.7/subprocess.py", line 152, in <module>
    import _posixsubprocess
ImportError: /<path-to>/miniconda3/envs/pytorch-1.3.0-1/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Py_write_noraise
Error detected while processing function vimspector#Stop:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name '_vimspector_session' is not defined
Press ENTER or type command to continue
```

**Comment by puremourning** [comment]
> ImportError: /<path-to>/miniconda3/envs/pytorch-1.3.0-1/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Py_write_noraise

Looks like your python is broken. `import subprocess` doesn't work. 

> miniconda3

Oh Boy. I thought YCM was the only place that anaconda would kill me. I hate anaconda.


Please can you run `vim -Nu NONE` and then `:py3 import subprocess` ? What's the output?
Can you repeat that test without any sort of anaconda environment ?

**Comment by dr-costas** [comment]
The output of the `:py3 import subprocess` is: 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/<path-to>/miniconda3/envs/pytorch-1.3.0-1/lib/python3.7/subprocess.py", line 152, in <module>
    import _posixsubprocess
ImportError: /<path-to>/miniconda3/envs/pytorch-1.3.0-1/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Py_write_noraise
```

**Comment by puremourning** [comment]
So yeah, you need to fix your python.

**Comment by dr-costas** [comment]
I do not think that I can do the test without any condo env, because to use Python on the cluster, I have to load the python module (with `lmod`), which is already offered.

**Comment by dr-costas** [comment]
Thnx

**Comment by puremourning** [comment]
You may need to build Vim from source using the conda environment that you're running. Basically vim has an embedded python which loads libpython3.so, your conda environment contains binaries built _specifically_ for the conda python, which is _not compatible_ with the standard cpython. So the python vim is loading (or compiled in) is failing to load modules from the standard library (like subprocess). You'll need your standard library and your vim compiled-in (or dynamically loaded) python to match.

Check the output of `vim --version` (like the template requested) setting  `pythonthreedll` to the anaconda libpython3.so might fix it (i.e. if you have `+python3=dyn`) but if vim has statically linked python (`+python3`) then you'll either need to rebuild vim and link the anaconda python, use `--enable-python3interp=dynamic` or find a way to run vim without anaconda messing things up.

Sorry, this situation with anaconda is horrible for users, horrible for developers of python software, and generally just a very sad situation about which i can do nothing :/
