### ISSUE TITLE
[neovim] AttributeError: 'LegacyVim' object has no attribute 'bindeval'

### ISSUE THREAD

**Issue by lanza** [puremourning/vimspector#2]
Not sure if it's a goal of yours to support neovim but the `bindeval` at `python3/vimspector/debug_session.py:349` crashes vimspector on neovim since it doesn't support that API.

**Comment by puremourning** [comment]
Currently neovim support is not planned, as I don’t use it, but thanks for the heads up.!

**Comment by puremourning** [comment]
Neovim is not supported at the moment, sorry.
