### ISSUE TITLE
Inline Values View﻿

### ISSUE THREAD

**Issue by adelarsq** [puremourning/vimspector#204]
With [nvim_buf_set_virtual_text()](https://github.com/neovim/neovim/blob/7b529e7912517af078e005dd7b06b3d042be9cb7/runtime/doc/api.txt#L2055) is possible to emulate the [inline values for variables](https://www.jetbrains.com/help/pycharm/inline-debugging.html).

Would be nice something like that for UX reasons.

At the moment this feature is only possible on Neovim.

**Comment by puremourning** [comment]
Sorry neovim only feature aren’t going to be implemented.
