### ISSUE TITLE
[Feature Request]: Add Haskell Support.

### ISSUE THREAD

**Issue by rpuntaie** [puremourning/vimspector#207]
hdx4vim suggests a minimal modification. Could that be done here?
Searching for `hdx4vim` I found no reference to [the trace issue](https://github.com/phoityne/hdx4vim#modify-a-bit).

**Comment by puremourning** [comment]
I have no idea what you are requesting.

**Comment by rpuntaie** [comment]
I didn't deem it  necessary to duplicate the linked information, but here it is:

```
(python3/vimspector)
$ diff stack_trace.py.dist stack_trace.py
177c177
<     if source.get( 'sourceReference', 0 ) > 0:
---
>     if (source.get( 'sourceReference', 0 ) is not None) and (source.get( 'sourceReference', 0 ) > 0):
$
```

**Comment by puremourning** [comment]
Why are they suggesting that change ? 

The server vendor needs to fix their implementation, not work around it in vimspector.

The specification clearly does _not_ allow `null` here (either don't supply `sourceReference` or supply a `number`):

```
 /**
   * If sourceReference > 0 the contents of the source must be retrieved through the SourceRequest (even if a path is specified).
   * A sourceReference is only valid for a session, so it must not be used to persist a source.
   * The value should be less than or equal to 2147483647 (2^31 - 1).
   */
  sourceReference?: number;
```

**Comment by puremourning** [comment]
TBH i'm happy to accept a PR which adds the haskell-debug-adapter to install_gadget.py as experimental, updates the docs etc. and as a result changes this (though the change should really be `if ( source.get( 'sourceReference' ) or 0 ) > 0`

**Comment by rpuntaie** [comment]
OK, I've renamed this to a general "add Haskell support". Maybe someone, or even me, can create such a pull request later on.

**Comment by puremourning** [comment]
https://github.com/puremourning/vimspector/wiki/languages

**Comment by puremourning** [comment]
I'm unlikely to add further niche languages to the core, rather favouring the community-contributed guides/plugins above.
