### ISSUE TITLE
Watch Window mentioned can not make changes modifiable is off

### ISSUE THREAD

**Issue by cybaol** [puremourning/vimspector#230]
when I want to add a variable to Watch Window
mentioned can not make changes, modifiable is off
a few days before, it worked well but work off now

I don't want to use :VimspectorWatch every time
:set ma is not work
how can I do this?

**Comment by puremourning** [comment]
Please complete the isssue template per CONTRIBUTING.md

**Comment by cybaol** [comment]
> 
> 
> Please complete the isssue template per CONTRIBUTING.md

I have solved it.
yesterday I updated all softwares using "pacman -Syyu"
so my neovim version rollback from v0.5.0 (prerelease)  to v0.4.4（previous stable release is 0.4.3）
my neovim version is too low to work it !

**Comment by puremourning** [comment]
no, vimspector should work with nevoid 0.4; I would appreciate if you could complete the full issue template so that I can investigate why this isn't working for you.

**Comment by puremourning** [comment]
wait actually, never mind, neovim 0.4 doesn't have prompt buffers.

**Comment by cybaol** [comment]
> 
> 
> no, vimspector should work with nevoid 0.4; I would appreciate if you could complete the full issue template so that I can investigate why this isn't working for you.

OK，I will complete the issue for you if I have spare time.

**Comment by puremourning** [comment]
Actually, don't. As I said, it's expected. The reason the issue template exists is so that I can easily see this, rather than wasting both of our time. I could have seen you were using neovim and therefore said see the documentation where it says that prompt buffers aren't supported in neovim. Anyway that's that.
