### ISSUE TITLE
[Feature Request]: cutomizable sign priority

### ISSUE THREAD

**Issue by antoinemadec** [puremourning/vimspector#231]
**Is your feature request related to a problem? Please describe.**
The issue is that Coc signs, Git signs and Vimspector signs are competing.
It happens that my Git signs priority is higher than Vimspector BP signs.

**Describe the solution you'd like**
I'd like the signs priorities to be configurable like so:
```vim
let g:vimspectorBP_sign_priority = 10
let g:vimspectorBPDisabled_sign_priority = 0 
let g:vimspectorPC_sign_priority = 12
```

**Describe alternatives you've considered**
Modifying all the other sign priorities could work if the other plugins offer that option.
However, this is not really scallable.

**Comment by puremourning** [comment]
> It happens that my Git signs priority is higher than Vimspector BP signs.

What is the priority of the other signs? Do the other plugins proivide ways to control their sign priorities ?

I would rather this just worked than add options. This isn't the first time this has been asked, I just want to make sure that any solution is canonical and aligned with vim best practice. For example `termdebug` doesn't set a priority at all.

**Comment by antoinemadec** [comment]
@puremourning ,

- [coc-git](https://github.com/neoclide/coc-git) signs default: priority=10, id=99
- [coc](https://github.com/neoclide/coc.nvim) LSP diagnostics signs default: priority=10, id=1000

They both are using a the default priority of 10 and rely on the ID that is used to show one sign or the other.
This ID offset can be changed, however the priority cannot be changed.

This is only for Coc, but other users could be using other plugins creating signs:

1. lowering those plugins sign priority might not be an option
2. if it is, raising 1 plugin (vimspector) priority is more economical than lowering N-1 plugins priorities 

What do you think?

Also, thanks for the amazing plugin :smiley:

**Comment by puremourning** [comment]
Vimspector sets the priority to 20. So it should override those right?

**Comment by antoinemadec** [comment]
@puremourning , yes it should.

Weird thing is that when doing `:sign place` it lists Coc and Coc-git signs, but not the vimspector signs (even though I can see them):
```
:sign place
--- Signs ---
Signs for /home/antoine/test/python/misc/fibo/fibo.py:
    line=14  id=1000  name=CocWarning  priority=10
    line=18  id=99  name=CocGitChangeRemoved  priority=10   
```
Do you have any idea why?

It might be a Vim bug (same behavior in Neovim).
For info, my Vim/Gvim was compiled from source today.

**Comment by puremourning** [comment]
If you can list steps to repro I can try but otherwise I would be guessing. I’m not even clear at this point what you mean by competing. You could also try fiddling with the calls to sign place in the vimspector code.

**Comment by antoinemadec** [comment]
By "competing", I mean that those signs:
- line=14  id=1000  name=CocWarning  priority=10
- line=18  id=99  name=CocGitChangeRemoved  priority=10

are hiding vimspector break point signs when on the same line.

I will try to come up with a minimal vimrc.
In the meantime, could you please comment on the fact that `:sign place` does not list the vimspector signs?

**Comment by puremourning** [comment]
> In the meantime, could you please comment on the fact that :sign place does not list the vimspector signs?

Vimspector puts its signs in a group. I think you’re only listing global group. Try with group=*

**Comment by antoinemadec** [comment]
@puremourning , I found the issue:
-     line=5  id=7  group=VimspectorCode  name=vimspectorBP  priority=9 

Since Coc signs are priority=10, it hides the vimspectorBP.
Would it be possible to add configurable priorities to vimspector signs?

**Comment by puremourning** [comment]
Maybe. It might be better to just change that default. I deliberately didn’t want BPs to get in the way when NOT debugging but that one is WHILE debugging so it should be 11 not 9

**Comment by puremourning** [comment]
I’m reluctant to add an option that exposes the actual priority because it’s a bit too nuts and bolts. Most users won’t know what to set it to. I’d rather the defaults worked for most users.

**Comment by antoinemadec** [comment]
@puremourning , got it.
Having good defaults make definitely a lot of sense.

I still however thinks that on top of good defaults, an options to set them to different values might make sense.
See my previous comment: https://github.com/puremourning/vimspector/issues/231#issuecomment-674553779

Anyway, the "better defaults" solution will definitely fix it for me, so thanks a lot :smiley:

**Comment by roachsinai** [comment]
@puremourning wish there an option to set priority, too.

As ALE also used and has a high default priority, it will override the breakpoint.

```
:sign place group=* 
--- Signs ---
cartoon_effect.py 的 Signs:
    line=2  id=1000001  group=ale  name=ALEWarningSign  priority=30
    line=8  id=1000002  group=ale  name=ALEStyleErrorSign  priority=30
    line=9  id=1000003  group=ale  name=ALEStyleErrorSign  priority=30
    line=9  id=2  group=VimspectorBP  name=vimspectorBP  priority=10
    line=18  id=1000004  group=ale  name=ALEStyleErrorSign  priority=30
```

Though I could download priority of ale by `let g:ale_sign_priority=15`.

**Comment by roachsinai** [comment]
While maybe need set lower priority for ale.
