### ISSUE TITLE
"Launching debugee..." freeze

### ISSUE THREAD

**Issue by kuntiik** [puremourning/vimspector#241]
Hi,
I am having this problem: When I call vimspector#Launch() I can see vimspector layout, but the debugger won't start and I can see pop up window saying "Launching debugee". ( picture attached at the end ) 

I tested vimspector on minimal .cpp file ( main function printing "Hello World" ) and the debuger worked just fine, but when I use on my rahter bigger project I cant get it working. 

This is my .vimspector.json file:

```
{
    "configurations": {
        "Launch": {
            "adapter": "vscode-cpptools",
            "configuration" : {
                "request": "launch",
                "program": "debug/convert_cloud",
                "cwd": "/home/kuntik/Desktop/playground",
                "externalConsole": true,
                "MIMode": "gdb"
            }
        }
    }
}
```
Thanks for your help. 

![Selection_019](https://user-images.githubusercontent.com/43137698/91743151-a9e32680-ebb7-11ea-8fcb-d3f65cd28536.png)

**Comment by puremourning** [comment]
Please can you complete the issue template (see CONTRIBUTING.md).

**Comment by puremourning** [comment]
For the record, the answer is almost certainly in the vimspector log (`VimspectorToggleLog`) but without it I would be guessing.
