### ISSUE TITLE
[Feature Request]: Switch to vscode-js-debug

### ISSUE THREAD

**Issue by puremourning** [puremourning/vimspector#249]
Looks like vsode-node-debug and vscode-chrome-debug are being deprecated.

https://github.com/microsoft/vscode-js-debug

seems to be the replacement. it has a ton of stuff in it, but it all looks quite out-of-band and may work worse for us in the end.

discovered while trying to report a bug in vscode-chrome-debug.

**Comment by csy19960309** [comment]
In the use of vscode-node-debug2, the breakpoint never works even if is says ' Debugger attached '. 
However, the breakpoint works well when I switch to Visual Studio Code with nothing else changed. I do not know if it is because Visual Studio Code uses vscode-js-debug instead if vscode-node-debug2.

**Comment by mfussenegger** [comment]
The [issue here](https://github.com/microsoft/vscode-js-debug/issues/902) may also be interesting to you.

**Comment by puremourning** [comment]
Thanks. I took another look at this other debug adapter and I could not work out how to drive it. Vscode-node-devug2 works well enough for now. I see they are using custom undocumented protocol extensions so I’m NOPE for now on that 👍 

same for you in nvim-dap I guess?

**Comment by Trim** [comment]
FYI, vscode-js-debug has released a pure DAP server (so, using the new 'startDebugging' feature): https://github.com/microsoft/vscode-js-debug/issues/1388#issuecomment-1482055640

If I understood correctly, the pure DAP server is inside this asset from the v1.77.0:

https://github.com/microsoft/vscode-js-debug/releases/download/v1.77.0/js-debug-dap-v1.77.0.tar.gz

I've seen the vimpsector [multpile-sessios](https://github.com/puremourning/vimspector/tree/multiple-sessios) branch with a python dap gadget example, maybe we could add vscode-js-debug too with this new release?

**Comment by puremourning** [comment]
the implementation in that branch is really experimental. The user experience is really terrible (having a tab-per-instance is very messy). I haven't actually worked out a good way to handle multiple sessions yet , which is sad. I'll push it up to the top of the "list".

**Comment by puremourning** [comment]
@Trim  I have updated the `multiple-sessios` branch to support the new `startDebugging` request and switch to vscode-js-debug. You can `:VimspectorInstall vscode-js-debug` and it will work with the sample project in `support/test/node/simple`.

However, as I said the UX is not really very good with this multiple tabs things. I need to do a lot of refactoring to make the UI/UX good. But feel free to try it.

**Comment by ericdvb** [comment]
As of now, does debugging an external process (using `"request": "attach"`) work? I'm trying to debug a next.js project but I can't get vscode-js-debug to attach to the node process. With vscode-node-debug2, it'll attach, but the process never stops on toggled breakpoints (although it will stop on exceptions, I supposed I could just use `break` or something).

**Comment by puremourning** [comment]
Yes it works so far as I know. There's even an example in the support/test directory.
