### ISSUE TITLE
Ruby/Elixir support

### ISSUE THREAD

**Issue by avucic** [puremourning/vimspector#250]
Is there any example how I can setup Vimspector for Ruby/Elixir? Both are supported in VScode. I read docs but I'm not sure how to do that. I would appreciate some guidance. Btw. thanks forthis great plugin !!

**Comment by puremourning** [comment]
Which plugin did you use on vscode?

**Comment by avucic** [comment]
I have these installed
https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby
https://marketplace.visualstudio.com/items?itemName=JakeBecker.elixir-ls

**Comment by puremourning** [comment]
Can you work it out with this as a guide? https://github.com/rubyide/vscode-ruby/blob/master/docs/debugger.md

**Comment by avucic** [comment]
I don't have enough experience with this topic. I see instruction/configuration how to "nstall/configure debugger and how to lunch/from VScode. I'm not sure how to configure/run Vimspecotor accordance with this instructions.

**Comment by avucic** [comment]
I managed to work with this setup for Ruby:
https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby
```
{
    "adapters": {
    "vscode-ruby-debug": {
      "command": [
        "node",
        "<root>/.vscode/extensions/rebornix.ruby-0.27.0/dist/debugger/main.js"
      ],
      "name": "vscode-ruby-debug"
    }
	},
  "configurations": {
    "vscode-ruby-debug": {
      "default": true,
      "adapter": "vscode-ruby-debug",
      "configuration": {
        "request": "launch",
        "cwd": "${workspaceRoot}",
        "program": "./bin/rspec",
        "args": [
          "${file}"
        ],
        "showDebugOutput": true,
        "trace": true
      }
    }
  }
}
```

**Comment by puremourning** [comment]
Nice. Thanks! I'm thinking of adding a Wiki section for community-contributed config like this

**Comment by puremourning** [comment]
Thanks, added this: https://github.com/puremourning/vimspector/wiki/languages
