### ISSUE TITLE
java jdt.ls automatic classpaths resolve 

### ISSUE THREAD

**Issue by dassio** [puremourning/vimspector#253]
### Describe the bug

for java debugging, we have to provide the vscode `classpaths` parameter, but since jdt.ls understand gradle/maven/eclipse project structures, this should be able omitted and resolved automatically 

### Minimal reproduciton

> Use the following Vimspector config file:

```
{
  "configurations": {
    "Java Attach": {
      "adapter": "vscode-java",
      "configuration": {
        "request": "launch",
        "mainClass": "hello.HelloWorld",
        "sourcePaths": [ "${workspaceRoot}/src/main/java" ],
        "classPaths": [ "${workspaceRoot}/build/classes/java/main/" ],
        "hostName": "localhost",
        "port": "${DAPPort}"
      },
      "breakpoints": {
        "exception": {
          "caught": "N",
          "uncaught": "N"
        }
      }
    }
  }
}

```

### Expected behaviour

`classpaths` resolved automatically 

### Actual behaviour

have to provide manually

**Comment by puremourning** [comment]
I have never had to specify that key. 

Also this is nothing to do with vimspector. It’s the java debug adapter.

**Comment by dassio** [comment]
> I have never had to specify that key.
> 
> Also this is nothing to do with vimspector. It’s the java debug adapter.

in the[ example,](https://github.com/puremourning/vimspector/blob/master/support/test/java/test_project/.vimspector.json)clearly you can see  the key : `classPaths`
>{
  "configurations": {
    "Java Launch": {
      "adapter": "vscode-java",
      "configuration": {
        "request": "launch",
        "mainClass": "com.vimspector.test.TestApplication",
        "sourcePaths": [ "${workspaceRoot}/src/main/java" ],
        "classPaths": [ "${workspaceRoot}/target/classes" ],
        "args": "hello world!",
        "stopOnEntry": true,
        "console": "integratedTerminal",
        "stepFilters": {
          "skipClasses": [ "$$JDK" ]
        }
      }
    },

**Comment by puremourning** [comment]
In my real projects, I don't specify it. Have you tried not specifying it? Have you read through the debug adapter's documentation ?

**Comment by dassio** [comment]
yes, I tried it, when not specifying the `classpaths` , i got the error 
```
Failed to launch debuggee VM. Missing mainClass or modulePaths/classPaths options in launch configuration.
```

```
2020-09-09 14:29:28,461 - ERROR - Server reported: Sep 9, 2020, 2:29:28 PM [error response][launch]: Failed to launch debuggee VM. Missing mainClass or modulePaths/classPaths options in launch config    uration.
801 Failed to launch debuggee VM. Missing mainClass or modulePaths/classPaths options in launch configuration.
802 com.microsoft.java.debug.core.DebugException: Failed to launch debuggee VM. Missing mainClass or modulePaths/classPaths options in launch configuration.
803 >-at com.microsoft.java.debug.core.adapter.AdapterUtils.createCompletionException(AdapterUtils.java:259)
804 >-at com.microsoft.java.debug.core.adapter.handler.LaunchRequestHandler.handleLaunchCommand(LaunchRequestHandler.java:89)
805 >-at com.microsoft.java.debug.core.adapter.handler.LaunchRequestHandler.handle(LaunchRequestHandler.java:81)
806 >-at com.microsoft.java.debug.core.adapter.DebugAdapter.lambda$dispatchRequest$0(DebugAdapter.java:87)
807 >-at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
808 >-at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
809 >-at com.microsoft.java.debug.core.adapter.DebugAdapter.dispatchRequest(DebugAdapter.java:86)
810 >-at com.microsoft.java.debug.core.adapter.ProtocolServer.dispatchRequest(ProtocolServer.java:118)
811 >-at com.microsoft.java.debug.core.protocol.AbstractProtocolServer.lambda$new$0(AbstractProtocolServer.java:78)
812 >-at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:60)
813 >-at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
814 >-at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
815 >-at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
816 >-at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
817 >-at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
818 >-at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
819 >-at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
820 >-at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
821 >-at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by puremourning** [comment]
> Missing mainClass or modulePaths/classPaths options in launch configuration

you have to tell it what to launch.

**Comment by puremourning** [comment]
Anyway, like I said, there is nothing vimspector can do here. It's all the debug adapter.

**Comment by dassio** [comment]
> > Missing mainClass or modulePaths/classPaths options in launch configuration
> 
> you have to tell it what to launch.

i did

```
{
  2   "configurations": {
  3     "Java Launch": {
  4       "adapter": "vscode-java",
  5       "configuration": {
  6         "request": "launch",
  7         "mainClass": "hello.HelloWorld",
  8         "sourcePaths": [ "${workspaceRoot}/src/main/java" ],
  9         "hostName": "localhost",
 10         "port": "${DAPPort}"
 11       },
 12       "breakpoints": {
 13         "exception": {
 14           "caught": "N",
 15           "uncaught": "N"
 16         } 
 17       }
 18     }
 19   }
 20 }
```

**Comment by dassio** [comment]
> Anyway, like I said, there is nothing vimspector can do here. It's all the debug adapter.

Like the `DAPPort`, vimspector can get the class path by `::YcmCompleter ExecuteCommand vscode.java.resolveClasspath hello.HelloWorld test`

now we are setting `DAPPort` in `.vimrc`, i don't see why we can't move it to the `language_server_completer.py` or somewhere else, when it is an java file, we can pre-setup all this parameters , so we can have the same user experience like vscode 

![Screenshot from 2020-09-09 14-35-31](https://user-images.githubusercontent.com/733502/92605532-22ca3880-f2b2-11ea-9923-a937786c2d8e.png)

**Comment by puremourning** [comment]
> Like the DAPPort, vimspector can get the class path by ::YcmCompleter ExecuteCommand vscode.java.resolveClasspath hello.HelloWorld test

I didn't know about that.

But still, there's nothing for vimspector to do here. 

Your custom code which integrates with YCM can run this. You just call `youcompleteme#GetCommandResponse` a second time to resolve it, then pass it in to your launch config as a launch argument. 

If you want to make a PR which updates the documentation/example to do this, that would be great!

**Comment by puremourning** [comment]
something like: https://github.com/puremourning/vimspector#usage-with-youcompleteme

```
function! s:StartDebugging()
  if s:jdt_ls_debugger_port <= 0
    " Get the DAP port
    let s:jdt_ls_debugger_port = youcompleteme#GetCommandResponse(
      \ 'ExecuteCommand',
      \ 'vscode.java.startDebugSession' )

    if s:jdt_ls_debugger_port == ''
       echom "Unable to get DAP port - is JDT.LS initialized?"
       let s:jdt_ls_debugger_port = 0
       return
     endif
  endif

  " Start debugging with the DAP port
       
    let classpaths = youcompleteme#GetCommandResponse( 'ExecuteCommand', 'vscode.java.resolveClasspath', '<something???!!!>' )

  call vimspector#LaunchWithSettings( { 'DAPPort': s:jdt_ls_debugger_port, 'ClassPaths': classpaths } )
end function
```

**Comment by dassio** [comment]
> something like: https://github.com/puremourning/vimspector#usage-with-youcompleteme
> 
> ```viml
> function! s:StartDebugging()
>   if s:jdt_ls_debugger_port <= 0
>     " Get the DAP port
>     let s:jdt_ls_debugger_port = youcompleteme#GetCommandResponse(
>       \ 'ExecuteCommand',
>       \ 'vscode.java.startDebugSession' )
> 
>     if s:jdt_ls_debugger_port == ''
>        echom "Unable to get DAP port - is JDT.LS initialized?"
>        let s:jdt_ls_debugger_port = 0
>        return
>      endif
>   endif
> 
>   " Start debugging with the DAP port
>        
>   let classpaths = youcompleteme#GetCommandResponse(
>       \  'ExecuteCommand', 
>       \ 'vscode.java.resolveClasspath', 
>       \ '<something???!!!>' )
> 
>   call vimspector#LaunchWithSettings( { 'DAPPort': s:jdt_ls_debugger_port, 'ClassPaths': classpaths } )
> endfunction
> ```

yes, this should work, I will give it a try


> now we are setting `DAPPort` in `.vimrc`, i don't see why we can't move it to the `language_server_completer.py` or somewhere else, when it is an java file, we can pre-setup all these parameters , so we can have the same user experience like vscode

now i understand whey change the python file will not work, i am confusing vimspector with ycm, you can't call an command from vimspector

**Comment by puremourning** [comment]
>  i am confusing vimspector with ycm, you can't call a ycm command from vimspector

👍
