### ISSUE TITLE
Installing vscode-node-debug on Windows

### ISSUE THREAD

**Issue by aaronhallaert** [puremourning/vimspector#259]
> DO NOT DELETE THIS TEMPLATE. IF YOU DELETE THIS TEMPLATE AND DO NOT COMPLETE IT, YOUR ISSUE WILL BE CLOSED.

### Describe the bug

When trying to install node debugger with: `install_gadget.py --force-enable-node`, I got a file not found error

I resolved the bug for this command by temporarily changing the python3/vimspector/installer.py at line 67 from
` subprocess.check_call( *args, **kwargs )` to `subprocess.check_call( *args, shell=True)`

### Minimal reproduciton

* Does your issue reproduce using `vim -Nu /path/to/vimspector/support/minimal_vimrc` ? \[No]
* If you are using Neovim, does your issue reproduce using Vim? \[Yes]

> List of steps to reproduce:

> 1. Run `install_gadget.py --force-enable-node` (on Windows, python 3.8)

> Use the following Vimspector config file:

Non vim related bug

### Expected behaviour

output of command
```
...
The following adapters were installed successfully:
 - vscode-node-debug2
```

### Actual behaviour
```
Traceback (most recent call last):
  File "python3\vimspector\installer.py", line 463, in InstallGagdet
    gadget[ 'do' ]( name, root, spec )
  File "python3\vimspector\gadgets.py", line 389, in <lambda>
    'do': lambda name, root, gadget: installer.InstallNodeDebug( name,
  File "python3\vimspector\installer.py", line 387, in InstallNodeDebug
    CheckCall( [ 'npm', 'install' ] )
  File "python3\vimspector\installer.py", line 68, in CheckCall
    subprocess.check_call( *args, **kwargs )
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\aaron\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
Installing vscode-node-debug2@v1.42.5...
 - FAILED installing vscode-node-debug2: [WinError 2] The system cannot find the file specified
Failed to install adapters:
 * vscode-node-debug2
```

### Environemnt

***NOTE***: NeoVim is supported only on a best-effort basis. Please check the README
for limitations of neovim. Don't be offended if I ask you to reproduce issues in
Vim.

***NOTE***: Windows support is experimental and best-efrort only. If you find an
issue related to Windows or windows-isms, consider sending a PR or
discussing on Gitter rather than raising an issue.

* Version of Vimspector: (e.g. output of `git rev-parse HEAD` if cloned or the
  name of the tarball used to install otherwise)
Installed with VimPlug

* Output of `vim --version` or `nvim --version`

```
NVIM v0.5.0-693-g20f7b9428
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

* Output of `:py3 print( __import__( 'sys' ).version )`:

```
3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)]
```

* Operating system: Windows
  
### Declaration

> Please complete the following declaration. If this declaration is not completed, your issue may be closed without comment.

* I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md) \[Yes]

**Comment by puremourning** [comment]
> got a file not found error

I don't see a file not found error in your report. Can you post the whole log ?

**Comment by aaronhallaert** [comment]
> > got a file not found error
> 
> I don't see a file not found error in your report. Can you post the whole log ?

@puremourning my bad, posted the wrong stacktrace, I edited the issue

**Comment by puremourning** [comment]
I need some help reproducing/understanding this. Windows is only supported best-efforts and quirks like this are the reason why.

If git.exe is in your path, I don't completely understand why subprocess.check_call( [ 'git' ] ) doesn't work.

**Comment by aaronhallaert** [comment]
> I need some help reproducing/understanding this. Windows is only supported best-efforts and quirks like this are the reason why.
> 
> If git.exe is in your path, I don't completely understand why subprocess.check_call( [ 'git' ] ) doesn't work.

@puremourning I understand Windows is experimental. And it seems like the stacktrace was again different than the first time I encountered the bug... I again updated the issue. I tried to figure out what file or folder was missing because the stacktrace doesn't mention it (even with verbose). I read online that spawning a shell with `shell=True` helps most of the time. I'm not an expert in python, but it worked in this case...

**Comment by puremourning** [comment]
OK thanks, I just tried this and I can repro. I'll have a think about it. I'm sure that this shell=True thing has come up before on YCM so I'll check the history.

**Comment by puremourning** [comment]
this is what baffles me:

> On Windows with shell=True, the COMSPEC environment variable specifies the default shell. The only time you need to specify shell=True on Windows is when the command you wish to execute is built into the shell (e.g. dir or copy). You do not need shell=True to run a batch file or console-based executable.

That's from the python docs.

**Comment by puremourning** [comment]
it's `npm install` which is failing....

**Comment by puremourning** [comment]
oh boom, it's because `npm` is `npm.cmd` in the path, which python doesn't work. YCM has code to handle this.

I guess I'll add it here.

**Comment by aaronhallaert** [comment]
> oh boom, it's because `npm` is `npm.cmd` in the path, which python doesn't work. YCM has code to handle this.
> 
> I guess I'll add it here.

Great!

**Comment by puremourning** [comment]
@aaronhallaert  I pushed a PR, can you see if it works for you ?

**Comment by aaronhallaert** [comment]
> @aaronhallaert I pushed a PR, can you see if it works for you ?

@puremourning done, it works as expected

**Comment by puremourning** [comment]
@aaronhallaert  thanks for checking and thanks for the report!
