### ISSUE TITLE
Broken UI in neovim 0.5

### ISSUE THREAD

**Issue by Maswor** [puremourning/vimspector#269]
<img width="1440" alt="Screen Shot 2020-09-30 at 12 23 13 AM" src="https://user-images.githubusercontent.com/15852839/94593830-91982180-02b3-11eb-8081-cce7be010ef1.png">
> DO NOT DELETE THIS TEMPLATE. IF YOU DELETE THIS TEMPLATE AND DO NOT COMPLETE IT, YOUR ISSUE WILL BE CLOSED.

### Describe the bug

> Ui is broken in the border area between code view and command prompt in Neovim 0.5.

### Minimal reproduciton

> Please answer the following questions

* Does your issue reproduce using `vim -Nu /path/to/vimspector/support/minimal_vimrc` ? \[Yes]
* If you are using Neovim, does your issue reproduce using Vim? \[No]

> List of steps to reproduce:

> 1. Run `vim -Nu /path/to/vimspector/support/minimal_vimrc`
> 2. Open a python/cpp project
> 3. Press F5

> Use the following Vimspector config file:

```
{
    "$schema": "https://puremourning.github.io/vimspector/schema/vimspector.schema.json#",
    "configurations": {
        "main: Launch": {
            "adapter": "debugpy",
            "configuration": {
                "name": "main: Launch",
                "type": "python",
                "request": "launch",
                "module": "flask",
                "python": "python3",
                "env": {
                    "FLASK_APP": "App.main",
                    "FLASK_ENV": "development",
                    "FLASK_DEBUG": "0"
                },
                "args": [
                    "run",
                    "--no-debugger",
                    "--no-reload"
                ],
                "stopOnEntry": true,
                "console": "externalTerminal",
                "jinja": true
            }
        }
    }
}

```

### Expected behaviour

> The border is a continous line

### Actual behaviour

> What actually happened, including output, log files etc.

> Please include:
> * Vimspector log (~/.vimspector.log)
> * Output from any or all UI diagnostic tabs (Server, etc.)

### Environemnt

***NOTE***: NeoVim is supported only on a best-effort basis. Please check the README
for limitations of neovim. Don't be offended if I ask you to reproduce issues in
Vim.

***NOTE***: Windows support is experimental and best-efrort only. If you find an
issue related to Windows or windows-isms, consider sending a PR or
discussing on Gitter rather than raising an issue.

* Version of Vimspector: (e.g. output of `git rev-parse HEAD` if cloned or the
  name of the tarball used to install otherwise)

* Output of `vim --version` or `nvim --version`

```
NVIM v0.5.0-090551a80
Build type: Release
LuaJIT 2.0.5

```

* Output of `which vim` or `which nvim`:

```
/usr/local/bin/nvim
```

* Output of `:py3 print( __import__( 'sys' ).version )`:

```
3.8.5 [clang 11.0.0]
```

* Output of `:py3 import vim`:

```
paste here
```

* Output of `:py3 import vimspector`:

```
paste here
```

* For neovim: output of `:checkhealth`

```
paste here
```

* Operating system: <linux or macOS> and version
  
### Declaration

> Please complete the following declaration. If this declaration is not completed, your issue may be closed without comment.

* I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md) \[Yes/No]

**Comment by puremourning** [comment]
Duplicate : https://github.com/puremourning/vimspector/issues/255

This is a Neovim bug. Try upgrading to vim :)
