### ISSUE TITLE
Windows : equivalence launch.json  from vs code don't work

### ISSUE THREAD

**Issue by grimgort** [puremourning/vimspector#271]
Hello,

I can't get vimspector to work on windows 10. I'm trying to make the equivalent of this launch.json from vs code :
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Lancer",
            "type": "cppdbg",
            "request": "launch",
            "program": "D:/ftarroux/Documents/FRED/BaseGit/JsonMatisse/matisseReaderCjson/build_mingw/executable_ctest/execute_only_scenario_read.exe ",
        "args": [
          "D:/ftarroux/Documents/FRED/BaseGit/JsonMatisse/matisseReaderCjson/build_mingw/scenario_test/scenario_3_6/testTous/testTous.json",
          "D:/ftarroux/Documents/FRED/BaseGit/JsonMatisse/matisseReaderCjson/build_mingw/scenario_test/scenario_3_6/testTous/matisse.cfg"
        ],
                       "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath":  "D:/ftarroux/scoop/apps/perl/current/c/bin/gdb.exe",
            "setupCommands": [
                {
                    "description": "Activer l'impression en mode Pretty pour gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}

with this  .vimspector : 
{
  "configurations": {
    "Vim - run a test": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "type": "cppdbg",
        "request": "launch",
        "program": "D:/ftarroux/Documents/FRED/BaseGit/JsonMatisse/matisseReaderCjson/build_mingw/executable_ctest/execute_only_scenario_read.exe",
        "args": [
          "D:/ftarroux/Documents/FRED/BaseGit/JsonMatisse/matisseReaderCjson/build_mingw/scenario_test/scenario_3_6/testTous/testTous.json",
          "D:/ftarroux/Documents/FRED/BaseGit/JsonMatisse/matisseReaderCjson/build_mingw/scenario_test/scenario_3_6/testTous/matisse.cfg"
        ],
        "cwd": "${workspaceRoot}",
        "environment": [],
        "externalConsole": true,
        "stopAtEntry": true,
        "MIMode": "gdb",
        "logging": {
          "engineLogging": false
        },
        "miDebuggerPath": "D:/ftarroux/scoop/apps/perl/current/c/bin/gdb.exe"
      }
    }
  }
}

but the debugger doesn't start.

**Comment by puremourning** [comment]
Please complete the issue template. See CONTRIBUTING.md.
