### ISSUE TITLE
[Feature Request]: Support F#

### ISSUE THREAD

**Issue by lucasteles** [puremourning/vimspector#274]
That should not be too hard, because F# runs on .NET core and mono, so the actual debuggers should work out of the box.

**Comment by puremourning** [comment]
https://github.com/puremourning/vimspector/wiki/languages

**Comment by lucasteles** [comment]
I tested the actual configurations of the netcoredbg on a F# project and just works, can I create a PR adding F# on side of C# in the readme?

**Comment by puremourning** [comment]
> can I create a PR adding F# on side of C# 

Sure! Please do ! Thanks!
