### ISSUE TITLE
Defining a prelaunch task 

### ISSUE THREAD

**Issue by TryerGit** [puremourning/vimspector#276]
Hi puremourning,

Sorry if this appears too much too fast. I just wanted to bring closure to the SO question I had posed available at:

https://stackoverflow.com/questions/64277301/vimspector-how-to-define-prelaunch-task

You already answered my first question there. This pertains to my second question, which I reproduce below.

----

2. `.vimspector.json` file seems similar in content to `.vscode/launch.json` file. My `.vscode/launch.json` file has an option of a `preLaunchTask` which builds the project.
    
`"preLaunchTask": "lindbgbuild",`

This build task does nothing other than the following:

    "command": "make",
    "args": ["CONF=Debug", "-C", "./.vscode"],

Also, within VSCode, building automatically saves any source code files that have changed but not yet saved. The net effect of all of this is that within VSCode, it is straightforward to change a file, setup a breakpoint and run it (if there are errors, in this process, VSCode automatically indicates where the error is and the debug launch is aborted) to hit that breakpoint with a single button press (`F5`). Note the `-C ./.vscode` option. This allows me to start VSCode from `myproject\` folder and accesses the makefiles within `myproject\.vscode\` folder. All of this is highly convenient.

Is a similar feature available in `vimspector` that automatically saves the file, if changed, builds it using make from within `.vim\` folder `Makefile`s, and then launches the debugger until the breakpoint is hit? As of now, because of my inability to use this feature (assuming it exists), I am having to separately navitage to `\myproject\.vim\` and issue `make CONF=Debug`, then go back into Vim and then hit `F5`.

**Comment by puremourning** [comment]
You can do all of what you need with vim and there is little point in re-implementing `makeprg`, `:make` and such within vimspector, which is a debug UI not a build system. 

It's really as simple as `command! BuildAndDebug :%update | :make | :call vimspector#Launch()`.  see vim help for details.

some other user integrated with some async make package or other (search the issues or Gitter logs for that). Also in Gitter logs I've explained that you can do this using Vimspector's `variables` by creating a `shell` variable which runs `make` if you really want to.

I won't be building a whole build management system in vimspector, it's just not in scope.

**Comment by TryerGit** [comment]
Thanks. Let me try this out.

**Comment by TryerGit** [comment]
I tried this and it works as expected when there is no error from make. When there is some error in make, it still opens up vimspector though. Is there a way that can be stopped ? i.e., vimspector should be launched only if make returns no errors ? Attached is a screenshot which shows vimspector being launched even though there is a syntax error that ycm correctly identifies and make also subsequently fails on.

![vimspectorquestion](https://user-images.githubusercontent.com/70434658/95653256-0cafd200-0b15-11eb-8dc7-3bf1bd9a892c.jpg)

**Comment by puremourning** [comment]
you could check if anything was populated in the quickfixlist (`:help getqflist()`)
