### ISSUE TITLE
[Feature Request]: formalizing a release process

### ISSUE THREAD

**Issue by StephenWithPH** [puremourning/vimspector#283]
First, thank you for your hard work on this project. It's great.

**Is your feature request related to a problem? Please describe.**
Right now, watching this project on GitHub for only releases does not work [for `$GitHub_reasons`](https://github.community/t/not-getting-release-notification-despite-watching-releases/1792/4). Meanwhile, it appears that every commit to `master` creates a pre-release via GitHub actions. The only way to determine what's changed and whether or not I want to update is to look at a diff between my current version of the plugin and the most recent pre-release version.

**Describe the solution you'd like**
1. A quick way for users to see what has changed with each release... perhaps using [a changelog](https://keepachangelog.com/en/1.0.0/).
1. Use of full-fledged (rather than pre-releases) in GitHub... possibly by integrating GitHub's [create-release action](https://github.com/actions/create-release) into the build pipeline.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by puremourning** [comment]
Maybe, if/when it is ever not pre-release.

I don't have time to manage release process. Life is too short and I already have way too little time.

For now. Every commit to master _is_ a new release. That's my release process.
