### ISSUE TITLE
[Feature Request]: Easier Python Interactive Debugging

### ISSUE THREAD

**Issue by Thieso** [puremourning/vimspector#287]
Hey, 

First of all, I really like vimspector and appreciate the work you are doing. I use it at the moment mostly for python debugging. I am an engineer and switched from Matlab to Python. I enjoy the switch and learning something new. However, when debugging Python with vimspector I miss the functionality of running some code while debugging. Let me explain. So lets say I hit a breakpoint during debugging and want to evaluate some code to see some output. For example variable a plus variable b, so I would like to type a + b somewhere. Right now this is only possible using VimspectorEval and sending "print(a+b)". I feel like this is overly complicated.
It would be easier if I could just type a+b (without the print) or if I, in case the code already has that statement somewhere, could select a range and rum VimspectorEval on it to evaluate the code. 

I would also be willing to implement this feature myself, though I am not sure how complicated this is or if this is possible at all with the current workings of the project. 

Maybe you could give me some information what you think, and if this is a feasible feature I could implement (I am not a programmer but an engineer so I am by no means an expert, but I am willing to learn.)

Any feedback is appreciated. 

Keep up the good work. 

Greetings

**Comment by puremourning** [comment]
>  For example variable a plus variable b, so I would like to type a + b somewhere

You can do this:

1. in the watch window
2. in the console

They are prompt buffers.

If you're using Neovim, then you'll have to upgrade to Vim for that to work.

**Comment by puremourning** [comment]
Also for the record, I would have expected `:VimspectorEval a + b` to just work too, does it not?

**Comment by puremourning** [comment]
https://asciinema.org/a/sWaHBRsn41j420fYZFLEPXWNH

**Comment by Thieso** [comment]
Thanks for the detailed answer. 
So it works in vim much better than in neovim. In neovim it doesn't work for numpy arrays for example so I guess I will "upgrade" to vim. 
However, there is no support for a range. So visually selecting a line and then running it is not possible. This seems for a noob like me for a minor change to enable this. Is this possible to implement? Or are there major obstacles with this that I am missing?

**Comment by puremourning** [comment]
hover (balloon) works for me: https://asciinema.org/a/ubI8YzOUDwPicGm16s8EGDCsM

again only works in vim (because for some inexplicable reason this feature was removed by the Neovim developers)

you can use `:VimspectorEval <Ctrl-r>*`

**Comment by Thieso** [comment]
Ok thanks, so hover seems cool but not quite what I was looking for. 
However, I managed to get the desired functionality using this custom function and keybinding: 
```
" to let Vimspector eval work on ranges
function! VimspectorEvalRangeFct() range
    let windowNr = win_getid()
    let lines = getline(a:firstline, a:lastline)
    for i in range(len(lines))
        call vimspector#Evaluate(lines[i])
        call win_gotoid(windowNr)
    endfor
    call vimspector#Update()
endfunction
command -range EvalRange <line1>,<line2>call VimspectorEvalRangeFct()
vmap <leader>dr :EvalRange<CR>
```

Only thing which I didn't manage to get working is updating in variable window. This works after doing a step but not in the same step as evaluating an expression. 
But this is still a nice solution for my case. 

Thanks for the help
