### ISSUE TITLE
VimspectorInstall netcoredbg fails with http 404 error

### ISSUE THREAD

**Issue by kujbika** [puremourning/vimspector#290]
### Describe the bug

> When calling VimspectorInstall netcoredbg, the link for the external file is broken, hence a 404 not found error is given. 

### Minimal reproduciton

* Does your issue reproduce using `vim -Nu /path/to/vimspector/support/minimal_vimrc` ? \[Yes/No] Yes
* If you are using Neovim, does your issue reproduce using Vim? \[Yes/No]  Yes

> List of steps to reproduce:

> 1. Run `vim -Nu /path/to/vimspector/support/minimal_vimrc`
> 2. Execute :VimspectorInstall netcoredbg --verbose

### Expected behaviour

> The debugger adapter gets installed

### Actual behaviour

The following is the vimspector output
> Installing netcoredbg@master...
Downloading https://github.com/Samsung/netcoredbg/releases/download/latest/netcoredbg-linux-master.tar.gz to /home/kujbmar/.local/share/nvim/plugged/vimspector/gadgets/linux/download/netcoredbg/master/netcoredbg-linux-master.tar.gz
Failed - HTTP Error 404: Not Found, will retry in 1 seconds

### Environemnt

* Version of Vimspector: (e.g. output of `git rev-parse HEAD` if cloned or the
  name of the tarball used to install otherwise)

* Output of `vim --version` or `nvim --version`

```
NVIM v0.5.0-812-gd17e50879
```

### Additional information

The url https://github.com/Samsung/netcoredbg/releases/download/ does not exist, and thats the root cause of the bug.

**Comment by puremourning** [comment]
I guess they must have moved it. PR welcome to fix it.

**Comment by puremourning** [comment]
Yeah they have renamed the files and stuff. I'll take a look.

**Comment by puremourning** [comment]
Unfortunately with the latest version, it just crashed when trying to launch a test program. Sigh.

**Comment by puremourning** [comment]
@kujbika I pushed a pr to update netcoredbg (#291) - can you try if you get the same behaviour as Samsung/netcoredbg#48 ?

**Comment by kujbika** [comment]
@puremourning I checked the PR, and it indeed fixes the issue. Thanks!

**Comment by puremourning** [comment]
Oh ok great. It’s not crashing for you? If so I’ll merge it. I don’t csharp

**Comment by kujbika** [comment]
It fixes the reported issue, however i cant seem to make it work anyways. I published the dotnet project, seemingly configured the .vimspector.json well, but it says on launching: 
Launch Failed,
Closing down

On the left down corner, it says Channel exit with status 134.

I guess it is not related to the fix.

**Comment by puremourning** [comment]
Yeah that’s my point. The server just crashes on the latest version. I opened a PR on their GitHub but we will see. Most server vendors only care about one client.

**Comment by kujbika** [comment]
Would you link here the PR?

**Comment by puremourning** [comment]
It’s already linked. Scroll up

**Comment by kujbika** [comment]
Ah, sorry

**Comment by puremourning** [comment]
Fixed it; they made `cwd` mandatory. I added it in the gadget file so that vimspector will default it for you
