### ISSUE TITLE
[Tutorial] Potential error for CFLAGS value?

### ISSUE THREAD

**Issue by browser-bug** [puremourning/vimspector#298]
I was going through the tutorial and at [this point](https://puremourning.github.io/vimspector-web/demo-setup.html#check-out-and-build-the-vim-code) it is suggested to use `-g -gdwarf4 -DDEBUG -O0 -fno-omit-frame-pointer` for the `CFLAGS`. I'm on Ubuntu 20.04 and running `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0` I get the following error:

```
gcc: error: ‘-gdwarf4’ is ambiguous; use ‘-gdwarf-4’ for DWARF version or ‘-gdwarf’ ‘-g4’ for debug level
```

For novice users It may be confusing so fixing it to `-gdwarf-4` could help. I know it's a really stupid issue but just wanted to point that out.

**Comment by puremourning** [comment]
Thanks, fixed
