### ISSUE TITLE
[Feature Request]: Allowing viewing / editing conditional breakpoints

### ISSUE THREAD

**Issue by TamaMcGlinn** [puremourning/vimspector#299]
**Is your feature request related to a problem? Please describe.**
Conditional breakpoints work, but it doesn't appear to be possible to see the conditions already assigned to a breakpoint. Also, when you add a conditional breakpoint where there is already a (conditional or not) breakpoint, it deletes the breakpoint and discards your input. That is rather unexpected behaviour.

**Describe the solution you'd like**
Suggest that if you try to add a conditional breakpoint where there already is a breakpoint, the input is pre-populated with the current condition (if any), and of course it first deletes the breakpoint but then also adds the new one; that way you can edit/view the conditional breakpoint by adding another conditional breakpoint, and just press enter again if you just wanted to view it, solving both the deletion and visibility problems without adding new interface elements.

**Describe alternatives you've considered**
For the viewing of the conditions of breakpoints, an even better solution would be to have a separate window that lists all the locations of (and conditions of) the breakpoints. This would also facilitate navigating to breakpoints, which would also be really useful.

**Comment by puremourning** [comment]
what is in `:call vimspector#ListBreakpoints()` for conditional breakpoints ? I thought it showed the condition there.

But this might really be handled as part of #10

**Comment by puremourning** [comment]
Let’s roll this into #10
