### ISSUE TITLE
[Feature Request]: Option to disable telemetry system for Microsoft plugins

### ISSUE THREAD

**Issue by Trim** [puremourning/vimspector#304]
**Is your feature request related to a problem? Please describe.**

After reading the readme and searching for "telemetry vimspector" in Google it's not clear if the Microsoft telemetry system of Microsoft's  plugins is active or not with vimspector.

For example, at the end of [readme](https://github.com/Microsoft/vscode-cpptools) of vscode-cpptools plugin, it's written:

> This extension collects usage data and sends it to Microsoft to help improve our products and services. Collection of telemetry is controlled via the same setting provided by Visual Studio Code: "telemetry.enableTelemetry". Read our privacy statement to learn more.

The Microsoft telemetry system seems a bit linked to Visual Studio Code, but I don't know if it's enabled by default in the packages provided by Microsoft.

I suppose the telemetry system is enabled by default even with vimspector as it downloads binaries provided by Microsoft.

**Describe the solution you'd like**

Provides an option in vimspector to disable the Microsoft telemetry system with a default value to disable the telemetry.

This option should provides a value for the "telemetry.enableTelemetry" setting from Visual Studio Code and transfers this setting to to the `vscode-*` Microsoft plugins.

**Describe alternatives you've considered**

Other possible alternatives:
* download vsix from the [Open VSX](https://open-vsx.org/) project, although I'm not sure if telemetry is enabled or not in these packages. The only clear goal of this project is to be an alternative extension market place open to any IDE.
* build custom binaries for all `vscode-*` plugins with Microsoft Telemetry disabled by default
* if vimspector is really unable to disable the Microsoft telemtry, writes it clearly in the README

**Comment by puremourning** [comment]
Vimspector ignores all telemetry data. It does not send it anywhere. It simply shows it in a log window. 

There’s nothing to turn off here afaik

**Comment by Trim** [comment]
Thanks for the information ! By the way, that's a really nice project, many thanks :+1:
