### ISSUE TITLE
Duplicate environment variables are send to vscode-cpptools on Windows OS.

### ISSUE THREAD

**Issue by zoumi** [puremourning/vimspector#310]
Python will upcase all environment variables, so we can't copy all environment variables from os.environ and send they to vscode-cpptools.

Here is the link:
https://stackoverflow.com/questions/19023238/why-python-uppercases-all-environment-variables-in-windows

This is from vimspector source code(@debug_session.py line 742)
```python
    # TODO: Do we actually need to copy and update or does Vim do that?
    env = os.environ.copy()
    if 'env' in self._adapter:
      env.update( self._adapter[ 'env' ] )
    self._adapter[ 'env' ] = env
```

**Comment by zoumi** [comment]
For example if we have an env var:
ProgramW6432=C:\Program Files

vimspector will send PROGRAMW6432 to vscode-cpptools.
But vscode-cpptools already has an env var call ProgramW6432 from it's father process. So it throws an Error.

**Comment by zoumi** [comment]
Sorry for not using an issue template.This bug is obvious.

**Comment by puremourning** [comment]
I can't confirm either of our proposed changes resolves this as you have not provided steps to reproduce. I have a windows vm and I have vimspector working in it, but I can't reproduce the problem. Please list steps to reproduce using the examples in vimspector/tests/testdata/cpp

**Comment by zoumi** [comment]
We have to use the external console to reproduce it.
```
        "externalConsole": true,
```

Here is my .vimspector.json:
```json
{
  "configurations": {
    "Launch": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "name":"my gdb debug",
        "type":"cppdbg",
        "request": "launch",
        "args": [],
        "env":[],
        "environment": [],
        "MIMode":"gdb",
        "program": "test.exe",
        "externalConsole": true,
        "miDebuggerPath": "gdb.exe"
      }
    }
  }
}
```

**Comment by puremourning** [comment]
I can repro thanks. confirmed that latest master fixes this.
