### ISSUE TITLE
Is there a way to expand string variables?

### ISSUE THREAD

**Issue by zricethezav** [puremourning/vimspector#322]
**Is your feature request related to a problem? Please describe.**
Is there a way to expand a long string to see the full contents? Example, the variable `patchContent` below is concatenated with `...381 more`. Is there a configuration change so that I can see the full contents?

**Describe the solution you'd like**
The ability to see the full contents of a string in the variable window

**Describe alternatives you've considered**
Printing to console... but that kinda defeats the purpose of the debugger

**Additional context**
![Screen Shot 2020-12-19 at 1 05 07 PM](https://user-images.githubusercontent.com/15034943/102696249-ee441200-41fa-11eb-906f-01f58caa8097.png)

cc @puremourning

**Comment by puremourning** [comment]
Not unless the debug adapter you're using provides this. this is not something that is controlled by vimspector.
