### ISSUE TITLE
Global configuration wrongly sets ${workspaceRoot}

### ISSUE THREAD

**Issue by David-Kunz** [puremourning/vimspector#330]
### Description of erroneous behaviour 
The `${workspaceRoot}` variable is not correctly set and points to the directory of the current file when using a global configuration file (e.g. `~/.config/vimspector-config/configurations/macos/_all/vim-debug-adapter.json`).

### Detailed steps to reproduce

0. Create a file `~/someFolder/someTest.js` and navigate to `~/`
1. Provide a global configuration using `g:vimspector_base_dir`
2. Make use of `${workspaceRoot}` in your configuration
3. Execute the test in `~/someFolder/someTest.js` from your workspace `~/`
4. See that `${workspaceRoot}` points to the file directory (`~/someFolder`) and not to your workspace (`~/`)

If a local `.vimspector.json` configuration is used, the `${workspaceRoot}` variable correctly points to your workspace (`~/`).

**Comment by puremourning** [comment]
This is documented behaviour. 

There is no way for vimspector to know ehere your project root is in this case. You have to use something else.

**Comment by puremourning** [comment]
from: https://puremourning.github.io/vimspector/configuration.html#debug-configurations 

> In addition, users can create filetype-specific configurations in the Vimspector installation directory. This can be useful where the parameters for the debug session for a particular filetype are always known in advance, or can always be entered by the user. This allows for debugging to “just work” without any modification to the project source (no need to add a .vimspector.json). ***In this case, the ${workspaceRoot} and workspace-relative paths are interpreted relative to the file open in Vim. This isn’t ideal, but there is no other obvious way to default this variable.***

**Comment by David-Kunz** [comment]
Thanks a lot for this fast response and sorry for not reading the documentation properly!

**Comment by David-Kunz** [comment]
In case someone has a similar problem:
Instead of using a locally-installed test runner (e.g. `${workspaceRoot}/node_modules/bin/jest`) one can simply use a globally-installed one (e.g. `/usr/local/bin/jest`) -> so there's no need for `${workspaceRoot}` anymore.

**Comment by puremourning** [comment]
or use an environment variable, e.g set by vim:

```
let $NODE_MODULES = finddir( 'node_modules', ';' )
```

and use `$NODE_MODULES/bin/jest` or whatever.
