### ISSUE TITLE
[Feature Request]: Support for "SourceFileMap" in launch config for dotnet / msbuild

### ISSUE THREAD

**Issue by RononDex** [puremourning/vimspector#331]
In the launch config of vscode, one can provide a [source-file-mapping](https://github.com/OmniSharp/omnisharp-vscode/blob/master/debugger-launchjson.md#source-file-map) in case `<PathMap>`was set in a .csproj or is passed on to msbuild in different ways.

The project I am working makes use of `<PathMap>` in its .csproj file. I got it to work with omnisharp debugging in vscode by adding
```json
          "sourceFileMap": {
            "/": "${workspaceRoot}/"
        }
```
to the `launch.json` file

I tried the same by adding it to the launch config in `.vimspector.json`. However, it does not seem to work the way it does on vscode and debugging in vim using vimspector does not work.

**Comment by puremourning** [comment]
Please see CONTRIBUTING.md
