### ISSUE TITLE
[Feature Request]: Configuration snippet for puppet-editor-services DAP

### ISSUE THREAD

**Issue by lelutin** [puremourning/vimspector#332]
Hi there,

I was able to get vimspector to interoperate with the DAP adaptor that puppetlabs wrote for VS Code. The adapter lives in https://github.com/puppetlabs/puppet-editor-services as `puppet-debugserver`. With this, one can step through puppet manifest files while `puppet apply` is compiling the catalog for the requested file.

I'd like to submit those configuration snippets that I used to get it working. I'm just not sure where it would fit better (e.g. as an example configuration in the extra languages page? or maybe somewhere else?).

vimspector/gadgets/custom/cust_puppet-debugger:

~~~
{
  "puppet-debugserver":  {
    "download": {
      "url": "https://github.com/puppetlabs/puppet-editor-services/releases/download/${version}/${file_name}"
    },
    "all": {
      "version": "1.0.1",
      "file_name": "puppet_editor_services_1.0.1.zip",
      "checksum": "15b33bf63062f226466191d4417368a411f6a14f53c67d4898ca488a8b22454b",
      "adapters": {
        "cust_puppet-debugserver": {
          "command": [
            "ruby",
            "${gadgetDir}/cust_puppet-debugserver/puppet-debugserver",
            "--port",
            "${unusedLocalPort}"
          ],
          "configuration": {
            "cwd": "${workspaceRoot}"
          },
          "name": "puppet-debugserver",
          "port": "${unusedLocalPort}"
        }
      }
    }
  }
}
~~~

example launch configuration:

~~~
{
  "configurations": {
    "launch current file": {
      "adapter": "cust_puppet-debugserver",
      "configuration": {
        "request": "launch",
        "manifest": "${file}",
        "noop": true,
        "args": [ 
          "--modulepath",
          "/path/to/your/modules"
        ]
      }
    }
  }
}
~~~

I don't see a configuration option that can make it break on entry. you can however set at least a breakpoint before launching the debugger.

**Comment by puremourning** [comment]
Thanks!

this would be best added to the wiki page about additional language support. Would you mind updating it?

**Comment by lelutin** [comment]
Here we go!

https://github.com/puremourning/vimspector/wiki/languages/_compare/3d27bc399c33e15897105e8931baecb05ef56262...40d9f68ea9460adcfea12a832cdc18deaf3b2a76

**Comment by puremourning** [comment]
Much appreciated!
