### ISSUE TITLE
Debugging a node app has incorrect thread state

### ISSUE THREAD

**Issue by puremourning** [puremourning/vimspector#333]
### Describe the bug

When starting debugging on a node js script, vimspector shows the main thread as running, but it is actually paused on entry. User must hit continue to start execution.

### Minimal reproduciton

> Please answer the following questions

* Does your issue reproduce using `vim -Nu /path/to/vimspector/support/minimal_vimrc` ? YES
* If you are using Neovim, does your issue reproduce using Vim? YES

> List of steps to reproduce:

1 vim -Nu minimal_vimrc support/test/node/simple/simple.js
2. F5

### Expected behaviour

Debugging starts and pauses on first line of script.

### Actual behaviour

Debugger shows no stack trace or PC, thread state is running.

From user @mkastner on Gitter.

### Additional info

The problem is the sequence of events sent by the debug adapter. Vimspector requests threads:

1. When the initialisation exchange completes (requests all threads)
2. Whenever a thread event is received 
3. whenever a  stopped event is received.

If any of those happens while any other request is in progress, we cache the request and handle it later. The latest request is processed when the response to the outstanding request is received. 

The problem is if the event is a stopped event, it is the handling of the threads request that actually sets the thread state internally to stopped. In a sequence where the first event is a stopped event, we end up discarding the stopped event. like:

1. Stopped event (thread 1 = stopped) (request threads)
2. Initialisation complete (cache request)
3. threads response received (discard response and process cached request)
4. response received (but forgotten about the stopped event).

The solution is to always process the thread response, but then handle the cached request. To avoid flicker, we don't draw the screen in the case where we're sending a cached request.

**Comment by mkastner** [comment]
Thanks a lot! I haven't tried it yet, but I'll do later this day. Anyway, this a great product and I appreciate your work.
