### ISSUE TITLE
Way to redirect input

### ISSUE THREAD

**Issue by Asdas91** [puremourning/vimspector#335]
Is there a way to redirect the standard input of the program I want to debug in Vimspector?

In bash it is done by using '<' character, for example `program < input.txt`. I wasn't able to achieve this in vimspector configuration. When I specify arguments to be "<" and "input.txt" then the program is just run with these arguments but the input is not actually redirected. I tried searching the documentation but I did not find anything.

**Comment by puremourning** [comment]
The answer is that it entirely depends on which debug adapter you're using, and a number of other things. There is no specific support in vimspector for this, nor is there any provision in DAP specifically for this.

See CONTRIBUTING.md. The issue tracker is not for support, it's for bug reports and specific, actionable feature requests. As such, closing.
