### ISSUE TITLE
[Feature Request]: Automatically create files .vimspector.json

### ISSUE THREAD

**Issue by thevan96** [puremourning/vimspector#349]
every time i debug i have to mess around configuring the .vimspector file. You can add a function to create the .vimspector file yourself

**Comment by puremourning** [comment]
This is a low-effort duplicate of https://github.com/puremourning/vimspector/issues/270

You can also create your configurations once in a central location (see the docs for details).

**Comment by puremourning** [comment]
https://puremourning.github.io/vimspector/configuration.html#debug-configurations

I use this a lot. Here are some of mine for home (I have many more for work): https://github.com/puremourning/.vim-mac/tree/master/vimspector-conf/configurations/macos

**Comment by thevan96** [comment]
Thank you
