### ISSUE TITLE
[Feature Request]: Support C# Samsung debugger

### ISSUE THREAD

**Issue by jpfeiffer16** [puremourning/vimspector#35]
I'd be interested in adding C# support with the new Samsung debugger: https://github.com/Samsung/netcoredbg

I know there were discussions about it using the Microsoft vsdbg, but that didn't go anywhere because of licensing issues.

@puremourning do you know anything about this? I feel like I saw a pr or something that added that support and I was trying to find that to go off of, but use the Samsung debugger instead.

**Comment by puremourning** [comment]
In theory you should just be able to configure it up in vimspector.json   

The docs on this aren’t exactly stellar but essentialy you just have to get it jnstallled somewhere and find out how to start it, then work out the launch parameters from its package.json.

**Comment by puremourning** [comment]
From looking at the code (sigh) the launch arguments seem to be:  

- program (string)
- args (list)
- stopOnEntry (bool)

https://github.com/Samsung/netcoredbg/blob/master/src/debug/netcoredbg/vscodeprotocol.cpp#L316

And the README says how to build and run it. 

So should be easy without vimspector changes.

**Comment by puremourning** [comment]
> ? I feel like I saw a pr or something that added that support

Possibly because install_gadget includes (disabled) ability to install the one with issues. I should squelch that code.

**Comment by jpfeiffer16** [comment]
Ok. I'll give that a try! Sorry for the ignorance, what is install_gadget?

**Comment by jpfeiffer16** [comment]
Oh. I see the python script.

**Comment by puremourning** [comment]
oh install_gadget.py is the installer script that downloads and installs some debug adapters: https://github.com/puremourning/vimspector/blob/master/install_gadget.py

If you can get it working, i'd be thrilled to merge a pr which includes it and updates the readme to say it's supported.

**Comment by puremourning** [comment]
I pushed a branch (c-sharp-samsung) which adds the adapter to install_gadget.py

I haven't actually tested that it works because i don't really have a trivial c-sharp (botnet core) application i could test quickly on macOS.

You _should_ be able to use it by running './install_gadget.py --force-enable-csharp' with a .vimspector.json like this:

```json
{
    "configurations": {
        "launch": {
            "adapter": "netcoredbg",
             "configuration": {
                 "request": "launch", 
                 "program": "${workspaceRoot}/path/to/binary",
                 "args": [ "arg1", "arg2...." ],
                 "stopAtEntry": true 
             }
        }
    }
}
```

let me know how you get on.

**Comment by jpfeiffer16** [comment]
Awesome. Thank you so much!

**Comment by jpfeiffer16** [comment]
@puremourning . I'm trying to get this repo set up with Vundle so it fits nicely with my other plugins. The `plugin/vimspector` file is getting run, but non of the functions or commands are showing up. That would indicate to me that the stuff in`autoload/*` is not getting run. Should this work with Vundle or is it only supported using the native vim packages system?

**Comment by puremourning** [comment]
It works with vundle (that’s how I use it). It doesn’t run and auto loaded functions on a startup to avoid slow startup. 

If you use the mappings, does it work?

**Comment by jpfeiffer16** [comment]
Ooh. I didn't try the mapping sets, I just expected the functions to work
when I called them. My bad. I'll try that out.

**Comment by puremourning** [comment]
They do work, you just have to type the full function name as they don’t get auto loaded until first use.

**Comment by jpfeiffer16** [comment]
I see. Yea, it does work fine when I use the bindings. Thanks! I should have actually tried that first.

**Comment by jpfeiffer16** [comment]
Got it to work but I had to make a few tweaks to the code. Still digging in to see if that's just the adapter straying from the spec. I suspect it is. That being said, what an awesome plugin. This is fantastic! Thanks for all your work on this.

**Comment by puremourning** [comment]
That’s really great to hear. Thanks !

**Comment by puremourning** [comment]
By the way : any other feedback on anything from UI to documentation etc more than welcome.

**Comment by puremourning** [comment]
Added in #37
