### ISSUE TITLE
[Feature Request]: Kill the application when closing the debugger

### ISSUE THREAD

**Issue by Zhern** [puremourning/vimspector#353]
When I am locally debugging a server application, each time after the debug session ends I need to manually call something like `kill -9 [pid]`.

Ideally I would like a kill message to be automatically sent to the application when the Vimspector debug session ends.

**Comment by puremourning** [comment]
Can you share your vimspector json? If it is a launch request this should be the default bahvaioir of the debug adapter

**Comment by Zhern** [comment]
Here is my .vimspector.json file:
```
{
    "configurations": {
        "launch": {
            "adapter": "CodeLLDB",
            "configuration": {
                "request": "launch",
                "program": "${workspaceRoot}/target/debug/my_daemon"
            }
        }
    }
}
```
The program is a rust program that is an async local server, basically:
```
#[tokio::main]
async fn main() {
    let server = async move {
        loop {
            ... never ends
        }
    };
    server.await;
}
```

**Comment by puremourning** [comment]
Hmmm.

It seems that at some point in the past I decided that if possible we should not terminate the debugee:

```
    if self._server_capabilities.get( 'supportTerminateDebuggee' ):
      # If we attached, we should _not_ terminate the debuggee
      arguments[ 'terminateDebuggee' ] = False
```

But I think this is wrong, and the [default of the protocol](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Disconnect) is probably correct:

> If the debuggee has been started with the ‘launch’ request, the ‘disconnect’ request terminates the debuggee.
If the ‘attach’ request was used to connect to the debuggee, ‘disconnect’ does not terminate the debuggee.
This behavior can be controlled with the ‘terminateDebuggee’ argument (if supported by the debug adapter).

Can you try removing the above block from `python3/vimspector/debug_session.py` (around line 794, in `_StopDebugAdapter`) - see if that does what you want. I might remove this, as it seems sketchy to go against the protocol defaults.

**Comment by Zhern** [comment]
It works like a charm with the block commented out as you said. Thank you!

**Comment by puremourning** [comment]
I'll remove it, I think it's sketchy enough that if it were to be set, it should be decided by the user. And I don't really want to pester the user with too many questions.

Maybe later I'll add a "Do you want to terminate the debuggee?" type question, but maybe not.

**Comment by puremourning** [comment]
@Zhern want to give #355 a spin and see how you like it?

**Comment by Zhern** [comment]
Fine for me!

**Comment by puremourning** [comment]
I think maybe it should just do the default if clicking the winbar button. it's kinda annoying to click a button then have a message appear on the other side of the screen

**Comment by puremourning** [comment]
Yeah I think that's much better.
