### ISSUE TITLE
Balloon pop up Error while using mouse cursor

### ISSUE THREAD

**Issue by blues0024** [puremourning/vimspector#363]
> DO NOT DELETE THIS TEMPLATE. IF YOU DELETE THIS TEMPLATE AND DO NOT COMPLETE IT, YOUR ISSUE WILL BE CLOSED.

### Describe the bug
When I moved my cursor with mouse on a variable in order to check the information of the variable through pop up (Balloon), my vim occur E730 ERROR : Using List as a String. Soon the error message disappeared, and blink again when I move cursor again. This problem happended in the given test file; /my/vimspector/path/support/test/python/main.py. As I'm totally new to Vimspector, I've couldn't solve this problem myself. I already read some issues on 'utils.py' but that doesn't helped for me.

> Provide A clear and concise description of what the bug is.

### Minimal reproduciton

> Please answer the following questions

* Does your issue reproduce using `vim -Nu /path/to/vimspector/support/minimal_vimrc` ? \[Yes/No]
> Impossible. That command emerge a new error. "Cannot open /my/vimspector/path/opt/vimspector/tests/vimrc. I guess the 'tests' folder is missing in the newest repository..
* If you are using Neovim, does your issue reproduce using Vim? \[Yes/No]
> I'm not using Neovim. vim 8.1.1800

> List of steps to reproduce:

> 1. Run `vim -Nu /path/to/vimspector/support/minimal_vimrc`
> 2. Open _this project_...
> 3. Press _this sequence of keys_

> Use the following Vimspector config file:
As I used your test files only, .vimspector.json is same with you.
```
{
  "$schema": "https://puremourning.github.io/vimspector/schema/vimspector.schema.json",
  "adapters": {
    "run_with_debugpy": {
      "command": [ "${workspaceRoot}/run_with_debugpy" ],
      "port": 9876,
      "env": {
        "DEBUG_PORT": "9876"
      }
    },
    "python-remote-docker": {
      "variables": {
        "port": "8765"
      },
      "port": "${port}",
      "launch": {
        "remote": {
          "container": "${ContainerID}",
          "runCommand": [
            "python3", "-m", "debugpy", "--listen", "0.0.0.0:${port}",
                                        "--wait-for-client",
                                        "%CMD%"
          ]
        },
        "delay": "5000m"
      }
    }
  },
  "configurations": {
    "Use custom gadget": {
      "adapter": "test_custom",
      "configuration": {
        "request": "launch"
      }
    },
    // This is a comment.
    "run legacy vscode-python": {
      "adapter": "vscode-python", /* coment goes here too */
      "configuration": {
        "request": "launch",
        "type": "python",
        "cwd": "${workspaceRoot}",
        "program": "${file}",
        "stopOnEntry": true,
        "console": "integratedTerminal"
      },
      "breakpoints": {
        "exception": {
          "raised": "N",
          "uncaught": "",
          "userUnhandled": ""
        }
      }
    },
    "attach": {
      "adapter": "multi-session",
      "configuration": {
        "request": "attach"
      },
      "breakpoints": {
        "exception": {
          "raised": "N",
          "uncaught": "",
          "userUnhandled": ""
        }
      }
    },
    "attach-run": {
      "adapter": "run_with_debugpy",
      "configuration": {
        "request": "attach"
      },
      "breakpoints": {
        "exception": {
          "raised": "N",
          "uncaught": "",
          "userUnhandled": ""
        }
      }
    },
    "docker-attach": {
      "adapter": "python-remote-docker",
      "remote-cmdLine": [ "/root/main.py" ],
      "remote-request": "launch",
      "configuration": {
        "request": "attach",
        "pathMappings": [
          {
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "/root"
          }
        ]
      }
    },
    "run": {
      "adapter": "debugpy",
      "configuration": {
        "request": "launch",
        "type": "python",
        "cwd": "${workspaceRoot}",
        "program": "${file}",
        "stopOnEntry": false,
        "console": "integratedTerminal"
      },
      "breakpoints": {
        "exception": {
          "raised": "N",
          "uncaught": "",
          "userUnhandled": ""
        }
      }
    },
    "run - default": {
      "adapter": "debugpy",
      "variables": {
        "MAKE_ENV_OUTPUT": {
          "shell": "${workspaceRoot}/make_env.sh"
        }
      },
      "configuration": {
        "request": "launch",
        "type": "python",
        "cwd": "${workspaceRoot}",
        "program": "${program:${file\\}}",
        "stopOnEntry#json": "${StopOnEntry:true}",
        "console": "integratedTerminal",
        "args#json": "${args:[]}",
        "igored#json#s": "string not json",
        "env#json": "${MAKE_ENV_OUTPUT}"
      },
      "breakpoints": {
        "exception": {
          "raised": "N",
          "uncaught": "",
          "userUnhandled": ""
        }
      }
    },
    "run - main.py": {
      "adapter": "debugpy",
      "configuration": {
        "request": "launch",
        "type": "python",
        "cwd": "${workspaceRoot}",
        "program": "${workspaceRoot}/main.py",
        "stopOnEntry": false,
        "console": "integratedTerminal"
      },
      "breakpoints": {
        "exception": {
          "raised": "N",
          "uncaught": "",
          "userUnhandled": ""
        }
      }
    },
    "run - exception question": {
      "adapter": "debugpy",
      "configuration": {
        "request": "launch",
        "type": "python",
        "cwd": "${workspaceRoot}",
        "program": "${file}",
        "stopOnEntry": false,
        "console": "integratedTerminal"
      }
    }
  }
}
```

### Expected behaviour

> Provide A clear and concise description of what you expected to happen.
I just want to check the variable information through pop up window without any errors.

### Actual behaviour

> What actually happened, including output, log files etc.
<img width="1739" alt="image" src="https://user-images.githubusercontent.com/79687451/109269428-d10d6e80-784f-11eb-8fa6-b29c0439feb4.png">
Because the error message is gone too fast, I can only upload the captured image. There is somtimes an empty pop up or the message: "Exception occurred during evaluation".
> Please include:
> * Vimspector log (~/.vimspector.log)
> * Output from any or all UI diagnostic tabs (Server, etc.)

### Environemnt

***NOTE***: NeoVim is supported only on a best-effort basis. Please check the README
for limitations of neovim. Don't be offended if I ask you to reproduce issues in
Vim.

***NOTE***: Windows support is experimental and best-efrort only. If you find an
issue related to Windows or windows-isms, consider sending a PR or
discussing on Gitter rather than raising an issue.

* Version of Vimspector: (e.g. output of `git rev-parse HEAD` if cloned or the
  name of the tarball used to install otherwise)
vimspector-macos-600905010

* Output of `vim --version` or `nvim --version`

```
VIM - Vi IMproved 8.1
```

* Output of `which vim` or `which nvim`:

```
/usr/local/bin/vim
```

* Output of `:py3 print( __import__( 'sys' ).version )`:

```
3.7.4 (default, Sep 28 2019, 16:39:19)
[Clang 11.0.0 (clang-1100.0.33.8)]
```

* Output of `:py3 import vim`:

```
paste here
```

* Output of `:py3 import vimspector`:

```
paste here
```

* For neovim: output of `:checkhealth`

```
paste here
```

* Operating system: <linux or macOS> and version
>  macOS Big Sur 11.0.1
  
### Declaration

> Please complete the following declaration. If this declaration is not completed, your issue may be closed without comment.

* I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md) \[Yes/No]
> Yes

**Comment by puremourning** [comment]
Thanks for the report. This is clearly a bug. I’ll have to try and repro. 

Please can you include your vimspector log when this happens?

**Comment by puremourning** [comment]
What is the behaviour if you trigger the popup with a keyboard mapping, e.g.:

* start debugging
* `nmap ,D <Plug>VimspectorBaloonEval`
* move to an identifier and press `,D`

I can't currently reproduce this.

**Comment by puremourning** [comment]
> Impossible. That command emerge a new error. "Cannot open /my/vimspector/path/opt/vimspector/tests/vimrc. I guess the 'tests' folder is missing in the newest repository..

Oh I guess you installed using the tarball. Please could you clone the plugin and retry, like this:

* `cd some_directory`
* `git clone https://github.com/puremourning/vimspector`
* `cd vimspector`
* `vim -Nu support/minimal_vimrc ....`

**Comment by blues0024** [comment]
Hi, Thanks for your quick reply.

Yes, as you mentioned, I installed my vimspector through the tarbell. So I reinstalled my vimspector as you wrote. Still, the error showed the same message. (Sorry for Korean. The error message is saying "Using List as a String"
<img width="703" alt="image" src="https://user-images.githubusercontent.com/79687451/109377369-48093c80-790e-11eb-9a1d-f49732039e07.png">

However, when I tried to mapping the BalloonEval explicitly, the pop up came out successfully. Even though, when I choose the specific lines in order to see additional information, another error message occurred as followed.
<img width="703" alt="image" src="https://user-images.githubusercontent.com/79687451/109377436-b9e18600-790e-11eb-8590-6886cc3c8eef.png">

I want to show my bug report through some log file, but I don't know how to do it. That's why I always post the screenshots of the error messages, sorry. :(

**Comment by blues0024** [comment]
At the end of the struggle for 8 hours, I noticed my vim version is the cause of the problem.... I confused that my error occurred even I used the newest version of the vim. At least vim>8.2 is needed..! Thx for your concerning!

**Comment by puremourning** [comment]
Can you get

The FULL output of `vim —version`

The vimspector log file (`VimspectorToggleLog`)

**Comment by puremourning** [comment]
Ok thanks. Yes vim 8.2 is required
