### ISSUE TITLE
Error detected while processing function vimspector#Stop

### ISSUE THREAD

**Issue by Hampycalc** [puremourning/vimspector#365]
> DO NOT DELETE THIS TEMPLATE. IF YOU DELETE THIS TEMPLATE AND DO NOT COMPLETE IT, YOUR ISSUE WILL BE CLOSED.

### Describe the bug

Using the HUMAN key mappings, after starting debugging with `vimspector#Continue()` (F5), calling `vimspector#Stop()` (F3) give the error:
```
Error detected while processing function vimspector#Stop:
line    5:
E488: Trailing characters:     options = {}
```

It seems this can be fixed by changing `autoload/vimspector.vim` line 197-201 `function! vimspector#Stop` from:
```
  if a:0 == 0
    options = {}
  else
    options = a:1
  endif
```
to:
```
  if a:0 == 0
    let options = {}
  else
    let options = a:1
  endif
```

Using vimspector commit 5bd83d3e37403d8cc7ad3378a58d58f06a53d318 (current master).
NVIM v0.5.0-dev+1089-gdc3ca16a9

* I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md) Yes

**Comment by Hampycalc** [comment]
Apologies for not completing the full template, but it seems like this is a bug with the code - although I'm not a vimscript guy, so I could be wrong. Ping me a reply if so and I'll do a full debug dump as per the template

**Comment by puremourning** [comment]
ugh, thanks for the report. I'll fix it.

I think I wrote on the PR that added this "I should probably add some tests"... yeah.. .shoulda done that.
