### ISSUE TITLE
[Feature Request]: Show default keybindings in toolbar if HUMAN mode

### ISSUE THREAD

**Issue by amit777** [puremourning/vimspector#378]
**Is your feature request related to a problem? Please describe.**
if I have `let g:vimspector_enable_mappings='HUMAN'` It's a little frustrating to lookup the various F1-F12 actions.  I also disable mouse so I rely on keybindings more.  

**Describe the solution you'd like**
if the "Stop" "Cont" "Pause" "Next" etc toolbar items could show the default keybindings in parenthesis, that would be awesome!
![Screen Shot 2021-03-28 at 12 27 15 AM](https://user-images.githubusercontent.com/2703309/112745332-62a9f200-8f5c-11eb-8728-52c9fa02195e.png)

**Comment by amit777** [comment]
I just realized I can manually change this menu items by customizing the UI.  It's what I will do, but I still think it would be a great default feature to just display the default Fkey for VSCODE or HUMAN mode

**Comment by amit777** [comment]
here is the customized bar with the HUMAN F<key> in case it's helpful
```viml
" customize the UI to add Fkeys
function! s:CustomiseWinBar()
  call win_gotoid( g:vimspector_session_windows.code )
  " Clear the existing WinBar created by Vimspector
  nunmenu WinBar
  nnoremenu WinBar.■\ Stop\(F3\) :call vimspector#Stop( { 'interactive': v:false } )<CR>
  nnoremenu WinBar.▶\ Cont\(F5\) :call vimspector#Continue()<CR>
  nnoremenu WinBar.▷\ Pause\(F6\) :call vimspector#Pause()<CR>
  nnoremenu WinBar.↷\ Next\(F10\) :call vimspector#StepOver()<CR>
  nnoremenu WinBar.→\ Step\(F11\) :call vimspector#StepInto()<CR>
  nnoremenu WinBar.←\ Out\(F12\) :call vimspector#StepOut()<CR>
  nnoremenu WinBar.⟲:\(F4\) :call vimspector#Restart()<CR>
  nnoremenu WinBar.✕ :call vimspector#Reset( { 'interactive': v:false } )<CR>
  " Cretae our own WinBar
endfunction

augroup MyVimspectorUICustomistaion
  autocmd!
  autocmd User VimspectorUICreated call s:CustomiseWinBar()
augroup END

```

**Comment by puremourning** [comment]
This is The exact reason that we added the customisation and there is even an example to do it. Not going to change the default because it would make the bar too wide.
