### ISSUE TITLE
[Feature Request]: Set variable value, etc.

### ISSUE THREAD

**Issue by puremourning** [puremourning/vimspector#38]
DAP supports assigning values to variables/expressions.

Vimspector does not.

**Comment by tinmarino** [comment]
Yes it does. Have you fixed it meanwhile ? From the console `i = 30`.


![vimspector_change_var](https://user-images.githubusercontent.com/6123962/72103859-d84e8180-3308-11ea-85ae-ef3763bc75af.gif)

**Comment by puremourning** [comment]
Ah that does sorta work, but only for that particular debug adapter. You're actually sending an ['evaluate' request](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Evaluate), which is being passed by the adapter to the downstream debugger. This isn't supported by all debug adapters.

This feature request is more about the more general feature supported by DAP (e.g. changing a value from the locals/watch window): https://microsoft.github.io/debug-adapter-protocol/specification#Requests_SetVariable

**Comment by puremourning** [comment]
This was implemented a long time ago.
