### ISSUE TITLE
Failed to set breakpoint when using symlinks

### ISSUE THREAD

**Issue by izhakjakov** [puremourning/vimspector#388]
### Describe the bug
vimspector started giving me an error:
```
Unable to set breakpoint: Failed to set breakpoint: "{e}"
```
- I am using it with Go on NeoVIM on Darwin (MacOS)
- Trying to use it with the old configuration file that used to work
- Tried it with code that I was previously able to debug and it still giving me the error

### Possible culprit
It seems like the problem happens when starting vim in a symlink
I exited vim and did this:
```
cd $(realpath .)
```
Which took me to the physical address, then, I started vim again and this time the breakpoints worked.

### Additional information
Upon request.  (sorry I am a bit short on time lately)

**Comment by puremourning** [comment]
Please complete the issue template.
