### ISSUE TITLE
Exception while loading vimspector: Vim(py3):UnicodeEncodeError: 'latin-1' codec can't encode character '\u25cf' in position 0: ordinal not in range(256) From: function vimspector#Continue[1]..<SNR>48_Enabled[2]..vimspector#internal#state#Reset, line 3 Vimspector unavailable: Requires Vim compiled with Python 3.6

### ISSUE THREAD

**Issue by Joejiong** [puremourning/vimspector#396]
> DO NOT DELETE THIS TEMPLATE. IF YOU DELETE THIS TEMPLATE AND DO NOT COMPLETE IT, YOUR ISSUE WILL BE CLOSED.

### Describe the bug
Exception while loading vimspector: Vim(py3):UnicodeEncodeError: 'latin-1' codec can't encode character '\u25cf' in position 0: ordinal not in range(256) From: function vimspector#Continue[1]..<SNR>48_Enabled[2]..vimspector#internal#state#Reset, line 3 Vimspector unavailable: Requires Vim compiled with Python 3.6
> Provide A clear and concise description of what the bug is.

### Minimal reproduciton

> Please answer the following questions

* Does your issue reproduce using `vim --clean -Nu /path/to/vimspector/support/minimal_vimrc` ? \[Yes/No]
* If you are using Neovim, does your issue reproduce using Vim? \[Yes/No]

> List of steps to reproduce:

> 1. Run `vim ---clean Nu /path/to/vimspector/support/minimal_vimrc`
> 2. Open _this project_...
> 3. Press _this sequence of keys_

> Use the following Vimspector config file:

```
paste .vimspector.json here
```

### Expected behaviour

> Provide A clear and concise description of what you expected to happen.

### Actual behaviour

> What actually happened, including output, log files etc.

> Please include:
> * Vimspector log (~/.vimspector.log)
> * Output from any or all UI diagnostic tabs (Server, etc.)

### Environemnt

***NOTE***: NeoVim is supported only on a best-effort basis. Please check the README
for limitations of neovim. Don't be offended if I ask you to reproduce issues in
Vim.

***NOTE***: Windows support is experimental and best-efrort only. If you find an
issue related to Windows or windows-isms, consider sending a PR or
discussing on Gitter rather than raising an issue.

* Version of Vimspector: (e.g. output of `git rev-parse HEAD` if cloned or the
  name of the tarball used to install otherwise)

* Output of `vim --version` or `nvim --version`

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  7 2021 06:55:02)
Included patches: 1-2840
Compiled by root@yq01-sys-hic-k8s-p40-qm-0014.yq01.baidu.com
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               -ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             +sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/vim82/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -ggdb -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lSM -lICE -lm -ltinfo -lselinux -lcanberra -ldl
```

* Output of `which vim` or `which nvim`:

```
/usr/bin/vim (i have changed the symbolic link to vim82)
```

* Output of `:py3 print( __import__( 'sys' ).version )`:

```
zsh: command not found: py3
```

* Output of `:py3 import vim`:

```
zsh: command not found: py3
```

* Output of `:py3 import vimspector`:

```
zsh: command not found: py3
```

* For neovim: output of `:checkhealth`

```
paste here
```

* Operating system: <linux or macOS> and version
  linux
### Declaration

> Please complete the following declaration. If this declaration is not completed, your issue may be closed without comment.

* I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md) \[Yes/No]

**Comment by puremourning** [comment]
Please see CONTRIBUTING.md. I cannot review issues without the issue template.
