### ISSUE TITLE
[Feature Request]: Zero config for trivial projects

### ISSUE THREAD

**Issue by puremourning** [puremourning/vimspector#40]
**Is your feature request related to a problem? Please describe.**
Configuring vimspector for the project isn't easy if you don't know the options for a given adapter. The READMe has some examples, but that's not easily accessible. VScode provides semantic completion (using json language server and son schema from package.json), but vimspector requires you just know its config or read the instructions n the website.

**Describe the solution you'd like**
Ideally, read package.json and integrate with YCM's json language server support (which doesn't exist) and its snippet completions (which also don't exist). 

But for starters we could just have some UltiSnips snippets which cover the supported languages

Out of scope: snippets for snippet systems I don't use, support for other completion systems I don't use.

**Describe alternatives you've considered**
As above - maybe parse the package.json if it exists (e.g. for vscode-cpptools, vscode-python)

**Comment by puremourning** [comment]
This is still useful, but with adding the json schema, editors can take advantage of that, including at least my own fork of ycm.

**Comment by tinmarino** [comment]
Is it acceptable to write a fallback `GetDefaultConfig` to `PathToConfigFile` if no config file is found: 

https://github.com/puremourning/vimspector/blob/68c47edabb627705e6c8beff1909f63a5041e6cd/python3/vimspector/debug_session.py#L79-L89

If current filetype is python => returns the formated string (replacing current_file AND current_file_pwd)

```json
{
  "configurations": {
    "simple_python: launch": {
      "adapter": "vscode-python",
      "configuration": {
        "name": "Python: Launch current file",
        "type": "python",
        "request": "launch",
        "cwd": "{current_file_pwd}",
        "stopOnEntry": true,
        "console": "externalTerminal",
        "debugOptions": [],
        "program": "{curren_file}"
      }
    }
  }
}
```

That way, for a short standalone file, the user do not have to create a config file, just press `F5` ?

What do you think ? I'm coding that and make a PR ?

**Comment by puremourning** [comment]
I think it's simpler to just put a `.vimspector.json` in your home directory.

Alternatively, if that's not great, then we could perhaps have something like `${gadgetDir}/.conf.d/<filetype>.defaults.json` which contains default debug configs for `<filetype>`. 

The [existing variable replacements](https://puremourning.github.io/vimspector/configuration.html#predefined-variables), like `${workspaceRoot}` would have to be adjusted when using configs from that locaiton.

I wouldn't merge a PR which includes adapter-specific configuraiton in the core code, no.

**Comment by tinmarino** [comment]
> I wouldn't merge a PR which includes adapter-specific configuraiton in the core code, no.

Understood, this was a pretty dirty idea of mine. A good error to learn. I'm removing it. 

> I think it's simpler to just put a `.vimspector.json` in your home directory.

Good enough for me, now that I spent time to "understand" it. But to get newcomers, to show them the plugin work :

> Alternatively, if that's not great, then we could perhaps have something like `${gadgetDir}/.conf.d/<filetype>.defaults.json` which contains default debug configs for `<filetype>`. These could be written by `install_gadget.py` even (optionally?)

This is a perfect solution: 

1. Separate it from the core
2. No configuration required for testing the plugin, familiarize ... hook newcomers


> But for starters we could just have some UltiSnips snippets which cover the supported languages

You mean snippet for `.vimspector.json`. I agree it helps but zero conf as your idea above is a killer feature.

**Comment by puremourning** [comment]
The main usual problem with "zero conf" is that it actually doesn't work in practice for any non-toy examples. 

That said, I actually have a _real_ use case at work that I was thinking about today, where I have lots of projects where the debug configuration is (or could be made to be) identical, given enough `variables` and such, so I think it's worthwhile.

**Comment by puremourning** [comment]
There is support for zero config in a sense now. You can put configs in `/path/to/vimspecotr/configurations/<os>/<filetype>` and vimspector with union them with the (now optional) `.vimspector.json`.

This isn't a panacea, because as stated above there are real limitations to what can be written in them (though Vimspector's variable substitution helps a lot). It also means vimspector has to guess the project root.

This feature is currently undocumented, so feedback is welcome on the approach.

**Comment by puremourning** [comment]
it's documented now.
