### ISSUE TITLE
Debugpy install error.

### ISSUE THREAD

**Issue by Eadwulf** [puremourning/vimspector#401]
> DO NOT DELETE THIS TEMPLATE. IF YOU DELETE THIS TEMPLATE AND DO NOT COMPLETE IT, YOUR ISSUE WILL BE CLOSED.

### Describe the bug
The :VimspectorIntsall debugpy command fails to download the .zip file.

> Provide A clear and concise description of what the bug is.
Vimspector tries to download the file from https://github.com/microsoft/debugpy/archive/v1.2.1.zip
but the file is actually located in https://github.com/microsoft/debugpy/releases/tag/v1.2.1.zip

**Comment by puremourning** [comment]
Please complete the issue tamplate. This clearly does not reproduce for me or for my CI.
