### ISSUE TITLE
[Feature Request]: Expose the ${lineNumber} predefined variable

### ISSUE THREAD

**Issue by findleyr** [puremourning/vimspector#404]
I'd like to write a debug profile configuration for Go (dlv-dap), that runs the current test being edited. I can find the current package using the `${relativeFile}` predefined variable + shelling out to a script (the ability to shell out to define a variable is great -- thanks!).

However, I can't automatically find the current test function (to be run with the delve `-test.run` argument), so need to prompt for this variable. https://github.com/puremourning/vimspector/blob/054ea35428e5e8d6abe12b6a535a3b0426d4874e/python3/vimspector/debug_session.py#L214 mentions that VS Code supports the `${lineNumber}` variable. If vimspector also supported this, I could easily write a script that found the relevant test function in the source, and my debug profile could just Do The Right Thing.

It _feels_ like this would be trivial to add, and would be useful for this type of workflow.  I'd be happy to try doing this myself, if someone could point me in the right direction. Thanks.

**Comment by findleyr** [comment]
Ok, I realized how to do this, wrote a separate program to extract the test name at point, and it works great!

I've sent a PR for the new predefined variable, assuming that's desirable.

**Comment by puremourning** [comment]
This can be done already. In fact I use this all the time. Example: https://github.com/puremourning/vimspector/blob/master/compiler/vimspector_test.vim#L81

**Comment by findleyr** [comment]
Hi, sorry I don't think that's quite equivalent.  Exposing it as a predefined variable means I can shell out to a Go program (which understands Go code).  Having to write it in vimscript is much less accessible.

Considering that it's trivial to add lineNumber, why not add it and enable this workflow?

**Comment by findleyr** [comment]
Specifically, here is my debug profile configuration:

```
    "test-dap": {
      "adapter": "dlv-dap",
      "default": true,
      "variables": {
        "TestDir": {
          "shell": ["dirname", "${relativeFile}"]
        },
	"TestName": {
          "shell": ["testname", "${file}:${lineNumber}"]
	}
      },
      "configuration": {
        "request": "launch",
        "mode": "test",
        "program": "./${TestDir}",
	"args": ["-test.run", "${TestName}"]
      }
    }
```

Another argument for exposing it as configuration is that certain languages have target semantics that are not easily expressed with regular expressions. For example, Go has a concept of subtests, which are written as nested function literals (`t.Run(name, testFunc)`). Subtests can be run via `dlv test -test.run=TestName/subtestName`.  Getting that right really requires writing the logic in Go, and it's easy to plug this logic in via the `"shell"` directive.

**Comment by puremourning** [comment]
You don’t have to use a regex. it’s one line of vimscript to call your other app

let lineNum = system( ‘testname ‘ . bufname() . ‘:’ . line( ‘.’ ) )->trim()

**Comment by puremourning** [comment]
Or just set the var manually

call vimspector#launchWithSettings( { ‘lineN’: line( ‘.’ ) } )

**Comment by findleyr** [comment]
Fair point, I can do that.  Thanks for the advice.

Out of curiosity, is there a particular reason _not_ to expose `${lineNumber}`, considering that it is exposed in VS Code? I would understand not wanting to add arbitrary new configuration, but this seems to be filling a gap in a trivial and at least somewhat useful way.

**Comment by puremourning** [comment]
No particular objection other than it doesn’t seem that useful in that many scenarios. 

But truth be told I looked at the PR and it’s missing tests and updates the wrong doc file and I’m on my phone so it’s easier to just work around it.

**Comment by findleyr** [comment]
Ok.  FWIW I grepped for other variable names to find the places I thought needed to be updated. Would have happily added tests if asked, given some advice for how to structure them -- I didn't see tests for other variable values.

**Comment by puremourning** [comment]
Sure sorry that wasn’t a critique of the PR (which I appreciate, thanks for sending it!) I just meant that I was being lazy - it’s quicker for me to hack a workaround here than review a PR !
