### ISSUE TITLE
[Feature Request]: Filter on test name when debugging with delve

### ISSUE THREAD

**Issue by mozey** [puremourning/vimspector#430]
**Is your feature request related to a problem? Please describe.**

This `.vimspector.json` config
```
"run_test": {
    "adapter": "vscode-go",
    "default": true,
    "configuration": {
        "request": "launch",
        "program": "${workspaceRoot}/${relativeFile}",
        "mode": "test",
        "dlvToolPath": "$HOME/go/bin/dlv",
        "trace": true
    }
}
```

will make delve run all the tests in a test file, similar to this command
```
dlv test ./pkg/foo/foo_test.go
```

It is possible to filter by test name, see [debugging tests with delve](https://stackoverflow.com/a/43403880/639133), for example...
```
dlv test --build-flags='github.com/foo/pkg/foo' -- -test.run ^TestA
```

...will run `TestA1` and `TestA2`, but not `TestB`

**Describe the solution you'd like**

It would be useful to specify a `${testPrefix}` variable to filter tests.

**Describe alternatives you've considered**

I tried the following config, but got and error: program must match a dir or file?
```
"program": "--build-flags='${testPkg}' -- -test.run ^${testPrefix}"
```

It would also be useful if `${testPkg}` could be constructed from [predefined variables](https://puremourning.github.io/vimspector/configuration.html#predefined-variables), something like
```
${goModule}/${relativeFileDirname}
```

**Comment by puremourning** [comment]
> It would be useful to specify a ${testPrefix} variable to filter tests.


you can do this. You have to write the code yourself though and call the documented API. I’m not going to write a ton of language-specific parsing stuff in vimspector.  I neither have the capacity not inclination to do that - it’s basically a job for life. 

But it’s totally possible. here’s an example that I use https://github.com/puremourning/.vim-mac/blob/master/ftplugin/python.vim#L87
