### ISSUE TITLE
[Feature Request]: Hot reloading within flutter/dart debugging

### ISSUE THREAD

**Issue by joshpetit** [puremourning/vimspector#434]
Thanks a lot for this plugin in general, it's saved developers around the world thousands of hours and countless sleepless nights :)
 
**Is your feature request related to a problem? Please describe.**
Being able to reload a flutter or dart app while debugging would be great, I mentioned it in #4  [here](https://github.com/puremourning/vimspector/issues/4#issuecomment-851492823)

**Describe the solution you'd like**
Being able to enable hot reload on save for a dart/flutter debugging session or reload from the REPL

**Describe alternatives you've considered**
I've tried setting fields within the configuration that [mirror](https://dartcode.org/docs/settings/#dartflutterhotreloadonsave) the options supported by dart code, but haven't had any luck with it working.

**Comment by puremourning** [comment]
So far as I can tel this is not possible. There is no DAP api for hot code reload and it looks like the dart vscode extension handles this client side (somehow). 

I’m not willing to write complex client side or server/language specific features in vimspector m, I simply do not have the bandwidth.

**Comment by puremourning** [comment]
FWIW if someone from the community can find evidence that there is a documented and supported API for this from the server, then we can revisit this/re-open. We do support this for java which has a very simple dap extension, which is about the absolute limit I am willing to consider.

**Comment by joshpetit** [comment]
@puremourning, ok I hear. Thanks for your time!
