### ISSUE TITLE
[Feature Request]: Add GDB Command Window

### ISSUE THREAD

**Issue by gergap** [puremourning/vimspector#439]
VimSpector has the best debugger integration for Vim I know, but ...

**Is your feature request related to a problem? Please describe.**
When debugging, it is essential to have the gdb commands available with tab completion (e.g. like in cgdb).
* This way you can easily set breakpoints for functions (or `<file>:<line>`) without opening the source file and navigating to the function, e.g.  `gdb> break functionname`.
* conditional breakpoints
* hardware watchpoints
* breakpoint actions
* reverse debugging
* memory dump
* ... all GDB has to offer

**Describe the solution you'd like**
Having a pane at the bottom in Vim where I can enter GDB commands.

**Describe alternatives you've considered**
Using cgdb instead using this plugin: https://github.com/gergap/vim-cmake-build
It allows setting breakpoints in vim and invoke cgdb for debugging.
Breakpoints are synced back and forth between cgdb and vim.

**Additional context**
VimSpector has nice watch window and local variable window and integrates well into vim.
Cgdb offers all GDB features without any limitations.
If VimSpector would offer the same, it would be the best solution.

**Comment by mark2185** [comment]
> **Describe the solution you'd like**
> Having a pane at the bottom in Vim where I can enter GDB commands.

But that already exists? The `Console` window at the bottom? Docs - https://github.com/puremourning/vimspector#console

**Comment by puremourning** [comment]
Duplicates:

https://github.com/puremourning/vimspector/issues/323
https://github.com/puremourning/vimspector/issues/52

Explanations there why this isn't completely possible, limited by DAP. 

CodeLLDB allows you to enter any arbitrary lldb command, and vscode-cpptool allow you to use `-exec` as a prefix to run gdb commands directly via MI.

**Comment by gergap** [comment]
Yes, in the console window, I can do `-exec break my_cool_function`. More precisely, I need to type  `i-exec break my_cool_function<cr>`. This is better than nothing. But this is not like a gdb window with TAB completion.

In GDB commandline I would type `b my_c<tab><cr>`.
A GDB commandline is comfortable to use, e.g. you can type `until<cr>`, or the abbreviation `u<cr>` and repeat the last command by pressing `<cr>`.

Also, if I add breakpoints in GDB, they don't get synced back to Vim but they work.
I would say the current console window is a suboptimal solution.
IMO this means you need real terminal window, not a vim buffer.

I don't know how other debuggers like KDevelop or cgdb handle this. Either GDB MI protocol allows this or they use simple CLI.
I understand that you want to go through DAP to be independent of GDB. Maybe DAP can be extended to allow command execution with completion support.

**Comment by puremourning** [comment]
vimspector is a DAP client. Anything else is out of scope.

**Comment by gergap** [comment]
lldb works better as you said: `b functioname`.
Thx for your help.
