### ISSUE TITLE
[Feature request] update netcoredbg gadget to support exceptions

### ISSUE THREAD

**Issue by sebaFlame** [puremourning/vimspector#448]
netcoredbg recently added exceptionBreakpointFilters support: [netcoredbg commit](https://github.com/Samsung/netcoredbg/commit/0eb46078b47ba31a04269fcc8e19b42081cc0267#diff-a684d655a34a4b8582e4d8cc1a0b4944c66b260e587dd8ac68ff0ecd0613169d)

this should be available in 1.2.0-825
Unfortunately it doesn't seem to be a drop-in replacement, it breaks breakpoints and I can not configure exceptions filters.

**Comment by puremourning** [comment]
If netcoredbg has regressed, then I'm not going to update to a version that's broken. Maybe report the regression to them ?

**Comment by sebaFlame** [comment]
There is also the issue of the exception filters not being sent. From what I understand so far, the filters should get sent when a breakpoint gets set?

.vimspector.json
`{
  "adapters": {
    "netcoredbg-debug": {
      "attach": {
        "pidProperty": "processId",
        "pidSelect": "ask"
      },
      "command": [
        "${gadgetDir}/netcoredbg/netcoredbg",
        "--interpreter=vscode",
        "--engineLogging=${workspaceRoot}/netcoredbg.engine.log",
        "--log=${workspaceRoot}/netcoredbg.log"
      ],
      "configuration": {
        "cwd": "${workspaceRoot}"
      },
      "name": "netcoredbg-debug"
    }
  },
  "configurations": {
    "test - netcoredbg": {
      "adapter": "netcoredbg-debug",
      "breakpoints": {
        "exception": {
            "unhandled": "Y",
            "user-unhandled": "Y",
            "throw": "Y",
            "all": "N"
        }
      },
      "configuration": {
        "request": "attach",
	  }
    }
  }
}`

"all" & "user-handled" are supported

Log for 1.2.0-782 - 
[_vimspector_log_Vimspector_782.log](https://github.com/puremourning/vimspector/files/7127981/_vimspector_log_Vimspector_782.log)
Log for 1.2.0-825 -
[_vimspector_log_Vimspector_825.log](https://github.com/puremourning/vimspector/files/7127984/_vimspector_log_Vimspector_825.log)

**Comment by puremourning** [comment]
hmm. That does seem odd.

Let me try it out.

**Comment by puremourning** [comment]
OK actually I can't. There's another reason we can't move to this version - no macOS binary.

**Comment by puremourning** [comment]
https://github.com/Samsung/netcoredbg/issues/66

**Comment by sebaFlame** [comment]
Apparently (https://github.com/Samsung/netcoredbg/issues/65#issuecomment-923878953) it Just Works™. Using the new https://github.com/Samsung/netcoredbg/releases/download/1.2.0-825/netcoredbg-linux-amd64_fixed.tar.gz @viewizard provided. I seem to be hitting a corner case with the way I'm debugging tests. Exception filters still do not get sent tho.

**Comment by puremourning** [comment]
feel free to use the latest build that works on linux, but I won't be updating vimsepctor while there are known issues and missing platform support. Other clients are also hitting issues : https://github.com/sar/free-omnisharp-vscode-LTS/issues/3
