### ISSUE TITLE
Can we provide aarch64 version CodeLLDB to support Mac M1

### ISSUE THREAD

**Issue by hanleylee** [puremourning/vimspector#451]
I found we only provide `codelldb-x86_64-darwin.vsix`  for Mac user.

<https://github.com/puremourning/vimspector/blob/b4bcfca932aec55d71c8e0607017959d398a5c44/python3/vimspector/gadgets.py#L389-L409>

Actually, `vscode-lldb` has released `codelldb-aarch64-darwin.vsix` for Mac with M1 chip, see here <https://github.com/vadimcn/vscode-lldb/releases/tag/v1.6.5>

So, I think it a good idea to provide `aarch64` version codelldb for people who use a Mac with M1 chip.

**Comment by puremourning** [comment]
duplicate #224
