### ISSUE TITLE
[Feature Request]: Remote debug for CodeLLDB

### ISSUE THREAD

**Issue by zoumi** [puremourning/vimspector#461]
**Is your feature request related to a problem? Please describe.**
According to https://github.com/vadimcn/vscode-lldb/blob/master/MANUAL.md#remote-debugging
CodeLLDB has the support for remote debug.

But when  I launch vimspector  I got an error.
```json
{
  "configurations": {
    "CodeLLDB": {
      "adapter": "CodeLLDB",
      "configuration": {
        "request": "custom",
        "targetCreateCommands": ["target create ${workspaceFolder}/test.exe"],
        "processCreateCommands": ["gdb-remote 127.0.0.1:5645"]
      }
    }
}
```

Error:
```
Launch Failed
Internal debugger error: Not implemented.
```

**Comment by puremourning** [comment]
There is nothing to implement here. Remote debugging is already supported.

**Comment by puremourning** [comment]
request: custom is not valid in the real world
this is what the codelldb extension does: https://github.com/vadimcn/vscode-lldb/blob/master/extension/main.ts#L379-L383

i.e. use request: 'launch', custom: true, as in:

```json
{
  "configurations": {
    "CodeLLDB": {
      "adapter": "CodeLLDB",
      "configuration": {
        "request": "launch",
        "custom": true,
        "targetCreateCommands": ["target create ${workspaceFolder}/test.exe"],
        "processCreateCommands": ["gdb-remote 127.0.0.1:5645"]
      }
    }
}
```
