### ISSUE TITLE
[Feature Request]: Reload .vimspector.json

### ISSUE THREAD

**Issue by jackhub** [puremourning/vimspector#474]
When debugging, I often need to update the configuration file for different "program", like this:

`            "configuration": {
                "request": "launch",
                "program": "build/samples/attach/sample_attach"
            }
`

I found there is no way to reload .vimspector.json file.
Please help to support this feature, thanks.

**Comment by puremourning** [comment]
I think it is because you are using "restart" rather than "launch"

If you "restart", vimspector re-uses the original launch config. To use new config, you need to use Launch
