### ISSUE TITLE
[Feature Request]: Truncate large arrays in variable window

### ISSUE THREAD

**Issue by Thieso** [puremourning/vimspector#487]
**Is your feature request related to a problem? Please describe.**
I work a lot with large matrices and in the vimspector variables window, the array is shown completely which clutters the window a lot and makes it very uncomfortable to use it. 

See also the screenshot below. 

**Describe the solution you'd like**
I would like the matrices in the variable window to be truncated and only show them when I expand the variable since then I want to see it. 
So maybe only show the first and last row or limit the amount of lines a variable preview can take. 

**Describe alternatives you've considered**
I have not considered any alternatives yet.

**Additional context**
Screenshot of variables window in vimspector showing a large matrix. 
![2021-11-10_12-26](https://user-images.githubusercontent.com/15210390/141104890-982c47b8-e2c1-46e7-a1ac-f8064039abf4.png)

The example uses python with debugpy. So I am not sure whether the problem exists in other programming languages or debug adapters as well. 

I hope my idea is clear and thanks for creating this great plugin.

**Comment by puremourning** [comment]
do you have some minimal example code that I can use to repro the behaviour you're seeing from debugpy?

It's tricky to know what to do about this. I mean I could just truncated the text.. or just display the first line unless the variable is expanded.

Though I actually have use cases where a _want_ the multi-line value as it turns out to be very useful for me. hmm;

**Comment by Thieso** [comment]
Hi, 
sadly I use `nvim-dap` now but I guess you can use this code snippet 

```
import numpy as np

big_matrix = np.random.standard_normal(size=(100, 100))
```

Maybe it would be possible to use an optional truncation of the arrays in the variables window. Or show them up to a certain size and if they are bigger only show the first line?

**Comment by puremourning** [comment]
Don't be sad! I'm sure vim-dap is fine :D

Thanks for the snippet, I'll try it out. I was thinking something like the later idea. I'd like to avoid options for this sort of thing. Too fiddly.

**Comment by puremourning** [comment]
Unfortunately,, the 1.7.0 version has a _massive_ regression in signature help that breaks our tests. 

<img width="578" alt="Screenshot 2021-12-20 at 10 47 34" src="https://user-images.githubusercontent.com/10584846/146755439-9384705b-4f3d-471c-82eb-b82d972894f7.png">

However, I think that jdt.ls doesn't actually use log4l so perhaps it's not really affected.

**Comment by puremourning** [comment]
raised https://github.com/eclipse/eclipse.jdt.ls/issues/1980

**Comment by puremourning** [comment]
these messages were clearly on the wrong thread, Ben.
