### ISSUE TITLE
[Feature Request]: Visual Studio Debugger Support

### ISSUE THREAD

**Issue by sam20908** [puremourning/vimspector#493]
**Is your feature request related to a problem? Please describe.**
VSCode uses VS debugger when `type` is set to `cppvsdbg`, I set that as the type and it still attempted to read `MIDebuggerPath`. Switching compilers wasn't an option for me either.

**Describe the solution you'd like**
Use the VS debugger when `type` is set to `cppvsdbg`.

**Describe alternatives you've considered**

**Additional context**

**Comment by puremourning** [comment]
Sorry, this is impossible.

It's not possible to use the visual studio debugger outside of vscode; it's proprietary licensed software. Only the OSS MIdebugger is available outside of ms products.
