### ISSUE TITLE
[Feature Request]: Determine ${workspaceRoot} based on the location of the directory .git

### ISSUE THREAD

**Issue by Zeioth** [puremourning/vimspector#495]
**Is your feature request related to a problem? Please describe.**
Currently, in order to tell vimspector what's the main directory of the project, a .vimspector file must be created. This should be unnecesary if we already have vimspector-config/os/filetype/*.json

**Describe the solution you'd like**
By default vimspector set the value of ${workspaceRoot} based on the location of the first .git directory found going up from the current file's location, if any.

**Describe alternatives you've considered**
Make this behavior optional by adding an option, in case this shouldn't be the default behavior.

**Comment by puremourning** [comment]
The problem I have with this is where does it stop?

* .git directory
* p4 client -o
* mercurial whatsit 
* Search for a Makefile
* Etc
* Etc

fijd Ing the canonical root of a ‘project’ is an entire plugin and ecosystem of its own. I’m not going to build all of that into vimspector. 

What I could do is check for a b:vimspector_project_root which you can set on BufLoad or something. Would that work?

**Comment by puremourning** [comment]
I think this is out of scope for vimspector. you don't have to use `${workspaceRoot}`, you can use anything
