### ISSUE TITLE
How can I disable the cursor hover evaluation information？

### ISSUE THREAD

**Issue by 0BananaBig0** [puremourning/vimspector#496]
How can I disable the cursor hover evaluation information？

**Comment by puremourning** [comment]
There's no trivial way, but maybe you can unset balooneval using one of the User autocommands that Vimspector provides.

In future, please carefully read CONTRIBUTING.md.

**Comment by Banana-Two** [comment]
@puremourning Ok. Thanks very much.

**Comment by puremourning** [comment]
More people have requested this since, so re-opening.
