### ISSUE TITLE
Opening a Python file in an Anaconda environment with a specific Python version, but debugging said file with Vimspector uses a different version

### ISSUE THREAD

**Issue by olliequ** [puremourning/vimspector#497]
### Describe the bug

Following on from the title -- When I run the file in nvim, the line `print(sys.version)` it gives v3.6, the version of Python specified when I set up the anaconda environment. Great. However, when I run vimspector on the file it prints v3.9 -- it's clear vimspector is not using the anaconda environment's Python version (?). 

Is there somewhere in vimspector settings I can tell it to use the Python version in the environment? I checked out my `.vimspector.json` but doesn't seem like I can do this there. This is my `.vimspector.json`:

```
{
    "configurations": {
     "run": {
      "adapter": "debugpy",
      "configuration": {
        "request": "launch",
        "type": "python",
        "cwd": "${workspaceRoot}",
        "program": "${file}",
        "stopOnEntry": false,
        "console": "integratedTerminal"
      },
      "breakpoints": {
        "exception": {
          "raised": "N",
          "uncaught": "",
          "userUnhandled": ""
        }
      }
    }
  }
}
```

### Minimal reproduciton

_Described above_.

> Please answer the following questions

* Does your issue reproduce using `vim --clean -Nu /path/to/vimspector/support/minimal_vimrc` ? \[Yes/No]
* If you are using Neovim, does your issue reproduce using Vim? \[Yes/No]

> List of steps to reproduce:

> 1. Run `vim ---clean Nu /path/to/vimspector/support/minimal_vimrc`
> 2. Open _this project_...
> 3. Press _this sequence of keys_

> Use the following Vimspector config file:

```
paste .vimspector.json here
```

### Expected behaviour

> Provide A clear and concise description of what you expected to happen.

### Actual behaviour

> What actually happened, including output, log files etc.

> Please include:
> * Vimspector log (~/.vimspector.log)
> * Output from any or all UI diagnostic tabs (Server, etc.)

### Environemnt

***NOTE***: NeoVim is supported only on a best-effort basis. Please check the README
for limitations of neovim. Don't be offended if I ask you to reproduce issues in
Vim.

***NOTE***: Windows support is experimental and best-efrort only. If you find an
issue related to Windows or windows-isms, consider sending a PR or
discussing on Gitter rather than raising an issue.

* Version of Vimspector: (e.g. output of `git rev-parse HEAD` if cloned or the
  name of the tarball used to install otherwise)

* Output of `:VimspectorDebugInfo`

```
paste here
```

* Output of `vim --version` or `nvim --version`

```
paste here
```

* Output of `which vim` or `which nvim`:

```
paste here
```

* Output of `:py3 print( __import__( 'sys' ).version )`:

```
paste here
```

* Output of `:py3 import vim`:

```
paste here
```

* Output of `:py3 import vimspector`:

```
paste here
```

* For neovim: output of `:checkhealth`

```
paste here
```

* Operating system: <linux or macOS> and version
  
### Declaration

> Please complete the following declaration. If this declaration is not completed, your issue may be closed without comment.

* I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md) \[Yes/No]

**Comment by puremourning** [comment]
Please see https://github.com/puremourning/vimspector#python

The python that debugpy uses to run your app is controlled by the `python` configuration option (documented here: https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings).

As you did not complete the issue template, I am closing this.

**Comment by olliequ** [comment]
@puremourning  Thanks for the reply.

> The python that debugpy uses to run your app is controlled by the python configuration option (documented here: https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings).

The python version to be used by vimspector, ideally, would be the one specified by the given environment I've entered. So, for example in my current environment (which I've called `cs188`) the python executable has this path: /Users/Ollie/opt/anaconda3/envs/cs188/bin/python3

Where do I specify this? And how? Is it in the `.vimspector.json` file? :)

**Comment by puremourning** [comment]
I have literally passed you the documentation that answers your question.

**Comment by olliequ** [comment]
@puremourning  I'm sorry. The truth is I am nvim noob and it's very overwhelming. 

Currently, as above, in my `.vimspector.json`,  in the "configuration" block I have `"type": "python"` -- as you saying I remove this and replace it with `"python": "python"`?

I notice the documentation you handed me says:
> Path python executable and interpreter arguments. Example: "python": ["/usr/bin/python", "-E"], For arguments to your script use "args".
So wouldn't I somewhere in `"python": "python"` have an argument representing the python version that the current environment has (as different envs can use different python versions)?

**Comment by puremourning** [comment]
```

    "configurations": {
     "run": {
      "adapter": "debugpy",
      "configuration": {
        "request": "launch",
        "type": "python",
        "cwd": "${workspaceRoot}",
        "program": "${file}",
        "stopOnEntry": false,
        "python": "python", // add this line, change the value to a specific path if you want to.
        "console": "integratedTerminal"
      },
      "breakpoints": {
        "exception": {
          "raised": "N",
          "uncaught": "",
          "userUnhandled": ""
        }
      }
    }
  }
}
```

**Comment by olliequ** [comment]
@puremourning Thanks a lot, I used `"python": "/Users/Ollie/opt/anaconda3/envs/cs188/bin/python3",` and it worked :)

How do I use the args feature specified in the documentation, so that if I copied this json and pasted it in a seperate directory whereby I use a separate anaconda environment for that, that vimspector would launch with that specific python version?

I imagine it's something like:  `"python": "/Users/Ollie/opt/anaconda3/envs/<env_name_here>/bin/python3", envname`

Not sure :S Looks messy. I guess this might not work because it would require vimspector is somehow identify the environment's Python version.

**Comment by puremourning** [comment]
The issue tracker is not for support, it's for bugs and feature requests.

This explains how to parameterise your config: https://puremourning.github.io/vimspector/configuration.html#replacements-and-variables

You could just put `${env_name}` and vimspector would prompt you to enter it.

**Comment by olliequ** [comment]
Ok, I'll stop querying. Thank you for your help. In future, for support, do I head to the `Discussions` tab on this repo?

**Comment by puremourning** [comment]
You should have seen this when you clicked "New Issue"

![Screenshot 2021-12-15 at 16 52 24](https://user-images.githubusercontent.com/10584846/146229571-4a30b196-263c-4682-9702-3ea258a793d0.png)

**Comment by olliequ** [comment]
Ok cool, thanks! Sorry for clicking the wrong thing.

**Comment by puremourning** [comment]
Btw, I often use this when working with virtual env, you may be able to make it work for anaconda (which I've never used):

```json

    "python - launch pytest": {
      "adapter": "debugpy",
      "variables": [
        {
          "python": {
            "shell": "/bin/bash -c 'if [ -z \"${dollar}VIRTUAL_ENV\" ]; then echo $$(which python3); else echo \"${dollar}VIRTUAL_ENV/bin/python\"; fi'"
          }
        },
      ],
      "configuration": {
        "python": "${python}",

```
