### ISSUE TITLE
[Feature Request]: Memory display

### ISSUE THREAD

**Issue by puremourning** [puremourning/vimspector#498]
We should support the dap `showMemory` request.

There's a wip implementation of this in the "memory" branch.

Currently this is blocked by not having a good idea for how to do this in the UI.

Currently:

- It takes over the code window by opening a temp file and populating it with the hex dump
- it asks the user for an offset, which is kinda annoying. There's no scrolling or anything like that
- other faff, it's just a prototype.

We need to work out a good UI for it.

**Comment by mark2185** [comment]
Dumping raw binary to a file would be useful.

And "i could even hook things like :w on the buffer that contains the hexdump"
