### ISSUE TITLE
Vimspector show blank splits while debugging lua

### ISSUE THREAD

**Issue by john-front** [puremourning/vimspector#503]
Steps to replicate issue:
- Install vimspector
- Install lua adaptor using: VimspectorInstall local-lua-debugger-vscode
- copy files from: vimspector/support/test/lua/simple/
- Go to simple.lua that you just copied, add breakpoints and run vimspector
- Vimspector will run and show the split windows but everything blank
- It wont stop at the breakpoint either.
- I tried this on fresh nvim installation 0.5v

**Comment by puremourning** [comment]
Please complete the full issue template
