### ISSUE TITLE
Go Delve dap `stdout` not visible

### ISSUE THREAD

**Issue by clementnuss** [puremourning/vimspector#504]
### Describe the bug

Thanks for solving #186, it works well! except for one thing: the `stdout` (and `stderr`) of the program I try to debug are visible nowhere. (I tried `VimspectorToggleLog` but there was nothing related to the output of the program).

It seems other projects are having the same issue: https://giters.com/mfussenegger/nvim-dap/issues/232
Aparrently `dlv dap` is printing stdout/stderr to its own process instead of redirecting it with DAP.
are you aware of that situtation, and if yes, do you have an idea for a workaround ?

### Minimal reproduciton

* Does your issue reproduce using `vim --clean -Nu /path/to/vimspector/support/minimal_vimrc` ? \[Yes]
* If you are using Neovim, does your issue reproduce using Vim? \[Yes]

> List of steps to reproduce:

> 1. Run `vim ---clean Nu /path/to/vimspector/support/minimal_vimrc`
> 2. Open any project that outputs something to stdout
> 3. Start debugging and observe an empty `console`

> Use the following Vimspector config file:

```json
{
  "configurations": {
    "run": {
      "adapter": "delve",
      "filetypes": ["go"],
      "variables": {
        "dlvFlags": "--check-go-version=false --log"
      },
      "configuration": {
        "request": "launch",
        "program": "${fileDirname}",
        "mode": "test"
      }
    }
  }
}
```

### Expected behaviour

The stdout should be printed out to the console view in debugging mode, but it isn't.

  
### Declaration

> Please complete the following declaration. If this declaration is not completed, your issue may be closed without comment.

* I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md) \[Yes]

**Comment by puremourning** [comment]
Sorry this took so long. Thanks for the report btw.

This should be resolved now; you should get a terminal window with delve in in. Delve uses its controlling tty for the debugee so both stdin and stdout should work in that terminal window.
