### ISSUE TITLE
What can I do to make variables look more readable? Like vector and map

### ISSUE THREAD

**Issue by Banana-Two** [puremourning/vimspector#511]
_nameMap is a std::map<std::string, int> variable, I want to know about its key:values. But when I use evaluation function of vimspector, it gives me the following result.
![image](https://user-images.githubusercontent.com/62785154/148318826-fd5634fe-fa69-461a-8774-34b1415b6663.png)
I can't get any useful information from it.
What can I do to make the result of evaluation of vimspector like the following picture which I get from gdbgui. 
![image](https://user-images.githubusercontent.com/62785154/148319565-cf02abec-a779-400a-b2c8-3ebbcde87245.png)

**Comment by puremourning** [comment]
Please do not delete the issue template. 

Please use the correct forums for user questions. 

https://github.com/puremourning/vimspector#data-visualization--pretty-printing

**Comment by Banana-Two** [comment]
@puremourning 
Ok. Thanks very much.
