### ISSUE TITLE
[Feature Request]: Make debug adapter timeouts configurable

### ISSUE THREAD

**Issue by gagara** [puremourning/vimspector#525]
**Is your feature request related to a problem? Please describe.**
Sometimes, when debugging remote java app (which can be behind firewall/VPN/slow network) debug adapter requests fails with timeouts.

**Describe the solution you'd like**
It can be fixed by making timeouts on debug adapter configurable, thus you can increase them when needed.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by puremourning** [comment]
There’s already a timeout you can set on the remote config. Which can be made parametric just like anything else.

**Comment by puremourning** [comment]
Search for ‘delay’ on here https://puremourning.github.io/vimspector/configuration.html

**Comment by gagara** [comment]
That's not what I meant.
I was talking about this value https://github.com/puremourning/vimspector/blob/master/python3/vimspector/debug_adapter_connection.py#L47
In most cases default value is used. And there is no way to configure it (at least I don't see how).

**Comment by puremourning** [comment]
You're saying some requests take 15 seconds  to get a response?

**Comment by gagara** [comment]
Yes. sometimes request takes >15 sec when remote app is too slow or it is too "far away"

**Comment by puremourning** [comment]
are you sure? are have you checked the logs to see how long it actually takes for the request to come back? i.e. it seems more likely that there is another issue at play for which an issue report might be a better vehicle to investigate (as it contains all the relevant diagnostics).

**Comment by gagara** [comment]
Yes, I used logs to troubleshoot.
In according to the logs after some request made in 15 sec I get "timeout" error message, then in e.g. 10 sec I see correct response is arrived with respective `seq` number. But it is ignored by debug adapter.
Additionally if I increase that `timeout` value in the code then debug works fine.
One more point: I observe the same slowness when I debug same app with Eclipse remote debug. Thus I don't think that this is the issue with vimspector itself of gadget it uses, but network or remote app issue.

**Comment by puremourning** [comment]
ok thanks for sharing that detail.

**Comment by puremourning** [comment]
As this is likely to be an extremely rare exception case, I would consider a PR with an undocumented switch for this in settings.py

**Comment by puremourning** [comment]
Can you try PR #526 ?

**Comment by gagara** [comment]
Works for me.
This is exactly what I need.
Thanks a lot.
