### ISSUE TITLE
Remote SSH command fails with incorrect syntax when optional user information is not provided

### ISSUE THREAD

**Issue by chrisdonlan** [puremourning/vimspector#527]
### Description
**FYI: 
During the compilation of this bug report, I moved `.vimspector.log` from its install location. The toggle log function does not touch the file prior to the call to tail, and fails.** 

Error message:

```
subprocess.CalledProcessError: Command '['ssh', '@ml1', '/path/to/secret/script/GetPIDForService', '']' returned non-zero exit status 255.
```

Error message summary:

```
# the following command is not a correct ssh call:
ssh @ml1
```

The situation: user account information is configured in `ssh` configuration file and is unnecessary. `ssh ml1` would have logged in correctly. The account was not provided in the set up. The configuration used is the `python3` remote debug configuration found [here](https://puremourning.github.io/vimspector/configuration.html#python-debugpy-example). 

### Works in vim?

Reproducable in Vim

### Works with clean config?

Yes

### Minimal Reproduction

List of steps to reproduce:

1. Run `vim ---clean Nu /path/to/vimspector/support/minimal_vimrc`
2. Open _this project_...
3. `:let g:vimspector_enable_mappings = 'HUMAN'`
4. <F5>
5. input ssh args related to this connection

### Expected Behaviour

Attaches to the pre-existing `debug-py` service I manually started (I have not gotten the process to initialize via the example configuration yet). 

### Actual Behaviour

```
subprocess.CalledProcessError: Command '['ssh', '@ml1', '/path/to/secret/script/GetPIDForService', '']' returned non-zero exit status 255.
```

-- an incorrect ssh command is generated when the optional account information is not provided as an argument.

### Installation Type

Vim packages (git clone)

### Vimspector version

63c14e410e347d375e584a3b8b2ec25ab03ab07f

### Debug Info

```Text
emits: "Vimspector not connected, start a debug session first"
```

### Log file

```Text
Log is blank.
```

### Vim version

```Text
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 15 2022 18:31:43)
```

### Python version

3.9.10

### Neovim diagnostics

```Text
NA
```

### Operating System

Mac OS: 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by puremourning** [comment]
> when the optional account information is not provided as an argument

When using ssh for remote debugging, both user and host are currently required.

Can you not just put 

```
 "variables": { "remoteUser": "the_user_name" }
```

in your config?

I mean we could change vimspector to not require the username, but that should work for a workaround.

**Comment by puremourning** [comment]
Wait, I just looked at the code and `account` is optional in the `remote` block, so just remove `account` from your `remote` block:

```
  def _GetSSHCommand( self, remote ):
    ssh = [ 'ssh' ] + remote.get( 'ssh', {} ).get( 'args', [] )
    if 'account' in remote:
      ssh.append( remote[ 'account' ] + '@' + remote[ 'host' ] )
    else:
      ssh.append( remote[ 'host' ] )

    return ssh

```

**Comment by chrisdonlan** [comment]
@puremourning ah -- I misunderstood the meaning of "optional"; figured I could leave the argument blank.
