### ISSUE TITLE
[Feature Request]: Why are all of those questions when starting a debug session?

### ISSUE THREAD

**Issue by doronbehar** [puremourning/vimspector#53]
So today, when I've started my first ever debug session I was asked:

```
Enable exception filter 'Raised Exceptions'? (Y/N)
Enable exception filter 'Uncaught Exceptions'? (Y/N)
When to break on exception?
1: never
2: always
3: unhandled
4: userHandled
Type number and <Enter> or click with mouse (empty cancels):
```

And only then the debugging has started. Is it possible to make give these answers default answers for the whole project / adapter / all adapters? Say I don't understand what are these questions all about, where could I find a documentation for it?

**Comment by puremourning** [comment]
It’s a bit of a hack to be honest. 

Basically the way DAP is designed makes some assumptions about what UI you have available. I don’t have a UI for the ‘exception breakpoint’ configuration Yet but it’s useful enough that I threw that in so it could be used. Certainly improving this is on the backlog. 

Basically the debug server is asking if you want to break on exceptions. I didn’t make a UI for that yet so it just asks you every time. Usually the defaults are fine and you can just press enter. Rememberinf choices is also on the backlog. 

Each adapter can have different options so I can’t doc them.

**Comment by doronbehar** [comment]
> I don’t have a UI for the ‘exception breakpoint’ configuration [...]

Ideally, I wouldn't expect a UI for configuring these exception options. I'd expect to be able to set them in `.vimspector.json` for every launcher configuration and to be able to set defaults per adapter in (e.g) `~/.config/nvim/vimspector.json`. Only if none of these will be set, I'd like to be asked and even then not every time.

Maybe the last part of this UX suggestion will be a little bit harder to implement, but I think being able to set defaults in a global / project / launcher configuration would be nice.

**Comment by puremourning** [comment]
> I'd expect to be able to set them in .vimspector.json for every launcher configuration

This might be possible, though the available options are defined as [capabilities returned on the initialize request](https://microsoft.github.io/debug-adapter-protocol/specification#Types_ExceptionBreakpointsFilter) so I don't know for certain how users could know what to configure in advance.

Feel free to have a read of the protocol and propose something :)

> Only if none of these will be set, I'd like to be asked and even then not every time.

yeah like I said, remembering the user's response is on my mental backlog. it's not that hard to do, just requires some code and tests. well, like everything else I suppose.

**Comment by puremourning** [comment]
I was wondering what we did in the tests.

:')

```python
  pyx << EOF
from unittest.mock import patch
with patch( 'vimspector.utils.SelectFromList',
            return_value=None ) as p:
  with patch( 'vimspector.utils.AskForInput',
              return_value=None ) as p:
    vim.eval( 'feedkeys( "\<F5>", "xt" )' )
    vim.eval( 'vimspector#test#signs#AssertCursorIsAtLineInBuffer( fn, 6, 1 )' )
    p.assert_called()
EOF
```

**Comment by doronbehar** [comment]
You are an impressive FOSS writer @puremourning. I've checked out the latest changes and it certainly feels much smoother now.

However, I do get now occasionally errors about an attribute named `DoRequest` missing to `self._connection`. E.g:

```
Error detected while processing function <SNR>220__OnServerData:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/doron/.vim/pack/functional/start/vimspector/python3/vimspector/debug_session.py", line 242, in OnChannelData
    self._connection.OnData( data )
  File "/home/doron/.vim/pack/functional/start/vimspector/python3/vimspector/debug_adapter_connection.py", line 131, in OnData
    self._ReadBody()
  File "/home/doron/.vim/pack/functional/start/vimspector/python3/vimspector/debug_adapter_connection.py", line 205, in _ReadBody
    self._OnMessageReceived( message )
  File "/home/doron/.vim/pack/functional/start/vimspector/python3/vimspector/debug_adapter_connection.py", line 249, in _OnMessageReceived
    getattr( self._handler, method )( message )
  File "/home/doron/.vim/pack/functional/start/vimspector/python3/vimspector/debug_session.py", line 712, in OnEvent_initialized
    self._breakpoints.SendBreakpoints( onBreakpointsDone )
  File "/home/doron/.vim/pack/functional/start/vimspector/python3/vimspector/breakpoints.py", line 256, in SendBreakpoints
    self._connection.DoRequest(
AttributeError: 'NoneType' object has no attribute 'DoRequest'
```

They don't seem harmful in anyway, because debugging seems to continue fine as is but it's kind of worrying.

**Comment by puremourning** [comment]
Worrying indeed. Thanks for the stack. Any chance you could raise it as a new issue? It seeeeeeeeems unrelated but could be that this change has supercharged a race condition
