### ISSUE TITLE
[Feature Request]: Option to configure an interpreter for arguments provided in "args": [ "arg-1", "etc."]

### ISSUE THREAD

**Issue by chrisdonlan** [puremourning/vimspector#537]
**Is your feature request related to a problem? Please describe.**
I typically use debuggers at the entry points of code. These are usually CLIs, and I usually write CLIs to be convenient to use from an interpreted command line. The most typical interpreter is BASH. 

With BASH, I can write a program to receive the output of an expression as if it were a file. For example, `foo.py process-foobar-file-list <(find -name '*.foobar')` might be an expression I could write on the command line. 

In a typical debugger, I would have to compose the output of `<(find -name '*.foobar')` into a stand-alone file containing a list, then pass the physical file in to the debug expression. It doesn't seem like there is a need to be this limited with `Vimspector`; instead it looks like it would be easy or at least possible to take it to the next level and have a debug feel exactly similar to the usage environment. 

**Describe the solution you'd like**
Be able to set an interpreter other than 'literal' strings:

```
# by default, the arg interpreter is literal:
"interpretation-style": "default" or "literal"

# optionally, I can set an interpretation style that would process the command in some initial fashion:
"intepretation-style": "bash"
```

That way, I can assemble the exact usage statement in my `vi:Terminal` mode, then copy paste the args as-is into the `.vimspector.json` file:

```
# vi:Terminal
./foo.py process-foobar-file-list <(find -name '*.foobar')

# buffer: .vimspector.json
"program": "${workspaceRoot}/foo.py"
"args":["<(find -name '*.foobar')"]
"interpretation-style": "bash"
```

**Describe alternatives you've considered**
Doing the legwork and adding the files. 

**Additional context**
The **Biggest** impact here is that `.vimspector.json` would have the potential to be the only debug file I'd have to commit, whereas more static debuggers would require me to commit the helper files I create if I want the same debug scenario when moving from computer to computer.

**Comment by puremourning** [comment]
You can use shell variables which run a command and put the result in a variable. 

https://puremourning.github.io/vimspector/configuration.html#replacements-and-variables

I think that does what you need. Otherwise vimspector has no control at all with how the debug adapter executes the debuggee.
