### ISSUE TITLE
[Feature Request]: Configuration setup is not friendly to new dummy users.

### ISSUE THREAD

**Issue by sloppydevil** [puremourning/vimspector#538]
I'm a vim user without debug for a while. One development activity is writing game with vscode, and use chrome for debug.

when I try to setup vim environment, there are too many configuration variable that I need learn and config, which is kinda annoying. This is not the thing for "lazy" coders. 

isn't there a way to create default/template configurations for different patterns? take mine for example, can I only define the port number for chrome debugging? 

Maybe like this: 
1. user cd some directory and enter vim;
2. user trigger vimspector function in command, e.g. : "vimspector create-config";
3. a list show up, and user pick one of them;
4. a default json is created and user continue to edit for specific setups;

thx so much.

**Comment by puremourning** [comment]
Duplicate #270
