### ISSUE TITLE
[Feature Request]: Extended remote support

### ISSUE THREAD

**Issue by T0maas** [puremourning/vimspector#562]
Can you please provide support for extended-remote debugging? This is needed by some target such are stm32 mcus over openocd which require extended remote for reseting target (with only target remote I cannot restart mcu). 
If I put `target extended-remote :3333` in custom commands cannot pause excecution.
Without extended-remote I can not reset mcu and openocd says `Warn : Prefer GDB command "target extended-remote 3333" instead of "target remote 3333"`

**Comment by puremourning** [comment]
i have no idea what this has to do with vimspector.

**Comment by T0maas** [comment]
I am using adapter vscode-cpptools. I am talking about this: https://github.com/microsoft/MIEngine/pull/1115

**Comment by puremourning** [comment]
What exactly do you need vimspector to change ? I don't see what I would need to do other than upgrade the vscode-cpptools version? I can try that I guess.

> e will be supporting extended-remote with a flag useExtendedRemote as defined in https://github.com/microsoft/MIEngine/pull/1260

**Comment by puremourning** [comment]
Unfortunately, it's basically impossible to update vscode-cpptools now because they've stopped producing GitHub releasees and now only use the vscode marketplace, which has no api for downloading the artefacts.
https://github.com/microsoft/vscode-cpptools/issues/4827

**Comment by puremourning** [comment]
good news, the cpptools maintainer pushed the packages to GitHub for us so we can update!

https://github.com/puremourning/vimspector/pull/563

**Comment by puremourning** [comment]
bad news, the new version of vscode-cpptools seems to cause regression test failures: https://github.com/microsoft/vscode-cpptools/issues/9094

**Comment by T0maas** [comment]
Thank you for response. I'm looking forward to them fixing it.

**Comment by puremourning** [comment]
Good news! The latest version fixes the regression in reported and #563 can now merge

**Comment by fbs2016** [comment]
Can't see the new option "useExtendedRemote " in cpptools 1.10.7

**Comment by puremourning** [comment]
What do you mean? And what does it have to do with vimspector?
