### ISSUE TITLE
[Feature Request]: Add support for https://github.com/actboy168/lua-debug

### ISSUE THREAD

**Issue by yoshi1123** [puremourning/vimspector#564]
I would like to know how to get a debugger to work for [https://github.com/sumneko/lua-language-server](https://github.com/sumneko/lua-language-server).

This page has information:
[https://github.com/sumneko/lua-language-server/wiki/Debug](https://github.com/sumneko/lua-language-server/wiki/Debug)

The above page says it works with [https://github.com/actboy168/lua-debug](https://github.com/actboy168/lua-debug).

The page, [https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/](https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/), lists actboy168/lua-debug as a DAP adaptor.

**Comment by puremourning** [comment]
I already have support for Lua using https://github.com/puremourning/vimspector#lua

Vimspector can be made to work with any conforming debug adapter. You can consult https://github.com/puremourning/vimspector/wiki/Additional-Language-Support if you want to try and make a different server work. I'm extremely unlikely to maintain support in vimspector for _two_ adapters for a niche language like lua, sorry.

**Comment by yoshi1123** [comment]
I have been trying to get it to work. The lua-debug repository said that this client lacks variables:

https://github.com/actboy168/lua-debug/issues/165

Is this a client problem or a configuration problem?

**Comment by puremourning** [comment]
You probably need to add all of this crap to your configuration. It’s not a vimspector issue, it’s a config issue. 

https://github.com/actboy168/lua-debug/blob/master/extension/package.json#L500

**Comment by puremourning** [comment]
You should raise an issue on the adapter repo asking them to document their launch parameters.

**Comment by yoshi1123** [comment]
Well to be fair, I think its designed for vscode.

Okay, I got it to work:

.vimspector.json:
```
{
    "$schema": "https://puremourning.github.io/vimspector/schema/vimspector.schema.json#",
    "configurations": {
        "lua-debug": {
            "adapter": "multi-session",
            "breakpoints": {
                "exception": {
                    "runtime": "",
                    "assert": "",
                    "error": "",
                    "syntax": "",
                    "other": "",
                    "lua": "",
                    "assert": "",
                    "native": "",
                    "panic": ""
                }
            },
            "variables": {
                "host": "127.0.0.1",
                "port": 12306
            },
            "configuration": {
                "request": "attach",
                "stopOnEntry": true,
                "outputCapture": ["print", "io.write", "stderr"],
                "configuration": {
                    "variables": {
                        "showIntegerAsHex": false
                    }
                }
            }
        }
    }
}

```


debugger.lua (to be used with require):
```
local function dofile(filename, ...)
    local load = _VERSION == "Lua 5.1" and loadstring or load
    local f = assert(io.open(filename))
    local str = f:read "*a"
    f:close()
    return assert(load(str, "=(debugger.lua)"))(...)
end

local path = "PATH/TO/LUA-DEBUG"
return dofile(path .. "/script/debugger.lua", path)
```

This use this in a lua file to debug that lua file:
```
require "debugger":start "0.0.0.0:12306":event "wait"
```
