### ISSUE TITLE
[Feature Request]: Update to debugpy 1.6 release

### ISSUE THREAD

**Issue by fvdnabee** [puremourning/vimspector#573]
**Is your feature request related to a problem? Please describe.**
With PR #560, vimspector moved to debugpy 1.5.1. Since then debugpy 1.6.0 has been [released](https://github.com/microsoft/debugpy/releases/tag/v1.6.0). Note it dropped support for EOL python versions (specifically 3.6), which might be problematic for some users/projects (e.g. Ubuntu 18.04 users).

**Describe the solution you'd like**
Consider bumping debugpy to 1.6.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by puremourning** [comment]
PR welcome.

**Comment by puremourning** [comment]
actually dropping all py2 and py3.6 support would be a big hit even for me, and there doesn't seem to be much in the release that will change anything in vimspector. 

Users can always install their own debugpy and use that.

**Comment by timsu92** [comment]
@puremourning I'm thinking of creating a new gadget to use the new versions and keep this old version as "debugpy". What's your opinion?

**Comment by puremourning** [comment]
What's new in debugpy that we might need or want?

**Comment by timsu92** [comment]
I'm not sure. However, according to [their release page](https://github.com/microsoft/debugpy/releases), you can see that many things are fixed/improved. Further more, it is still in development. This means that there will be way more fixes/features in the future.

**Comment by timsu92** [comment]
This is solved by ba771eccbb77c16e92b98e3a170208dc89f44a60 right?
Thanks @puremourning !

**Comment by puremourning** [comment]
Yep I guess so.

**Comment by axrt** [comment]
Question, if I may, @puremourning,
Is it still possible to use python3.6 with debugpy-python2 adapter?
When I try to launch a configuration like the following:
`
...
    "Some Run on Python 3.6 that used to work": {
      "adapter": "debugpy-python2",
      "breakpoints": {
        "exception": {
          "caught": "Y",
          "raised": "Y",
          "uncaught": "Y",
          "userUnhandled": "Y"
        }
      },
      "configuration": {
        "args": [
          ...
        ],
        "console": "externalTerminal",
        "cwd": "${workspaceRoot}",
        "debugOptions": [],
        "env": {
          "MODULE_ROOT": "${workspaceRoot}"
        },
        "justMyCode": true,
        "program": "${workspaceRoot}/src/python/file_to_debug.py",
        "python": [
          "${workspaceRoot}/.py3_venv/bin/python"
        ],
        "request": "launch",
        "stopOnEntry": false,
        "type": "python"
      }
    },
...
`
I see that Vimspector attempts to run debugpy 1.6.1 that does not support python3.6.
Kindly advise? 
Thank you!

**Comment by puremourning** [comment]
Ugh. I'm such a muppet. There's a bug with the -python2 adapter. It doesn't work at all :(

Could you please raise a new GitHub issue? 

I may fix it, or just drop the legacy version.  For now I suggest installing debugpy manually and using a custom adapter.

**Comment by timsu92** [comment]
If you could, please don't drop the legacy version as some libs are still in Python2.

**Comment by puremourning** [comment]
Nothing would stop you using the legacy version with 4 lines of json, but I just stop having code to install it for you. I have only a tiny amount of free time and I can't support legacy stuff forever.
