### ISSUE TITLE
Not refresh new source in vimspector

### ISSUE THREAD

**Issue by thanhtai9606** [puremourning/vimspector#582]
### Description

I cannot debugger after change source. Maybe it not clear cache in source. I Use tmux + neovim. Somebody help me please??

### Works in vim?

Only broken in Neovim

### Works with clean config?

No

### Minimal Reproduction

List of steps to reproduce:

1. Run `vim ---clean Nu /path/to/vimspector/support/minimal_vimrc`
2. Open _this project_...
3. Press _this sequence of keys_

### Expected Behaviour

update new source and debug in vimspector

### Actual Behaviour

Not change source in vimspector

### Installation Type

Plugin Manager (git clone)

### Vimspector version

xx

### Vim version

```Text
nVIM v.0.7.0
```

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by puremourning** [comment]
I have no clue what the issue you are reporting is. No steps to repro. No logs. Closing.
