### ISSUE TITLE
g:vimspector_configurations does not work with the default field

### ISSUE THREAD

**Issue by WillDHB** [puremourning/vimspector#587]
### Description

Configuration selection based on the 'default' field does not work correctly with g:vimspector_configurations, seemingly because of the following line:

`      defaults = { n: c for n, c in configurations.items()
                   if c.get( 'default', False ) is True
                   and c.get( 'autoselect', True ) is not False }
`

...specifically, the `is True` part; I am not aware of a way to create an actual bool in vimrc, and so if there are multiple configurations for a filetype, it will always ask which to use (since the closest you can get is a 1 or the str 'true'.  When I removed the `is True` it worked fine.

### Works in vim?

Reproducable in Vim

### Works with clean config?

No

### Minimal Reproduction

This is an issue with the configuration functionality itself.  It does not work with a minimal config.

List of steps to reproduce:

1. Add the following configuration to a vimrc:
`
let g:vimspector_enable_mappings = 'HUMAN'
let g:vimspector_configurations = {
    \ "BasePython": {
        \ "adapter": "debugpy",
        \ "filetypes": [ "python" ],
        \ "configuration": {
            \ "name": "<name>: Launch",
            \ "request": "launch",
            \ "console": "externalTerminal",
        \ },
        \ "breakpoints": {
            \ "exception": {
                \ "raised": "N",
                \ "userUnhandled": "N",
                \ "uncaught": "Y",
            \ }
        \ }
    \ },
    \ "python": {
        \ "extends": "BasePython",
        \ "default": 1,
        \ "autoselect": 1,
        \ "configuration": {
            \ "program": "${file}",
        \ }
    \ },
    \ "pytest": {
        \ "extends": "BasePython",
        \ "configuration": {
            \ "module": "pytest",
        \ }
    \ }
\ }
`
2. Run `vim`
3. Open python file.
4. Press F5.

### Expected Behaviour

The correct configuration should get selected without prompt (it doesn't matter what happens after that).

### Actual Behaviour

The configuration prompt always appears.

### Installation Type

Plugin Manager (git clone)

### Vimspector version

4c693f33e3038c1199e0f2e1045f340339714b60

### Vim version

```Text
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  2 2021 22:11:39)
MS-Windows 32-bit console version
Included patches: 1-2825
Compiled by appveyor@APPVYR-WIN
Huge version without GUI.  Features included (+) or not (-):
+acl                +ex_extra           +multi_lang         +tcl/dyn
+arabic             +extra_search       +mzscheme/dyn       +termguicolors
+autocmd            -farsi              -netbeans_intg      +terminal
+autochdir          +file_in_path       +num64              -termresponse
+autoservername     +find_in_path       +packages           +textobjects
-balloon_eval       +float              +path_extra         +textprop
+balloon_eval_term  +folding            +perl/dyn           -tgetent
-browse             -footer             +persistent_undo    +timers
++builtin_terms     +gettext/dyn        +popupwin           +title
+byte_offset        -hangul_input       -postscript         -toolbar
+channel            +iconv/dyn          +printer            +user_commands
+cindent            +insert_expand      +profile            +vartabs
+clientserver       +ipv6               +python/dyn         +vertsplit
+clipboard          +job                +python3/dyn        +virtualedit
+cmdline_compl      +jumplist           +quickfix           +visual
+cmdline_hist       +keymap             +reltime            +visualextra
+cmdline_info       +lambda             +rightleft          +viminfo
+comments           +langmap            +ruby/dyn           +vreplace
+conceal            +libcall            +scrollbind         +vtp
+cryptv             +linebreak          +signs              +wildignore
+cscope             +lispindent         +smartindent        +wildmenu
+cursorbind         +listcmds           +sound              +windows
+cursorshape        +localmap           +spell              +writebackup
+dialog_con         +lua/dyn            +startuptime        -xfontset
+diff               +menu               +statusline         -xim
+digraphs           +mksession          -sun_workshop       -xpm_w32
-dnd                +modify_fname       +syntax             -xterm_save
-ebcdic             +mouse              +tag_binary         
+emacs_tags         -mouseshape         -tag_old_static     
+eval               +multi_byte_ime/dyn -tag_any_white      
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
Compilation: cl -c /W3 /GF /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND  -DFEAT_JOB_CHANNEL -DFEAT_IPV6      -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /source-charset:utf-8 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG /arch:IA32 /Zl /MT /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python39.dll\" -DFEAT_MZSCHEME -I "C:\Program Files (x86)\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"msvcrt-ruby240.dll\" -DRUBY_VERSION=24 -DFEAT_HUGE /Fd.\ObjCULYHTRZi386/ /Zi
Linking: link  /nologo /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:i386   libcmt.lib  user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python39.lib   "C:\Tcl\lib\tclstub86.lib" winmm.lib WSock32.lib Ws2_32.lib /PDB:vim.pdb -debug
```

### Operating System

Windows-10-10.0.22000-SP0

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by puremourning** [comment]
Does it work if you use `v:true` in vimrc?

**Comment by puremourning** [comment]
I tried it and v:true works.
