### ISSUE TITLE
Again: console and watch completion with coc-nvim

### ISSUE THREAD

**Issue by sloppydevil** [puremourning/vimspector#590]
# Overview
I'm using coc-nvim for completion.
in a brand-new file type, when I mandatorily set that filetype to e.g. typescript, coc-nvim works well for that.
in vimspector chrome debugger console/watch, the filetype is VimspectorPromt.

## Actions and Observed
Set the filetype mandatorily to typescript and the completion won't do with coc-nvim.

## Expected Results
Completion will do as in other user-defined file types even without any LSP.

## Open Idea:
all variables can be displayed correctly in Variables scope, why can't that be taken and serviced for console/watch completion, while all default completion are disabled.

**Comment by puremourning** [comment]
I have no idea what you are asking. 

Vimspector supports omnicomplete on and if your completion system m doesn’t then it is faulty.
