### ISSUE TITLE
[Feature Request]: winbar support for neovim

### ISSUE THREAD

**Issue by nullchilly** [puremourning/vimspector#594]
**Is your feature request related to a problem? Please describe.**
Support for a bar at the top of each window was added in https://github.com/neovim/neovim/pull/18562 along with click support too https://github.com/neovim/neovim/pull/18650

**Describe the solution you'd like**
I will be gone for a while so opened this early before the next neovim release.

**Comment by puremourning** [comment]
Sadly, it looks like neovim have decided to implement a completely incompatible version of the vim feature, so unless someone wants to contribute changes and tests for this, I'm unlikely to spend time on it.

I can't understand why the neovim devs decided to do that, but shrug.

**Comment by puremourning** [comment]
It's not about what's better, it's about what level of hacks I am willing to maintain forever. I don't have tests for neovim, and I already have to maintain complete rewrites of all job control and popup functionality. Now I have to maintain rewrite of the winbar functionality too? ugh... I don't fancy it. Particularly as I use nunmenu, etc. in the output view which will be a pain to do equivalently using this winbar= setting, which requires construction of some complex string rather than a series of commands. 

Anyway like I said, quality community contribution welcome. This particular change has no benefit to me, so I'm not likely to spend my limited free time working on it, sorry.

**Comment by nullchilly** [comment]
I think it will be better than "some complex string" after lua version of this is out.

Have a great day!

**Comment by nullchilly** [comment]
<details><summary>heh</summary>

![image](https://user-images.githubusercontent.com/56817415/170053229-9be16fad-c435-4651-be12-1fca032515b1.png)

**Comment by puremourning** [comment]
let's keep this open in case someone wants to work on it.

**Comment by bfredl** [comment]
> Sadly, it looks like neovim have decided to implement a completely incompatible version of the vim feature, so unless someone wants to contribute changes and tests for this, I'm unlikely to spend time on it.

> I can't understand why the neovim devs decided to do that, but shrug.

@puremourning Partially true :) It is an explicitly stated goal for nvim 0.8 to also support vim8 style WinBar menus. 0.8 is still in development software, some patience might be required before its features are feature complete.

**Comment by UnrealApex** [comment]
@puremourning @bfredl Nvim v0.8.0 just released a few weeks ago with [winbar support](https://github.com/neovim/neovim/releases/tag/v0.8.0). Perhaps this can become a reality now?

**Comment by nullchilly** [comment]
@UnrealApex Did you read the conversation?

The author won't implement it unless neovim support vim8 winbar menus. However, you are welcome to make a pull request.

**Comment by puremourning** [comment]
If, as @bfredl says the neovim api is going to be compatible with Vim's, then it should just be a one line change.

**Comment by UnrealApex** [comment]
Any update on this?

**Comment by puremourning** [comment]
The neovim api is nothing like the vim one. So no.

**Comment by UnrealApex** [comment]
I see. Perhaps some day.

**Comment by puremourning** [comment]
Unlikely, without community contribution.

**Comment by bfredl** [comment]
correct.

**Comment by puremourning** [comment]
Well, I tried to implement this, despite the obtuse "API". Anyway looks like it's blocked by https://github.com/neovim/neovim/issues/23165
