### ISSUE TITLE
how can I install vscode-cpptools manually or use a proxy to install it.

### ISSUE THREAD

**Issue by Banana-Two** [puremourning/vimspector#614]
**Is your feature request related to a problem? Please describe.**
In some places, we have to use a proxy to download some tools from github. But I don't know how to set a proxy for vimspector.

**Describe the solution you'd like**
Add a proxy interface for vimspector like vim-plug.

**Comment by puremourning** [comment]
pretty sure it will obey http_proxy/https_proxy environment vars. 

You can also install it manually any way you like and use custom adapter definitions. see the Docs for that.
