### ISSUE TITLE
[Feature Request]: Stable UI API based on winlayout, winrestcmd and Android LinearLayout

### ISSUE THREAD

**Issue by dkaszews** [puremourning/vimspector#654]
**Is your feature request related to a problem? Please describe.**
I was playing around with current UI customization options and came up with a pattern that in my opinion could be quite an easy way of allowing user to specify custom layout. This is based on `winlayout` and `winrestcmd`, which have following values in the current default layout (sizes dependent on resolution):

```vim
['row', [['col', [['leaf', 1025], ['leaf', 1024], ['leaf', 1023]]], ['col', [['leaf', 1022], ['leaf', 1028], ['leaf', 1026]]]]]

1resize 17|vert 1resize 50|2resize 15|vert 2resize 50|3resize 17|vert 3resize 50|4resize 24|vert 4resize 157|5resize 15|vert 5resize 157|6resize 10|vert 6resize 157|1resize 17|vert 1resize 50|2resize 15|vert
2resize 50|3resize 17|vert 3resize 50|4resize 24|vert 4resize 157|5resize 15|vert 5resize 157|6resize 10|vert 6resize 157|
```

Those can be parsed to restore current layout, as shown in https://vi.stackexchange.com/a/22545

My current setup is to hook into `VimspectorUICreated`, parse the saved layout, then set each window to the buffer I want (e.g. to add breakpoints view where I like).

**Describe the solution you'd like**
Solution described above can be cleaned up into something like this, which can be read by a modified version of window restore script linked above:
```vim
let g:vimspector_ui = {
\ 'type': 'vertical_split;
\ 'children': [
\   {
\     'type': 'horizontal_split',
\     'size': 15
\     'children': [
\       'Variables',
\       'Watches',
\       'Breakpoints',
\       'StackTrace',
\     ]
\   },
\   {
\     'type': 'horizontal_split',
\     'children': [
\       'Source',
\       { 'type': 'Console', 'size': 30 },
\     ]
\   }
\ ],
\}    
```

This solution could be further extended by providing a percentage- or weight-based sizes (Android has [`LinearLayout`](https://developer.android.com/reference/android/widget/LinearLayout) algorithms to handle just that) allowing to run a user-provided command to select or create a buffer for window (I use `term pwsh` a lot), make API conditional, create pseudo-tabs by tying window to multiple buffers with a mapping to select them, etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by puremourning** [comment]
I can't see this happening, sorry.
