### ISSUE TITLE
[Feature Request]: Add ability to debug specific unit test in Go. 

### ISSUE THREAD

**Issue by Tombert** [puremourning/vimspector#667]
**Is your feature request related to a problem? Please describe.**

As of right now, when I write Go code and want to debug, I have to hop to the main function and try and do my debugging from there.  In comparison, if I use something like Goland, I can right click on a unit test and execute it directly.  It would be cool to have this in vimspector. 

**Describe the solution you'd like**

I would like to be able to hit some keystroke while my cursor is inside a unit test, and have the debugger kick off that unit test and *only* that unit test. 

**Describe alternatives you've considered**

My alternative right now has been to hop into Goland when I want to do any kind of debugging. 

**Additional context**

**Comment by puremourning** [comment]
Pretty sure you can already do this. I do this by just using `"program": "${fileDirname}", "mode": "test"` in my configuration. Perhaps delve can be told to run a specific test case, I dunno.

In any event there is zero chance that vimspector will have any language-specific knowledge e.g. to extract the current test name or any such stuff. For that you will either need to write some vimscript or find a plugin that does this for you. maybe  @myitv has some wisdom on that. 

I have various vim scripts that I use to launch various test frameworks by calculating the inputs and then calling `vimspector#LaunchWithSettings( { ... } )`. For example, [here](https://github.com/puremourning/.vim-mac/blob/master/ftplugin/python.vim#L108-L124).

But I certainly don't see this as in scope for Vimspector, which is a DAP client and unless there is a DAP feature or adapter feature that vimspector isn't supporting, I don't think there's anything for vimsepctor to do.

**Comment by Tombert** [comment]
Ah, alright; I think I can accomplish what I need with vim-delve.  Thanks for getting back to me.
