### ISSUE TITLE
[Feature Request]: Add autocmd to save debug session

### ISSUE THREAD

**Issue by zoumi** [puremourning/vimspector#701]
I can use VimspectorUICreated to load debug session when I start debug, while it seem that I can't use VimspectorDebugEnded to save debug session when I exit debug.
So, add a new autocmd VimspectorDebugEndPre?

**Comment by puremourning** [comment]
I'm sorry I really don't understand what you are requesting and why. Please elaborate your use case clearly.

**Comment by zoumi** [comment]
I want to save breakpoints by aotucmd when exit debug without manually call vimspector mk session command.
