### ISSUE TITLE
[Feature Request] Support for armhf (whatever that is)

### ISSUE THREAD

**Issue by slacker-HD** [puremourning/vimspector#703]
### Description

c&cpp debug don't work on raspbian armhf while it works well on raspbian arm64.

when I try :

`install ./install_gadget.py --enable-c
`
I saw:

```
Installing CodeLLDB@v1.7.4...
Checksum matches for /home/pi/.vim/plugged/vimspector/gadgets/linux/download/CodeLLDB/v1.7.4/codelldb-x86_64-linux.vsix, using it
Extracting /home/pi/.vim/plugged/vimspector/gadgets/linux/download/CodeLLDB/v1.7.4/codelldb-x86_64-linux.vsix to /home/pi/.vim/plugged/vimspector/gadgets/linux/download/CodeLLDB/v1.7.4/root
```

It seems we download the wrong architecture of CodeLLDB. On Raspbian armhf it should be arm or armhf but here is x86_64.

I also notice that in `~/.vim/plugged/vimspector/python3/vimspector/gadgets.py`, there is no architecture of arm or armhf in CodeLLDB.

### Works in vim?

Reproducable in Vim

### Works with clean config?

Yes

### Sample project works?

Reproducable with sample project

### Minimal Reproduction

List of steps to reproduce:

1. Run `vim ---clean Nu /path/to/vimspector/support/minimal_vimrc ....`
2. Open _this project_...
3. Press _this sequence of keys_

### Expected Behaviour

c&cpp debug should work on raspbian armhf while it works well on raspbian arm64.

### Actual Behaviour

c&cpp debug don't work.

### Installation Type

Plugin Manager (git clone)

### Vimspector version

5c328b513485675c061558d2f25a98ee503cb243

### Vim version

```Text
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 01 2021 01:51:08)
包含补丁: 1-2434
Extra patches: 8.2.3402, 8.2.3403, 8.2.3409, 8.2.3428
修改者 team+vim@tracker.debian.org
编译者 team+vim@tracker.debian.org
巨型版本 无图形界面。  可使用(+)与不可使用(-)的功能:
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
     系统 vimrc 文件: "$VIM/vimrc"
     用户 vimrc 文件: "$HOME/.vimrc"
 第二用户 vimrc 文件: "~/.vim/vimrc"
      用户 exrc 文件: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
         $VIM 预设值: "/usr/share/vim"
编译方式: gcc -c -I. -Iproto -DHAVE_CONFIG_H -Wdate-time -g -O2 -ffile-prefix-map=/build/vim-Wj0ILV/vim-8.2.2434=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
链接方式: gcc -L. -Wl,-z,relro -Wl,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim -lm -ltinfo -lselinux -lacl -lattr -lgpm -ldl -L/usr/lib -llua5.2 -Wl,-E -fstack-protector-strong -L/usr/local/lib -L/usr/lib/arm-linux-gnueabihf/perl/5.32/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python3.9/config-3.9-arm-linux-gnueabihf -lpython3.9 -lcrypt -lpthread -ldl -lutil -lm -lm -L/usr/lib/arm-linux-gnueabihf -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.7 -lm -L/usr/libpip3
```

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by slacker-HD** [comment]
I solved it with a dirty workground.

1. Download `codelldb-arm-linux.vsix` and change it's name to `codelldb-x86_64-linux.vsix` 
2. Copied  `codelldb-x86_64-linux.vsix`  to `/home/pi/.vim/plugged/vimspector/gadgets/linux/download/CodeLLDB/v1.7.4/` 
3. Modify `~/.vim/plugged/vimspector/python3/vimspector/gadgets.py` at line 534, change the checksum with `codelldb-arm-linux.vsix`'s checksum `21f648e522696e9af4c90cf7fcaa82b7ae52a72431140459fab2ffb3228ceaa5`.
4. Enter `/home/pi/.vim/plugged/vimspector/`  and run `./install_gadget.py --enable-c` again.

Now **the correct architecture of codelldb** was installed and we can use codelldb to debug c&cpp Prgrams.

I believe `vscode-cpptools` has the same problem but don't know where to download it's arm architecture.

**Comment by puremourning** [comment]
I only support installation for aarch64 and x86_64 platforms as those are the only ones I test with. 

You are welcome to install adapters in any way. You don't have to use the installer.

**Comment by puremourning** [comment]
But if you want to make a PR, the simplest thing to do is edit `python3/vimspector/install.py` `GetPlatform()` function to recognise armhf (whatever that is) and then add a block to the gadgets in `gadgets.py` for the arm builds of supported gadgets. Or if armhf is 100% compatible with arm64 (aarch64), then have it return that and it should just work.

Without any device running this architecture, I can't test it so won't be making any changes.

**Comment by slacker-HD** [comment]
I tried to print the information:

machine：armv7l
Machine Info ：('ARM_7', 32)

Thanks.

**Comment by puremourning** [comment]
@slacker-HD  can you try pr #704 ?

**Comment by slacker-HD** [comment]
> 

Thanks. I tested thr armv7 branch with a new installation on Raspbian armhf, and It works correctly.

**Comment by slacker-HD** [comment]
> @slacker-HD can you try pr #704 ?


Thanks. I tested thr armv7 branch with a new installation on Raspbian armhf, and It works correctly.
