### ISSUE TITLE
Default host/port for multi-session attach type

### ISSUE THREAD

**Issue by zbs** [puremourning/vimspector#713]
### Description

Per [these instructions](https://github.com/puremourning/vimspector#python-remote-debugging), I have a debug configuration for attaching to a debug server started by debugpy:
```
{
  "configurations": {
    "Python Attach": {
      "adapter": "multi-session",
      "filetypes": [ "python" ], // optional
      "hot": "localhosthost",
        "port": 5678,
      "configuration": {
        "request": "attach",
        "host": "localhost",
        "port": 5678,
        "pathMappings": [
          // mappings here (optional)
        ]
      }
    }
  }
}
```
I've attempted adding the host and port to the configuration, but it seems like there's no way to make Vimspector read these default values. On launch, it always asks for host and port. Is there any way to save these values?

### Works in vim?

Only broken in Neovim

### Works with clean config?

Yes

### Sample project works?

Not reproducable with sample project

### Minimal Reproduction

List of steps to reproduce:

1. Run a python module with `debugpy --listen`
2. Use the above configuration
3. Open nvim, run `:call vimspector#Launch()`

### Expected Behaviour

Starts debugger without asking for host and port

### Actual Behaviour

Asks for host and port

### Installation Type

Plugin Manager (git clone)

### Vimspector version

HEAD

### Vim version

```Text
NVIM v0.5.0
```

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by puremourning** [comment]
Use

```
"variables": { "host": "my host", "port": "my port" }
```

**Comment by zbs** [comment]
Thank you!
