### ISSUE TITLE
Attaching to existing debugpy debugger

### ISSUE THREAD

**Issue by zbs** [puremourning/vimspector#727]
Prior to vimspector, most of my Python debugging was done in vscode by starting the debugger with
```
 python -m debugpy --wait-for-client --listen 5678 module_name arg1 arg2
```
and then attaching to it in VS Code using the debugpy adapter. In this case, VS Code is not launching the debugger -- it is connecting to the DAP server created by the above invocation. This approach is useful when copying and pasting a long python command (e.g. many args) that I want to debug.

The vimspector debugpy adapter does not work because it assumes you want to launch the debugger. We don't want to do that here, because it has been launched by the separate python command shown above. To get around this, we have to make the `attach` adapter have a no-op command as its `attachCommand`, as follows:
```
{
  "adapters": {
    "python-remote": {
      "host": "localhost",
      "port": 5678,
      "attach": {
        "remote": {
          "attachCommand": [
            "true"
          ],
          "pidCommand": [
            "true"
          ]
        },
        "delay": "1000m" // format as per :help sleep
      }
    }
  },
  "configurations": {
    "Python": {
      "adapter": "python-remote",
      "remote-request": "attach",
      "breakpoints": {
        "exception": {
          "raised": "N",
          "userUnhandled": "N",
          "caught": "",
          "uncaught": "Y"
        }
      },
      "filetypes": [
        "python"
      ],
      "default": true,
      "configuration": {
        "request": "attach",
        "connect": {
          "justMyCode": false
        },
        "pathMappings": [
          {
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}"
          }
        ]
      }
    }
  }
}
```

This feels a little clumsy, so I was wondering if we could support doing this more simply.

**Comment by puremourning** [comment]
Just use the multi-session adapter. Like this https://github.com/puremourning/vimspector#python-remote-debugging

**Comment by zbs** [comment]
This is much better -- thank you.
