### ISSUE TITLE
UpFrame/DownFrame change the current line of the stacktrace window to 1

### ISSUE THREAD

**Issue by Aster89** [puremourning/vimspector#736]
### Description

(To me, it is a bug. But you can re-classify it otherwise.)

Basically moving through the stack via `:call vimspector#DownFrame()`/`:call vimspector#UpFrame()` changes the current line in the StackTrace window to 1, even if last time you visited that window you left the cursor somewhere else.

This can be very annoying when you mix movements via `:call vimspector#DownFrame()`/`:call vimspector#UpFrame()` and navigation in that window. Which can be often the case in huge code bases where, to give my experience, you use `:call vimspector#DownFrame()`/`:call vimspector#UpFrame()` as long as they stay in "your codebase" and want to quickly scan through the stack when you're in system headers.

### Works in vim?

Reproducable in Vim

### Works with clean config?

Yes

### Sample project works?

Not reproducable with sample project

### Minimal Reproduction

List of steps to reproduce:

1. Run `vim ---clean Nu /path/to/vimspector/support/minimal_vimrc some_file`
2. Put a breakpoint step into function (or do whatever fits) to get to a state where the number of line in the stack trace window is big enough, say 10 lines
3. make the stack trace window smaller than the number of lines it contains
4. `set rnu` in the stacktrace win (this is just for visual feedback what happens there)
5. get to its last line, e.g. via <kbd>G</kbd> (not the first line of the stack is out of view, beyond the top line in the window)
6. hit <kbd>Enter</kbd> (now the stacktrace win has numbers going from 0 to some number going from bottom to top)
7. `:call vimspector#DownFrame()`
8. now the stacktrace win, which still has no focus, has the current line being the first one of the buffer, even if it's out of view (you see that the line numbers in the stacktrace win go from some non-zero number on the top to a bigger number on the bottom); but you still see the same view you left at step 6
9. Now move back to the stacktrace window, e.g. via <kbd>Ctrl+W</kbd><kbd>p</kbd>, and you'll see the view snapping to the top.

Here's a similar screencast:
[![asciicast](https://asciinema.org/a/bSBqIXxev5Cnsfh0sG2akYxTT.svg)](https://asciinema.org/a/bSBqIXxev5Cnsfh0sG2akYxTT)

### Expected Behaviour

I would like the stacktrace window to not change its current line if I don't move it. Or at least change it according to where I'm in the stack.

### Actual Behaviour

As soon as `:call vimspector#DownFrame()`/`:call vimspector#UpFrame()`  is executed, the current line in the stacktrace win becomes line 1, so moving to that window will viewport will jump.

### Installation Type

Plugin Manager (git clone)

### Vimspector version

1dba52e6e886bc60184da405a11f8ec22d2f2b49

### Vim version

```Text
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Mar 21 2023 20:51:42)
Included patches: 1-1420
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       +tcl/dyn
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
+balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
+browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl/dyn          +title
+channel           +ipv6              +persistent_undo   +toolbar
+cindent           +job               +popupwin          +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3/dyn       +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby/dyn          +wildignore
+cursorbind        +lua/dyn           +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con_gui    +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            +X11
+digraphs          +mouse             +sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        +mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cloudproviders -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -pthread -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/vim/src=/usr/src/debug/vim -flto=auto -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.36/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -L/usr/local/lib -o vim -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lelf -lcanberra -lacl -lattr -lgpm -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.36/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto -fstack-protector-strong -L/usr/local/lib -L/usr/lib/perl5/5.36/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm
```

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by puremourning** [comment]
I can no longer repro this after #141
