### ISSUE TITLE
[Feature Request]: Editing conditional breakpoints' conditions in the breakpoint window

### ISSUE THREAD

**Issue by Aster89** [puremourning/vimspector#737]
**Is your feature request related to a problem? Please describe.**
It's probably a niche usecase, but I report it just in case. Recently, in debugging some bugged code I really had little clue about, I had to do the following:
  1. set 1 breakpoint at a given line where a pointer value was available
  2. run the program
  3. when the program stops a that breakpoint, inspect that pointer (say the value is `0xFOO123`)
  4. set _a lot_ of conditional breakpoints around with the condition that `someLocalPtr == 0xFOO123`.

Clearly, from run to run, `0xFOO` would change, so I had to manually reset the condition of every single one of the several breakpoints I set at step 4.

**Describe the solution you'd like**
Well, I guess that if I could edit the conditions of breakpoints in the breakpoint window, I could use all the power of Vim, such as visual block editing, `.`, macros, ...

**Describe alternatives you've considered**
It's not a scenario that happens frequently, so the alternative I have is to become quick at <kbd>Ctrl+P</kbd> to set for a conditional breakpoint the same condition as the previous one.

**Additional context**

**Comment by puremourning** [comment]
Yeah agree. We should have this. I think we should add a way to edit breakpoint properties and add a mapping/WinBar button to the breakpoint window. Simple re-running of the set up with the existing values defaulted seems simplest.
