### ISSUE TITLE
[Feature Request]: support for Windows

### ISSUE THREAD

**Issue by hulucc** [puremourning/vimspector#74]
Vim is supporting windows, as well as the dap and python3. 
So why windows is not supported? Is it possiable?

**Comment by puremourning** [comment]
As I said in the README, it’s not that it’s impossible (it’s surely possible, indeed easy to to) I just don’t use windows so I would need a volunteer to own windows support, CI, etc.

**Comment by hulucc** [comment]
It sounds there's a chance already works on windows. I will have a try.

**Comment by puremourning** [comment]
I would be surprised. 

At the very least (based on YCM experience), these are things to look at:

- the URI handling will not work properly 
- the install script won’t work
- I would be surprised if the adapter shutdown worked totally correctly 
- other windows file system foibles like locking files

**Comment by puremourning** [comment]
I had a quick go at making at least the python debug environment work on vimspector. Wasn't totally straightforward (hit quite a few OS-invariant bugs when the adapter doesn't start up), but after fixing one issue with paths, and turning off some stuff that relies on `tail -f` (!) it sorta works:

<img width="1680" alt="Screenshot 2020-01-03 at 00 15 52" src="https://user-images.githubusercontent.com/10584846/71700929-751b9700-2dbe-11ea-89e9-2ebae0810a98.png">

**Comment by puremourning** [comment]
I've pushed a branch `windows` with the changes; try it out. The installer won't work for most things, but I sort of hope you should be able to get it to work with most adapters that work on windows.

**Comment by blayz3r** [comment]
Will the windows branch be merged. It would be good to have windows support even for one language

**Comment by puremourning** [comment]
does it work for you ?

**Comment by blayz3r** [comment]
Was able to get to work for Windows python

![image](https://user-images.githubusercontent.com/12205650/74609564-47ae5280-50b9-11ea-842b-9455af650378.png)
