### ISSUE TITLE
Python terminals buffers are not closed after exiting Vimspector

### ISSUE THREAD

**Issue by dr-costas** [puremourning/vimspector#776]
### Description

Hi, 

When doing debugging in Python with Vimspector, there is a terminal/output console created. When exiting the Vimspector, this buffer is not wiped out but remains open. 

### Works in vim?

Reproducable in Vim

### Works with clean config?

Yes

### Sample project works?

Not reproducable with sample project

### Minimal Reproduction

List of steps to reproduce:

1. Run `vim ---clean Nu /path/to/vimspector/support/minimal_vimrc ....`
2. Open _this project_...
3. Press _this sequence of keys_

### Expected Behaviour

The terminal/output buffer(s) should be closed/wiped when exiting Vimspector.

### Actual Behaviour

The terminal/output buffer(s)are not closed/wiped when exiting Vimspector.

### Installation Type

Plugin Manager (git clone)

### Vimspector version

2dd35dede7712403645a484b6dc5fa23c25172b2

### Vim version

```Text
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr 13 2023 18:15:54)
macOS version - arm64
Included patches: 1-1450
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby              +wildignore
+cursorbind        +lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      +sodium            -X11
+digraphs          +mouse             +sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static
```

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by dr-costas** [comment]
> Please can you complete steps to repro using minimal config and example project?On 9 Jun 2023, at 12:35, Konstantinos Drossos ***@***.***> wrote:﻿ Description Hi, When doing debugging in Python with Vimspector, there is a terminal/output console created. When exiting the Vimspector, this buffer is not wiped out but remains open. Works in vim? Reproducable in Vim Works with clean config? Yes Sample project works? Not reproducable with sample project Minimal Reproduction List of steps to reproduce: Run vim ---clean Nu /path/to/vimspector/support/minimal_vimrc .... Open this project... Press this sequence of keys Expected Behaviour The terminal/output buffer(s) should be closed/wiped when exiting Vimspector. Actual Behaviour The terminal/output buffer(s)are not closed/wiped when exiting Vimspector. Additional information No response Installation Type Plugin Manager (git clone) Vimspector version [2dd35de](https://github.com/puremourning/vimspector/commit/2dd35dede7712403645a484b6dc5fa23c25172b2) Debug Info No response Log file No response Vim version VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr 13 2023 18:15:54) macOS version - arm64 Included patches: 1-1450 Compiled by Homebrew Huge version without GUI. Features included (+) or not (-): +acl +file_in_path +mouse_urxvt -tag_any_white +arabic +find_in_path +mouse_xterm -tcl +autocmd +float +multi_byte +termguicolors +autochdir +folding +multi_lang +terminal -autoservername -footer -mzscheme +terminfo -balloon_eval +fork() +netbeans_intg +termresponse +balloon_eval_term +gettext +num64 +textobjects -browse -hangul_input +packages +textprop ++builtin_terms +iconv +path_extra +timers +byte_offset +insert_expand +perl +title +channel +ipv6 +persistent_undo -toolbar +cindent +job +popupwin +user_commands -clientserver +jumplist +postscript +vartabs +clipboard +keymap +printer +vertsplit +cmdline_compl +lambda +profile +vim9script +cmdline_hist +langmap -python +viminfo +cmdline_info +libcall +python3 +virtualedit +comments +linebreak +quickfix +visual +conceal +lispindent +reltime +visualextra +cryptv +listcmds +rightleft +vreplace +cscope +localmap +ruby +wildignore +cursorbind +lua +scrollbind +wildmenu +cursorshape +menu +signs +windows +dialog_con +mksession +smartindent +writebackup +diff +modify_fname +sodium -X11 +digraphs +mouse +sound -xfontset -dnd -mouseshape +spell -xim -ebcdic +mouse_dec +startuptime -xpm +emacs_tags -mouse_gpm +statusline -xsmp +eval -mouse_jsbterm -sun_workshop -xterm_clipboard +ex_extra +mouse_netterm +syntax -xterm_save +extra_search +mouse_sgr +tag_binary -farsi -mouse_sysmouse -tag_old_static Python version No response Neovim diagnostics No response Operating System No response Declaration I have read and understood CONTRIBUTING.md I have read and understood the CODE_OF_CONDUCT.md —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Ho, 

Sorry, I cannot find how to run the minimal example project. Can you please indicate how to do it?

**Comment by dr-costas** [comment]
I tried with `vim --clean Nu ~/.vim/plugged/vimspector/support/minimal_vimrc ` but Vim doesn't have the Vimspector commands in it and I cannot start Vimspector.

Actually, the very first time I issued the above command, I could see Vimspector's commands with `<Tab>` in Vim, but after I quoted and re-issued the clean Vim I could not see again Vimspector.

**Comment by puremourning** [comment]
You missed out a - before Nu 'vim -Nu ...'

**Comment by dr-costas** [comment]
OK. Now it worked. I could run a debug session. 

Indeed, when I do `:VispectorReset` then the `:buffers` returns only my script buffer and not the terminal buffer from Vimspector. 

Any insights to what causes that problem? I'm using the following plugins: 

```vim
Plug 'jiangmiao/auto-pairs'
Plug 'psf/black', { 'branch': 'stable'  }
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'chrisbra/csv.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'morhetz/gruvbox'
Plug 'Yggdroot/indentLine'
Plug 'itchyny/lightline.vim'
Plug 'taohexxx/lightline-buffer'
Plug 'preservim/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'vim-python/python-syntax'
Plug 'preservim/tagbar'
Plug 'ryanoasis/vim-devicons'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'fisadev/vim-isort'
Plug 'tpope/vim-markdown'
Plug 'heavenshell/vim-pydocstring', { 'do': 'make install' }
Plug 'sillybun/vim-repl'
Plug 'tibabit/vim-templates'
Plug 'puremourning/vimspector'
Plug 'mhinz/vim-startify'
Plug 'tpope/vim-surround'
```

and when I'm issuing `:VimspectorReset`, the output buffers opened from Vimspector need to be manually wiped out (using `bw ...`).

**Comment by puremourning** [comment]
You will need to isolate the issue/plug-in conflict.
