### ISSUE TITLE
Cannot install debugpy gadget: Checksum does not match expected

### ISSUE THREAD

**Issue by kael-k** [puremourning/vimspector#785]
### Description

I am trying to install the debugpy gadget for vimspector in a nvim environment, but the installation fails both from `:VimspectorInstall debugpy` and `./install_gadget.py --verbose --enable-python`

```
❯ ./install_gadget.py --verbose --enable-python
Installing debugpy@1.6.7...
Checksum doesn't match for /home/kael_k/.local/share/nvim/plugged/vimspector/gadgets/linux/download/debugpy/1.6.7/v1.6.7.zip, removing it
Removing existing /home/kael_k/.local/share/nvim/plugged/vimspector/gadgets/linux/download/debugpy/1.6.7/v1.6.7.zip
Downloading https://github.com/microsoft/debugpy/archive/v1.6.7.zip to /home/kael_k/.local/share/nvim/plugged/vimspector/gadgets/linux/download/debugpy/1.6.7/v1.6.7.zip
Traceback (most recent call last):
  File "/home/kael_k/.local/share/nvim/plugged/vimspector/./python3/vimspector/installer.py", line 529, in InstallGadget
    file_path = DownloadFileTo(
                ^^^^^^^^^^^^^^^
  File "/home/kael_k/.local/share/nvim/plugged/vimspector/./python3/vimspector/installer.py", line 674, in DownloadFileTo
    raise RuntimeError(
RuntimeError: Checksum for /home/kael_k/.local/share/nvim/plugged/vimspector/gadgets/linux/download/debugpy/1.6.7/v1.6.7.zip (9b99b2e33aa7331e254ac2fd3a71de85ca1d33da53b162f69275da92b6755836) does not match expected 59b441c3ddac3de9d47fd75a1766cf5636f09b281f907717c769149f86aa106e
 - FAILED installing debugpy: Checksum for /home/kael_k/.local/share/nvim/plugged/vimspector/gadgets/linux/download/debugpy/1.6.7/v1.6.7.zip (9b99b2e33aa7331e254ac2fd3a71de85ca1d33da53b162f69275da92b6755836) does not match expected 59b441c3ddac3de9d47fd75a1766cf5636f09b281f907717c769149f86aa106e
Failed to install adapters:
 * debugpy
```

I tried recreating `/home/kael_k/.local/share/nvim/plugged/vimspector` and reinstall with vim-plug but I got the same error.

So i tried to download manually the zip and check the checksum. The computed checksum from the downloaded zip by vimspector is infact the same I get by manually downloading and validate the checksum

```
❯ curl -L -o - https://github.com/microsoft/debugpy/archive/v1.6.7.zip | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 7143k    0 7143k    0     0  1220k      0 --:--:--  0:00:05 --:--:-- 1429k
9b99b2e33aa7331e254ac2fd3a71de85ca1d33da53b162f69275da92b6755836  -
```

Given the checksum of the manual check, it seems to me that the checksum in `python3/vimspector/gadgets.py` is wrong
https://github.com/puremourning/vimspector/blob/95791ba3eb2e7d60de7faa4d5c13280ade356a0b/python3/vimspector/gadgets.py#L109-L119

### Works in vim?

Reproducable in Vim

### Works with clean config?

Yes

### Sample project works?

No sample project for this filetype

### Minimal Reproduction

List of steps to reproduce:

1.  `curl -L -o - https://github.com/microsoft/debugpy/archive/v1.6.7.zip | sha256sum`

### Expected Behaviour

./install_gadget.py install debugy v1.6.7

### Actual Behaviour

./install_gadget.py does not install debugy v1.6.7

### Installation Type

Plugin Manager (git clone)

### Vimspector version

95791ba3eb2e7d60de7faa4d5c13280ade356a0b

### Vim version

```Text
❯ nvim --version
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=always -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include -I/var/tmp/portage/app-editors/neovim-0.9.0-r1/work/neovim-0.9.0_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-0.9.0-r1/work/neovim-0.9.0_build/include -I/var/tmp/portage/app-editors/neovim-0.9.0-r1/work/neovim-0.9.0_build/cmake.config -I/var/tmp/portage/app-editors/neovim-0.9.0-r1/work/neovim-0.9.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Python version

3.11.4 (main, Jun 26 2023, 07:08:00) [GCC 12.2.1 20230428]

### Operating System

 Linux kaelk-T495 6.1.41-gentoo-dist-hardened #1 SMP PREEMPT_DYNAMIC Fri Jul 28 21:08:04 CEST 2023 x86_64 AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx AuthenticAMD GNU/Linux

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by eduardomezencio** [comment]
I see you closed this issue, but I was having a checksum issue with debugpy just now. I decided to check the file myself and I found that the checksum for v1.6.7.zip is exactly the same it was before, and commit 61fb528 broke it for me. The sha256sum is precisely '59b441c3ddac3de9d47fd75a1766cf5636f09b281f907717c769149f86aa106e'.

I'm trying to understand exactly what you meant with 'GitHub sometimes changes the checksums'. To change the checksum they would need to change the file itself. As long as the file is the same, the checksum cannot change. Is there something I got wrong here?

**Comment by puremourning** [comment]
> I see you closed this issue, but I was having a checksum issue with debugpy just now. I decided to check the file myself and I found that the checksum for v1.6.7.zip is exactly the same it was before, and commit 61fb528 broke it for me. The sha256sum is precisely '59b441c3ddac3de9d47fd75a1766cf5636f09b281f907717c769149f86aa106e'.
> 
> 
> 
> I'm trying to understand exactly what you meant with 'GitHub sometimes changes the checksums'. To change the checksum they would need to change the file itself. As long as the file is the same, the checksum cannot change. Is there something I got wrong here?

Preciously MS just re-encoded/compressed all the zips and/or changed the algorithm. We can't assume they even store the files as is. 

Anyway if the SHA has changed again then this is a more serious problem. But I can't diagnose that from a comment. Need a full issue. All I can say is I was able to repro when this issue was raised/fixed.

**Comment by eyalz800** [comment]
After this fix I appear to be getting this:
Checksum for /home/runner/.vim/plugged/vimspector/gadgets/linux/download/debugpy/1.6.7/v1.6.7.zip (59b441c3ddac3de9d47fd75a1766cf5636f09b281f907717c769149f86aa106e) does not match expected 9b99b2e33aa7331e254ac2fd3a71de85ca1d33da53b162f69275da92b6755836

**Comment by puremourning** [comment]
I dunno what is going on at github but I have reverted this change. In future, if you have an issue please raise a *new* issue, completing the full issue template.
