### ISSUE TITLE
netcoredbg: macos arm64 archive contains x86_64 build

### ISSUE THREAD

**Issue by bradyslot** [puremourning/vimspector#794]
### Description

The downloaded archive of netcoredbg is named deceptively.

<img width="843" alt="Screenshot 2023-09-01 at 1 04 48 pm" src="https://github.com/puremourning/vimspector/assets/11919969/883235e0-aff6-47e5-af1b-722a458ea98f">

What's actually provided in the archive is a build for x86_64.

<img width="843" alt="Screenshot 2023-09-01 at 1 05 26 pm" src="https://github.com/puremourning/vimspector/assets/11919969/cf60a5b0-dc3c-43ac-86c6-b99d55662d8b">

netcoredbg can be built for arm64, and replacing the downloaded gadget with my own fixes the issue.

### Is it reproducible in vim?

Reproducible in Vim

### Works with clean config?

Yes

### Sample project works?

Not reproducible with sample project

### Minimal Reproduction

List of steps to reproduce:

On Apple Silicon Macos:

1. Install Vimspector however you prefer
2. Open vim/nvim and run :VimspectorInstall netcoredgb
3. Observe filetype using `file` command

### Expected Behaviour

Expected to install netcoredbg built for arm64 macos

### Actual Behaviour

Installs netcoredbg built for x86_64

### Installation Type

Plugin Manager (git clone)

### Vimspector version

4e49a1782e34433410f96602640a05c9ec00a65f

### Vim version

```Text
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"
```

### Operating System

Darwin steelix.lan 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64 arm Darwin

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by puremourning** [comment]
Last time I looked there was no arm64 build for netcoredbg. Vimspector currently installs:

      'version': '2.2.0-974'

Looks like there is a 2.2.3-992 which has an arm64 build.

PR welcome to update the gadget and verify the tests on macOS arm

**Comment by bradyslot** [comment]
You're totally right, for some reason I read amd64 as arm64.
I'm such a doofus.
