### ISSUE TITLE
The demo images are broken

### ISSUE THREAD

**Issue by nonsleepr** [puremourning/vimspector#8]
`README.md` links to C-demo and Python-demo (I assume, gifs). The links for those demos are broken.

**Comment by puremourning** [comment]
Yeah, thanks. I need to find some other suitable way of hosting them. I'll also need to record some new demos as lots has changed since the originals.

**Comment by puremourning** [comment]
I'm reworking the readme at the moment and will put up some new demos soon.

**Comment by puremourning** [comment]
Readme reworked and a new website created with screenshots/tutorial: https://puremourning.github.io/vimspector-web
