### ISSUE TITLE
[Nvim Install without GUI]  python3/vimspector/installer.py report room

### ISSUE THREAD

**Issue by PannenetsF** [puremourning/vimspector#806]
### Description

I have to pack the neovim with vimspector to some docker only in scripts without any interactive operations. 

This is related to the line https://github.com/PannenetsF/vimspector/blob/5d9643584fe9238d0ed5bdc9aff353c530ff682b/python3/vimspector/installer.py#L149

In fact, it just open a buffer to show the installer info, so I wonder if we can call the this command without UIs? 

### Is it reproducible in vim?

Only broken in Neovim

### Works with clean config?

Yes

### Sample project works?

No sample project for this filetype

### Minimal Reproduction

List of steps to reproduce:

1. Config of packer 
```
-- This file can be loaded by calling `lua require('plugins')` from your init.vim

-- Only required if you have packer configured as `opt`
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function(use)
  -- Packer can manage itself
  use "puremourning/vimspector"
end)
```
2. Run `nvim -V2 log -i None -c "VimspectorInstall debugpy" -c "qa".`

### Expected Behaviour

Installation completed. 

### Actual Behaviour

which report 
```
root@7ca7f5e58d8b:/workspace# lvim -Es -V1 log -i None -c "VimspectorInstall debugpy" -c "qa"
"log" [New File]
Error detected while processing command line..function vimspector#Install[5]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.local/share/lunarvim/site/pack/lazy/opt/vimspector/python3/vimspector/installer.py", line 153, in RunInstaller
    vim.command( f'botright { settings.Int( "bottombar_height" ) }new' )
  File "/root/.local/lib/python3.10/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: command line..function vimspector#Install[5]..provider#python3#Call[18]..vimspector#Install, line 5: Vim(new):E36: Not enough room
```

### Installation Type

Plugin Manager (git clone)

### Vimspector version

831530b85aad02f2c465047a21452409bfaaf784

### Vim version

```Text
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Python version

Python 3.10.6

### Operating System

Linux 7ca7f5e58d8b 5.14.0-284.25.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Aug 2 14:53:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Declaration

- [X] I have read and understood [CONTRIBUTING.md](https://github.com/puremourning/vimspector/blob/master/CONTRIBUTING.md#diagnostics)
- [X] I have read and understood the [CODE_OF_CONDUCT.md](https://github.com/puremourning/vimspector/blob/master/CODE_OF_CONDUCT.md)

**Comment by puremourning** [comment]
I think you are trying to run the vimspector installer script non-interactively?

Just run the script: https://github.com/puremourning/vimspector/#install_gadgetp, don't use :VimspectorInstall.

But if you (for some reason) really want to do that, you have to use the `VimspectorInstallSuccess` and `VimspectorInstallFailed` user-auto commands because the install is asynchronous. This is what the test system does: https://github.com/puremourning/vimspector/blob/master/run_tests#L220

But seriously, just use the script, or install debugpy yourself with `pip install debugpy`

**Comment by PannenetsF** [comment]
Thanks for the reply! The method indeed worked
