### ISSUE TITLE
What about a platformio integration?

### ISSUE THREAD

**Issue by ubaldot** [puremourning/vimspector#821]
My request may not make sense as I just discovered DAP, but yet I try. :p 

I think it would be handy to have a debugger for embedded systems in Vim.
I am using platformio and it seems that they already did lot of [debugging config work](https://docs.platformio.org/en/latest/plus/debugging.html) for many boards.

I am wondering how and if vimspector can connect to the platformio debugging framework.
The desired feature is that once you have selected a board and a probe, then with "1-click" you have the debugger ready to be used. 

Would that make sense?

**Comment by puremourning** [comment]
If there is a conforming debug adapter for the platform then vimspector should work without changes.

I will not be adding anything unique or specific to vimspector for this niche case.
