### ISSUE TITLE
[Bug report]: Please make it simple to setup

### ISSUE THREAD

**Issue by LinArcX** [puremourning/vimspector#88]
**Is your feature request related to a problem? Please describe.**
Hi. I'm not sure is it a bug report or feature request! But let me first thank you for neovim support. I'm so glad to see [that PR](https://github.com/puremourning/vimspector/pull/77) merged eventually. :)

I read **README** file and [these instructions](https://puremourning.github.io/vimspector-web/demo-setup.html) for setting up vimspector.

But after reading some lines, let me confess: I got confused!
First, please update **README** and that page, becuase there are some differences for setting up in vim vs neovim. For example [here](https://github.com/puremourning/vimspector#installation):
> Untar the release tarball for your OS into $HOME/.vim/pack:

I downloaded latest release tarball and i don't have any idea where should i put it and what  should i do after that! Actually you said:
> Configure your project's debug profiles (create .vimspector.json)

But i don't have any idea how do that.

Please, please make the installation process easier.

**Comment by LinArcX** [comment]
OK. I figured it out how to simply install it:
1. If you are using plugin managers like Plug, add this line to your __init.vim__:
`Plug 'puremourning/vimspector'`
2. Run this command after that: `:PlugInstall`
3. vimspector is in this directory now:
`/home/$USER/.config/nvim/plugged/vimspector/`
4. To install gadgets, go to that directory and start installing some gadgets(For instance i installed vscode-cpptools gadget):
`./install_gadget.py --enable-c`
5. Create a file named `/path/to/vimspector/gadgets/linux/.gadgets.d/lldb-vscode.json`:
```
{
  "adapters": {
    "lldb-vscode": {
      "variables": {
        "LLVM": {
          "shell": "brew --prefix llvm"
        }
      },
      "attach": {
        "pidProperty": "pid",
        "pidSelect": "ask"
      },
      "command": [
        "${LLVM}/bin/lldb-vscode"
      ],
      "env": {
        "LLDB_LAUNCH_FLAG_LAUNCH_IN_TTY": "YES"
      },
      "name": "lldb"
    }
  }
}
```
5. Now go to your project that you are developing and create a file called: `.vimspector.json` and put these lines into it:
```{
  "configurations": {
    "<name>: Launch": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "name": "<name>",
        "type": "cppdbg",
        "request": "launch",
        "program": "<path to binary>",
        "args": [ ... ],
        "cwd": "<working directory>",
        "environment": [ ... ],
        "externalConsole": true,
        "MIMode": "lldb"
      }
    },
    "<name>: Attach": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "name": "<name>: Attach",
        "type": "cppdbg",
        "request": "attach",
        "program": "<path to binary>",
        "MIMode": "lldb"
      }
    }
    ...
  }
}```
Tip: Don't forget to specify the actual path of compiled program with debug symbols.
Till now i can set breakpoints with: `:call vimspector#ToggleBreakpoint()`, But if i try to start debugging:`:call vimspector#Launch()`, i'll get this error message:
```
Error detected while processing function vimspector#Launch[1]..provider#python3#Call:                                                                  
line   18:                                                                                                                                             
Error invoking 'python_execute' on channel 6 (python3-script-host):                                                                                    
Traceback (most recent call last):                                                                                                                     
  File "<string>", line 1, in <module>                                                                                                                 
  File "/home/linarcx/.config/nvim/plugged/vimspector/python3/vimspector/debug_session.py", line 93, in Start                                          
    database = json.load( f )                                                                                                                          
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load                                                                                        
    return loads(fp.read(),                                                                                                                            
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads                                                                                       
    return _default_decoder.decode(s)                                                                                                                  
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode                                                                                       
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                  
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode                                                                                   
    raise JSONDecodeError("Expecting value", s, err.value) from None                                                                                   
json.decoder.JSONDecodeError: Expecting value: line 10 column 19 (char 285)                                                                            
Press ENTER or type command to continue  
```

**Comment by LinArcX** [comment]
With help of this site, i've found out that my .vimspector.json file is incorrect. This is correct one:
```
{
  "configurations": {
    "<name>: Launch": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "name": "<name>",
        "type": "cppdbg",
        "request": "launch",
        "program": "/mnt/D/WorkSpace/C++/cpp/projects/active/neodm/debug/neodm",
        "cwd": "<working directory>",
        "externalConsole": true,
        "MIMode": "lldb"
      }
    },
    "<name>: Attach": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "name": "<name>: Attach",
        "type": "cppdbg",
        "request": "attach",
        "program": "/mnt/D/WorkSpace/C++/cpp/projects/active/neodm/debug/neodm",
        "MIMode": "lldb"
      }
    }
  }
}
```
After that i run this command: `:call vimspector#Launch()` and select __Launch__, but i see empty buffers:

**Comment by oblitum** [comment]
Example VIM-PLUG auto install/update:

```vim
Plug 'puremourning/vimspector', {'do': './install_gadget.py --enable-c --enable-python'}
```

**Comment by puremourning** [comment]
Installation is as easy as any other vim plugin. Configuration is no more difficult than VSCode. I’m 1 person and they are Microsoft, so while I’m open to suggestions, they will need to be more specific.
