### ISSUE TITLE
[Question] Gdb console is not modifiable

### ISSUE THREAD

**Issue by phcerdan** [puremourning/vimspector#92]
First, thanks for the plugin, is looking great!
I am testing it in neovim 0.4.3
```
Plug 'puremourning/vimspector', {'do': './install_gadget.py --enable-c --enable-python'}
```
`.vimspector.json`
```
{
  "configurations": {
    "<name>: Launch": {
      "adapter": "vscode-cpptools",
      "configuration": {
        "name": "<name>",
        "type": "cppdbg",
        "request": "launch",
        "program": "path/to/testSplitFunctions",
        "cwd": "/path/to/build",
        "environment": [],
        "MIMode": "gdb"
      }
    }
}
```

When running, the vimspector.Console buffer is not modifiable
![Screenshot from 2020-01-25 10-20-27](https://user-images.githubusercontent.com/3021667/73119016-5e4f0700-3f5c-11ea-9e08-5d0e9548a2b8.png)

Maybe this is in the area of `vscode` configuration, but it would be great to have a minimal example with interactive `gdb` in the docs.

Thanks

**Comment by puremourning** [comment]
Please complete the issue template. It contains important diagnostics which help answer the question 

If your on Linux, set externalConsole: true and it will launch your app in a new console. 

If you want to send commands to the debugger, use VimspectorEval, or stop using neovim and use vim

**Comment by phcerdan** [comment]
> If you are on Linux, set externalConsole: true and it will launch your app in a new console.

I set it, but doesn't change that the buffer with the gdb console is not modifiable.
Trying it with vim, the console is modifiable, which I expect should be the behavior in nvim too. Or this is expected? Thanks

**Comment by puremourning** [comment]
> Trying it with vim, the console is modifiable, which I expect should be the behavior in nvim too. Or this is expected? Thanks

yes it is, due to a missing feature in neovim.

**Comment by puremourning** [comment]
In case it wasn’t clear you can use VimspectorEval command instead of entering insert mode in the Console window
